import * as THREE from 'three';
import { EffectComposer, RenderPass, EffectPass, BloomEffect } from 'postprocessing';
import { VisualFamilyLock } from '../warp/VisualFamilyLock.js';
import { ContinuityGuard } from '../warp/ContinuityGuard.js';
import { WarpVariationEngine } from '../warp/WarpVariationEngine.js';
import { WarpContinuityDirector } from '../warp/WarpContinuityDirector.js';
import { OpticalFlowController } from '../warp/OpticalFlowController.js?v=20260812-15';
import { JourneyNarrativeDirector } from '../warp/JourneyNarrativeDirector.js?v=20260812-14';
import { WarpFieldManager } from '../warp/WarpFieldManager.js?v=20260813-42';
import { AdaptiveQualityManager } from '../performance/AdaptiveQualityManager.js';
import { WebGPUComputeEnhancer } from '../performance/WebGPUComputeEnhancer.js?v=20260813-42';
import { runtimeCapabilities } from '../capabilities/RuntimeCapabilityRegistry.js';

export class InterstellarWarpScene{
 constructor(container){
  this.container=container;this.scene=new THREE.Scene();this.scene.background=null;this.camera=new THREE.PerspectiveCamera(64,1,.1,260);this.camera.position.set(0,0,0);this.camera.lookAt(0,0,-1);
  this.renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance',alpha:true,premultipliedAlpha:true,stencil:false});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.66;this.renderer.setClearColor(0x000000,0);this.container.appendChild(this.renderer.domElement);runtimeCapabilities.attachRenderer(this.renderer);
  const mobile=/iPad|iPhone|Android/i.test(navigator.userAgent||'')||innerWidth<800,maxStars=mobile?900:1400;
  this.composer=new EffectComposer(this.renderer,{multisampling:0});this.renderPass=new RenderPass(this.scene,this.camera);this.bloomEffect=new BloomEffect({intensity:.12,luminanceThreshold:.75,luminanceSmoothing:.055,mipmapBlur:true,radius:.22,levels:mobile?4:6});this.effectPass=new EffectPass(this.camera,this.bloomEffect);this.effectPass.renderToScreen=true;this.composer.addPass(this.renderPass);this.composer.addPass(this.effectPass);runtimeCapabilities.mark('postprocessing',true,{version:'6.39.4',effects:['BloomEffect'],mobileLevels:mobile?4:6,active:true});
  this.warpField=new WarpFieldManager(maxStars);this.scene.add(this.warpField.group);
  this.webgpu=new WebGPUComputeEnhancer();void this.webgpu.init().then(()=>this.webgpu.applyToRaymarcher(this.warpField.nebula));
  this.familyLock=new VisualFamilyLock();this.continuityGuard=new ContinuityGuard();this.variationEngine=new WarpVariationEngine();this.director=new WarpContinuityDirector(this.variationEngine,this.familyLock,this.continuityGuard);this.journey=new JourneyNarrativeDirector();this.narrative={stage:'DETACHMENT',heartbeat:0,livingLight:0,galaxyReveal:0,idealized:0,lifeReview:0,boundary:0,returnForce:0,returnFlash:0,finalFade:0,detachment:0,hookPresence:0,turnX:0,turnY:0};this.opticalFlow=new OpticalFlowController();this.quality=new AdaptiveQualityManager(this.renderer,this.composer,maxStars);this.state=this.director.state;this.externalHeartPulse=0;this.heartLightFade=0;this.lastDt=1/60;this.resize=this.resize.bind(this);addEventListener('resize',this.resize,{passive:true});this.resize();
 }
 setExternalHeartPulse(pulse,fade){this.externalHeartPulse=Math.max(0,Math.min(1,pulse||0));this.heartLightFade=Math.max(0,Math.min(1,fade||0));}
 resize(){const w=Math.max(1,this.container.clientWidth||innerWidth),h=Math.max(1,this.container.clientHeight||innerHeight);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false);this.composer.setSize(w,h);}
 update(dt,features,musicalState,progress=0){this.lastDt=dt;const base=this.director.update(features,musicalState,dt);this.narrative=this.journey.update(dt,features,musicalState,progress);this.state=this.journey.apply(base,this.narrative);this.state.audioHeartPulse=this.externalHeartPulse;this.state.heartLightFade=this.heartLightFade;this.opticalFlow.update(dt,this.state,features);this.camera.fov+=(this.state.fov-this.camera.fov)*(1-Math.exp(-1.8*dt));this.camera.position.x+=(0-this.camera.position.x)*(1-Math.exp(-3.0*dt));this.camera.position.y+=(0-this.camera.position.y)*(1-Math.exp(-3.0*dt));this.camera.lookAt(0,0,-1);this.camera.rotation.z+=(0-this.camera.rotation.z)*(1-Math.exp(-3.0*dt));this.camera.updateProjectionMatrix();this.warpField.update(dt,this.state,features,{x:0,y:0,bank:0});const pulse=this.warpField.starTunnel.pulseLevel||0,heart=this.state.heartPulse||0,living=this.state.livingLight||0,reveal=this.state.galaxyReveal||0,ideal=this.state.idealized||0,wisps=this.warpField.galacticWisps?.maxOpacity||0,sector=this.warpField.deepSpace?.maxPresence||0,external=this.externalHeartPulse*this.heartLightFade,finalFade=this.state.finalFade||0;const baseBloom=.052+this.state.bloom*.15+pulse*.018+heart*.032+living*.030+reveal*.022+wisps*.016+sector*.008+external*.060,bloomTarget=Math.min(.24,baseBloom)*(1-finalFade*(1-this.heartLightFade)*.96),k=1-Math.exp(-2*dt);this.bloomEffect.intensity+=(bloomTarget-this.bloomEffect.intensity)*k;this.bloomEffect.mipmapBlurPass.radius=.17+this.state.warpIntensity*.028+living*.016+reveal*.008+wisps*.008+sector*.003+external*.022;this.bloomEffect.luminanceMaterial.threshold=.75-living*.010-reveal*.007-external*.020;const exposureTarget=(.62+this.state.warpIntensity*.030+heart*.014+living*.028+reveal*.038+ideal*.012+wisps*.012+sector*.018+external*.040)*(1-finalFade*(1-this.heartLightFade)*.99);this.renderer.toneMappingExposure+=(exposureTarget-this.renderer.toneMappingExposure)*(1-Math.exp(-1.6*dt));this.quality.update(dt,this.warpField.starTunnel);}
 render(){this.renderer.setClearColor(0x000000,0);this.composer.render(this.lastDt);}
 dispose(){removeEventListener('resize',this.resize);this.warpField.dispose();this.effectPass.dispose?.();this.bloomEffect.dispose?.();this.composer.dispose();this.renderer.dispose();this.renderer.domElement.remove();}
}
