import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { VisualFamilyLock } from '../warp/VisualFamilyLock.js';import { ContinuityGuard } from '../warp/ContinuityGuard.js';import { WarpVariationEngine } from '../warp/WarpVariationEngine.js';import { WarpContinuityDirector } from '../warp/WarpContinuityDirector.js';import { OpticalFlowController } from '../warp/OpticalFlowController.js?v=20260812-15';import { JourneyNarrativeDirector } from '../warp/JourneyNarrativeDirector.js?v=20260812-14';import { WarpFieldManager } from '../warp/WarpFieldManager.js?v=20260812-28';import { AdaptiveQualityManager } from '../performance/AdaptiveQualityManager.js';
export class InterstellarWarpScene{
 constructor(container){this.container=container;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x000104);this.camera=new THREE.PerspectiveCamera(64,1,.1,260);this.camera.position.set(0,0,0);this.camera.lookAt(0,0,-1);this.renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance',alpha:false,stencil:false});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.68;this.renderer.setClearColor(0x000104,1);this.container.appendChild(this.renderer.domElement);this.composer=new EffectComposer(this.renderer);this.renderPass=new RenderPass(this.scene,this.camera);this.bloomPass=new UnrealBloomPass(new THREE.Vector2(1,1),.18,.25,.70);this.outputPass=new OutputPass();this.composer.addPass(this.renderPass);this.composer.addPass(this.bloomPass);this.composer.addPass(this.outputPass);const mobile=/iPad|iPhone|Android/i.test(navigator.userAgent||'')||innerWidth<800,maxStars=mobile?1200:1400;this.warpField=new WarpFieldManager(maxStars);this.scene.add(this.warpField.group);this.familyLock=new VisualFamilyLock();this.continuityGuard=new ContinuityGuard();this.variationEngine=new WarpVariationEngine();this.director=new WarpContinuityDirector(this.variationEngine,this.familyLock,this.continuityGuard);this.journey=new JourneyNarrativeDirector();this.narrative={stage:'DETACHMENT',heartbeat:0,livingLight:0,galaxyReveal:0,idealized:0,lifeReview:0,boundary:0,returnForce:0,returnFlash:0,finalFade:0,detachment:0,hookPresence:0,turnX:0,turnY:0};this.opticalFlow=new OpticalFlowController();this.quality=new AdaptiveQualityManager(this.renderer,this.composer,maxStars);this.state=this.director.state;this.externalHeartPulse=0;this.heartLightFade=0;this.resize=this.resize.bind(this);addEventListener('resize',this.resize,{passive:true});this.resize();}
 setExternalHeartPulse(pulse,fade){this.externalHeartPulse=Math.max(0,Math.min(1,pulse||0));this.heartLightFade=Math.max(0,Math.min(1,fade||0));}
 resize(){const w=Math.max(1,this.container.clientWidth||innerWidth),h=Math.max(1,this.container.clientHeight||innerHeight);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false);this.composer.setSize(w,h);}
 update(dt,features,musicalState,progress=0){const base=this.director.update(features,musicalState,dt);this.narrative=this.journey.update(dt,features,musicalState,progress);this.state=this.journey.apply(base,this.narrative);this.state.audioHeartPulse=this.externalHeartPulse;this.state.heartLightFade=this.heartLightFade;this.opticalFlow.update(dt,this.state,features);const vp={x:0,y:0,bank:0};this.camera.fov+=(this.state.fov-this.camera.fov)*(1-Math.exp(-1.8*dt));this.camera.position.x+=(0-this.camera.position.x)*(1-Math.exp(-3.0*dt));this.camera.position.y+=(0-this.camera.position.y)*(1-Math.exp(-3.0*dt));this.camera.lookAt(0,0,-1);this.camera.rotation.z+=(0-this.camera.rotation.z)*(1-Math.exp(-3.0*dt));this.camera.updateProjectionMatrix();this.warpField.update(dt,this.state,features,vp);const pulse=this.warpField.starTunnel.pulseLevel||0,heart=this.state.heartPulse||0,living=this.state.livingLight||0,reveal=this.state.galaxyReveal||0,ideal=this.state.idealized||0,wisps=this.warpField.galacticWisps?.maxOpacity||0,sector=this.warpField.deepSpace?.maxPresence||0,flyby=this.warpField.flybys?.activeFlybyCount>0?1:0,external=this.externalHeartPulse*this.heartLightFade,finalFade=this.state.finalFade||0;const baseBloom=.065+this.state.bloom*.18+pulse*.021+heart*.040+living*.038+reveal*.030+wisps*.030+sector*.020+flyby*.012+external*.075;const bloomTarget=Math.min(.30,baseBloom)*(1-finalFade*(1-this.heartLightFade)*.96);this.bloomPass.strength+=(bloomTarget-this.bloomPass.strength)*(1-Math.exp(-2.0*dt));this.bloomPass.radius=.20+this.state.warpIntensity*.035+living*.020+reveal*.010+wisps*.012+sector*.008+external*.028;this.bloomPass.threshold=.71-living*.014-reveal*.010-external*.025;const exposureTarget=(.66+this.state.warpIntensity*.038+heart*.018+living*.035+reveal*.050+ideal*.015+wisps*.020+sector*.035+flyby*.020+external*.052)*(1-finalFade*(1-this.heartLightFade)*.99);this.renderer.toneMappingExposure+=(exposureTarget-this.renderer.toneMappingExposure)*(1-Math.exp(-1.6*dt));const bg=.00040+(1-this.state.darkness)*.0016+reveal*.0018+living*.0005;this.scene.background.setRGB(bg*.10,bg*.22,bg*.54);this.quality.update(dt,this.warpField.starTunnel);}
 render(){this.composer.render();}
 dispose(){removeEventListener('resize',this.resize);this.warpField.dispose();this.composer.dispose();this.renderer.dispose();this.renderer.domElement.remove();}
}
