import * as THREE from 'three';
import { VisualFamilyLock } from '../warp/VisualFamilyLock.js';
import { ContinuityGuard } from '../warp/ContinuityGuard.js';
import { WarpVariationEngine } from '../warp/WarpVariationEngine.js';
import { WarpContinuityDirector } from '../warp/WarpContinuityDirector.js';
import { OpticalFlowController } from '../warp/OpticalFlowController.js?v=20260812-15';
import { JourneyNarrativeDirector } from '../warp/JourneyNarrativeDirector.js?v=20260812-14';
import { WarpFieldManager } from '../warp/WarpFieldManagerV53.js?v=20260814-61';
import { CachedVolumetricNebulaPass } from '../warp/CachedVolumetricNebulaPassV53.js?v=20260813-53';
import { runtimeCapabilities } from '../capabilities/RuntimeCapabilityRegistry.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export class InterstellarWarpScene{
 constructor(container){this.container=container;this.mobile=/iPad|iPhone|iPod|Android/i.test(navigator.userAgent||'')||innerWidth<800;this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(64,1,.1,260);this.camera.position.set(0,0,0);this.renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance',alpha:false,stencil:false,depth:true});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.68;this.renderer.autoClear=false;this.renderer.setClearColor(0x000000,1);container.appendChild(this.renderer.domElement);runtimeCapabilities.attachRenderer(this.renderer);runtimeCapabilities.mark('postprocessing',true,{active:false,reason:'production-layer-scheduler'});runtimeCapabilities.mark('webgpu-compute',false,{reason:'single-renderer-production-path'});this.nebulaPass=new CachedVolumetricNebulaPass();const maxStars=this.mobile?420:900;this.warpField=new WarpFieldManager(maxStars,this.nebulaPass);this.scene.add(this.warpField.group);this.familyLock=new VisualFamilyLock();this.continuityGuard=new ContinuityGuard();this.variationEngine=new WarpVariationEngine();this.director=new WarpContinuityDirector(this.variationEngine,this.familyLock,this.continuityGuard);this.journey=new JourneyNarrativeDirector();this.opticalFlow=new OpticalFlowController();this.state=this.director.state;this.narrative={stage:'DETACHMENT'};this.externalHeartPulse=0;this.heartLightFade=0;this.resize=this.resize.bind(this);addEventListener('resize',this.resize,{passive:true});this.resize();}
 pixelRatio(w,h){const budget=this.mobile?900000:2200000,base=Math.sqrt(budget/Math.max(1,w*h));return clamp(Math.min(devicePixelRatio||1,base),this.mobile?.55:.65,this.mobile?1:1.25);}
 resize(){const w=Math.max(1,this.container.clientWidth||innerWidth),h=Math.max(1,this.container.clientHeight||innerHeight);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setPixelRatio(this.pixelRatio(w,h));this.renderer.setSize(w,h,false);this.nebulaPass.resize(w,h);}
 setExternalHeartPulse(p,f){this.externalHeartPulse=clamp(p||0,0,1);this.heartLightFade=clamp(f||0,0,1);}
 update(dt,features,musicalState,progress=0){const base=this.director.update(features,musicalState,dt);this.narrative=this.journey.update(dt,features,musicalState,progress);this.state=this.journey.apply(base,this.narrative);this.state.audioHeartPulse=this.externalHeartPulse;this.state.heartLightFade=this.heartLightFade;this.opticalFlow.update(dt,this.state,features);this.camera.fov+=(this.state.fov-this.camera.fov)*(1-Math.exp(-1.8*dt));this.camera.position.x+=(0-this.camera.position.x)*(1-Math.exp(-3*dt));this.camera.position.y+=(0-this.camera.position.y)*(1-Math.exp(-3*dt));this.camera.lookAt(0,0,-1);this.camera.rotation.z+=(0-this.camera.rotation.z)*(1-Math.exp(-3*dt));this.camera.updateProjectionMatrix();this.warpField.update(dt,this.state,features);const l=this.state.livingLight||0,g=this.state.galaxyReveal||0,e=this.externalHeartPulse*this.heartLightFade,fade=this.state.finalFade||0,target=(.64+(this.state.warpIntensity||0)*.028+l*.025+g*.038+e*.03)*(1-fade*(1-this.heartLightFade)*.99);this.renderer.toneMappingExposure+=(target-this.renderer.toneMappingExposure)*(1-Math.exp(-1.5*dt));}
 render(){this.nebulaPass.renderCache(this.renderer,this.camera);this.renderer.setRenderTarget(null);this.renderer.setClearColor(0x000000,1);this.renderer.clear(true,true,true);this.nebulaPass.composite(this.renderer);this.renderer.clearDepth();this.renderer.render(this.scene,this.camera);}
 dispose(){removeEventListener('resize',this.resize);this.warpField.dispose();this.nebulaPass.dispose();this.renderer.dispose();this.renderer.domElement.remove();}
 get performanceStats(){return{pixelRatio:this.renderer.getPixelRatio(),drawCalls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles,warp:this.warpField.stats};}
}
