import * as THREE from'three';
import type{AudioFeatures,WarpState}from'../types';
const clamp01=(v:number)=>Math.max(0,Math.min(1,v));
const gaussian=(x:number,c:number,w:number)=>Math.exp(-.5*Math.pow((x-c)/w,2));
type RefSpec={url:string;width:number;center:number;maxOpacity:number;x:number;y:number;z:number;phase:number};
type Layer=RefSpec&{material:THREE.SpriteMaterial;sprite:THREE.Sprite;texture:THREE.Texture|null;aspect:number};
const REFERENCES:RefSpec[]=[
 {url:'./assets/ethereal/angel-01.png',width:25,center:.24,maxOpacity:.50,x:-1.25,y:.20,z:-27,phase:.15},
 {url:'./assets/ethereal/angel-02.png',width:22.5,center:.72,maxOpacity:.46,x:1.05,y:.08,z:-29,phase:3.10}
];
export class EtherealFiguresSystem{
 readonly group=new THREE.Group();private readonly layers:Layer[]=[];private time=0;private readyCount=0;private readonly loader=new THREE.TextureLoader();
 constructor(){for(const ref of REFERENCES){const material=new THREE.SpriteMaterial({color:0xe6f3ff,transparent:true,opacity:0,depthWrite:false,depthTest:false,alphaTest:.008,blending:THREE.AdditiveBlending,toneMapped:false});const sprite=new THREE.Sprite(material);sprite.position.set(ref.x,ref.y,ref.z);sprite.renderOrder=42;this.group.add(sprite);const layer:Layer={...ref,material,sprite,texture:null,aspect:1};this.layers.push(layer);this.loadReference(layer);}this.group.position.set(0,0,0);this.group.visible=false;}
 private loadReference(layer:Layer){this.loader.load(layer.url,texture=>{const image=texture.image as HTMLImageElement|undefined;layer.aspect=image?.width&&image?.height?image.width/image.height:1;texture.colorSpace=THREE.SRGBColorSpace;texture.generateMipmaps=false;texture.minFilter=THREE.LinearFilter;texture.magFilter=THREE.LinearFilter;texture.premultiplyAlpha=true;layer.texture=texture;layer.material.map=texture;layer.material.needsUpdate=true;layer.sprite.scale.set(layer.width,layer.width/layer.aspect,1);this.readyCount++;},undefined,error=>console.warn('URUX supplied transparent PNG could not be loaded',layer.url,error));}
 update(dt:number,state:WarpState,features?:AudioFeatures){this.time+=dt;const stage=state.journeyStage||'',living=clamp01(state.livingLight||0),ideal=clamp01(state.idealized||0),review=clamp01(state.lifeReview||0),boundary=clamp01(state.boundary||0),ret=clamp01(state.returnForce||0),finalFade=clamp01(state.finalFade||0),p=clamp01(state.soulProgress||0);const eligible=stage==='LIVING_LIGHT'||stage==='IDEALIZED_COSMOS'||stage==='LIFE_REVIEW',progressGate=clamp01((p-.46)/.10)*(1-clamp01((p-.94)/.05)),stageFloor=eligible?.28:0,presence=clamp01(Math.max(living*.98,ideal,review*.98,stageFloor))*progressGate*(1-boundary*.88)*(1-ret*.82)*(1-finalFade),sequence=clamp01((p-.46)/.46);this.group.position.set(0,0,0);let total=0;const weights=this.layers.map(l=>{const w=gaussian(sequence,l.center,.38);total+=w;return w}),norm=Math.max(.92,total*.74);for(let i=0;i<this.layers.length;i++){const l=this.layers[i],weight=weights[i]/norm,breathe=1+Math.sin(this.time*.18+i*1.61)*.010,cycle=.5+.5*Math.sin(this.time*.285+l.phase),intermittent=.56+.44*Math.pow(cycle,1.7),audioLift=.96+(features?.mid||0)*.06;l.sprite.position.set(l.x,l.y,l.z);const width=l.width*breathe;l.sprite.scale.set(width,width/l.aspect,1);l.material.opacity=(l.texture?1:0)*presence*(.44+.56*weight)*l.maxOpacity*intermittent*audioLift;}this.group.visible=this.readyCount>0&&presence>.018;}
 dispose(){for(const l of this.layers){l.material.dispose();l.texture?.dispose();}}
}
