declare global { interface Window { Spacekit:any } }
const clamp01=(v:number)=>Math.max(0,Math.min(1,v));
const smooth01=(x:number)=>{const t=clamp01(x);return t*t*(3-2*t);};
const AU_KM=149598000;
const SPACEKIT_BASE='https://typpo.github.io/spacekit/src';
type EventSpec={name:string;start:number;end:number;side:number;y:number;radiusKm:number;visualScale?:number;texture:string;atmosphere:number;tilt:number;rings?:{inner:number;outer:number;texture:string}};
const EVENTS:EventSpec[]=[
 {name:'SpaceKit Jupiter',start:.205,end:.255,side:-1,y:.00042,radiusKm:71492,texture:'https://typpo.github.io/spacekit/examples/jupiter/jupiter2_4k.jpg',atmosphere:0xd6e8ff,tilt:3.13},
 {name:'SpaceKit Saturn',start:.382,end:.438,side:1,y:-.00036,radiusKm:58232.503,texture:'https://typpo.github.io/spacekit/examples/saturn/th_saturn.png',atmosphere:0xe7ddc4,tilt:26.7,rings:{inner:74270.580913,outer:140478.924731,texture:'https://typpo.github.io/spacekit/examples/saturn/saturn_rings_top.png'}},
 {name:'SpaceKit Earth',start:.548,end:.596,side:-1,y:-.00024,radiusKm:6371,visualScale:3.0,texture:'https://typpo.github.io/spacekit/examples/planet/eso_earth.jpg',atmosphere:0x72bfff,tilt:23.4},
 {name:'SpaceKit Jupiter Return',start:.716,end:.764,side:1,y:.00032,radiusKm:71492,texture:'https://typpo.github.io/spacekit/examples/jupiter/jupiter2_4k.jpg',atmosphere:0xd6e8ff,tilt:3.13}
];
type Item={spec:EventSpec;obj:any;root:any};
export class SpaceKitAstronomicalLayer{readonly container:HTMLElement;ready=false;failed=false;sim:any=null;planets:Item[]=[];activePlanetCount=0;closestPlanetZ=-999999;focalOriginError=0;lateralOffset=0;flybyProgress=0;usesLiteralSpaceKit=false;skybox:any;stars:any;constructor(container:HTMLElement){this.container=container;const SK=window.Spacekit;if(!SK||!container){this.failed=true;return;}try{this.sim=new SK.Simulation(container,{basePath:SPACEKIT_BASE,jdPerSecond:0,startPaused:true,unitsPerAu:25000,camera:{initialPosition:[0,0,.000001],enableDrift:false},debug:{showAxes:false,showGrid:false,showStats:false}});this.sim.setCameraDrift(false);const viewer=this.sim.getViewer(),cam=viewer.get3jsCamera(),controls=viewer.get3jsCameraControls();cam.position.set(0,0,0);cam.fov=58;cam.updateProjectionMatrix();controls.target.set(0,0,-1);controls.enablePan=false;controls.enableRotate=false;controls.enableZoom=false;controls.enabled=false;cam.lookAt(0,0,-1);cam.updateMatrixWorld();const renderer=this.sim.getRenderer();renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.65));renderer.setSize(Math.max(1,container.clientWidth||innerWidth),Math.max(1,container.clientHeight||innerHeight));renderer.domElement.style.position='absolute';renderer.domElement.style.inset='0';renderer.domElement.style.width='100%';renderer.domElement.style.height='100%';renderer.domElement.style.pointerEvents='none';this.skybox=this.sim.createSkybox(SK.SkyboxPresets.ESO_GIGAGALAXY);this.stars=this.sim.createStars({minSize:.55});this.sim.createLight([-.018,-.010,.014],0xffffff);EVENTS.forEach((s,i)=>this.createPlanet(s,i));this.usesLiteralSpaceKit=true;this.ready=true;}catch{this.failed=true;}}
private createPlanet(spec:EventSpec,index:number){const radius=(spec.radiusKm/AU_KM)*(spec.visualScale||1),obj=this.sim.createSphere(`urux-spacekit-${index}`,{textureUrl:spec.texture,radius,axialTilt:spec.tilt,levelsOfDetail:[{radii:0,segments:96},{radii:40,segments:64},{radii:95,segments:32}],atmosphere:{enable:true,color:spec.atmosphere,innerSizeRatio:.018,outerSizeRatio:.11}});if(spec.rings)obj.addRings(spec.rings.inner,spec.rings.outer,spec.rings.texture,192);const root=obj.get3jsObjects()[0];root.visible=false;this.planets.push({spec,obj,root});}
update(progress:number,dt:number){if(!this.ready||!this.sim)return;const p=clamp01(progress||0);this.activePlanetCount=0;this.closestPlanetZ=-999999;this.focalOriginError=0;this.lateralOffset=0;this.flybyProgress=0;for(const item of this.planets){const s=item.spec,raw=(p-s.start)/(s.end-s.start);if(raw<=0||raw>=1){item.root.visible=false;continue;}const t=clamp01(raw),approach=Math.pow(smooth01(t),2.05),late=smooth01((t-.56)/.40),pass=Math.pow(late,1.75),z=-.068+approach*.06755,x=s.side*.00275*pass,y=s.y*pass;item.obj.setPosition(x,y,z);item.obj.update(this.sim.getJd(),true);item.root.visible=true;item.root.rotation.z+=dt*.045*s.side;this.activePlanetCount++;const zScene=z*25000,lateral=Math.hypot(x,y)*25000;this.closestPlanetZ=Math.max(this.closestPlanetZ,zScene);this.lateralOffset=Math.max(this.lateralOffset,lateral);this.flybyProgress=Math.max(this.flybyProgress,t);if(t<.42)this.focalOriginError=Math.max(this.focalOriginError,lateral);}}
resize(){if(!this.ready||!this.sim)return;const renderer=this.sim.getRenderer(),camera=this.sim.getViewer().get3jsCamera(),w=Math.max(1,this.container.clientWidth||innerWidth),h=Math.max(1,this.container.clientHeight||innerHeight);renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}}
export {};
