import{test,expect}from'@playwright/test';

test('v65 balances traversable colored gas, shuffles planetary families and performs a physical comet camera crossing',async({page},testInfo)=>{
 test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.locator('#enterBtn')).toBeVisible();await page.waitForFunction(()=>Boolean((window as any).__URUX_BOOT__?.interactionReady),undefined,{timeout:30000});await expect(page.locator('#enterBtn')).toBeEnabled();await page.locator('#enterBtn').click();await page.waitForFunction(()=>Boolean((window as any).__MUSIC_PULSE_QA__?.started)&&Boolean((window as any).__MUSIC_PULSE_QA__?.runtimeReady),undefined,{timeout:55000});
 await page.waitForFunction(()=>{const q=(window as any).__MUSIC_PULSE_QA__,c=q?.performanceStats?.scene?.warp?.clouds;return Boolean(c&&c.cameraCrossings>0&&c.peakOpacity>.38&&c.coloredGas===true&&c.densityNoise==='layered-fbm-cellular'&&c.perceptualRevision==='v65-dense-colored-gas'&&c.luminanceCapped===true&&q.nebulaVisibility>.24);},undefined,{timeout:50000});
 try{await page.waitForFunction(()=>{const c=(window as any).__MUSIC_PULSE_QA__?.cinematicEncounterStats||{};return Boolean(c.cometRoute?.guaranteedActualCameraCrossing===true&&c.cometRoute?.actualCameraCrossings>0);},undefined,{timeout:35000});}catch(error){const diag=await page.evaluate(()=>{const q=(window as any).__MUSIC_PULSE_QA__;return{runtimePhase:q?.runtimePhase,audioStage:q?.audioStage,cinematic:q?.cinematicEncounterStats,performance:q?.performanceStats};});console.log('V65_PHYSICAL_CROSSING_DIAGNOSTICS',JSON.stringify(diag));throw error;}
 const runtime=await page.evaluate(()=>{const q=(window as any).__MUSIC_PULSE_QA__,clouds=q.performanceStats?.scene?.warp?.clouds||{},cinematic=q.cinematicEncounterStats||{};return{clouds,cinematic,nebulaVisibility:q.nebulaVisibility,nebulaRaySteps:q.nebulaRaySteps,nebulaLightSteps:q.nebulaLightSteps};});
 expect(runtime.clouds.mode).toBe('continuous-volumetric-traversal');expect(runtime.clouds.perceptualRevision).toBe('v65-dense-colored-gas');expect(runtime.clouds.coloredGas).toBe(true);expect(runtime.clouds.densityGain).toBeGreaterThan(1);expect(runtime.clouds.sizeGain).toBeGreaterThan(1);expect(runtime.clouds.chromaGain).toBeGreaterThan(1);expect(runtime.clouds.nearAlphaLift).toBe(true);expect(runtime.clouds.luminanceCapped).toBe(true);expect(runtime.clouds.peakOpacity).toBeGreaterThan(.38);expect(runtime.nebulaVisibility).toBeGreaterThan(.24);expect(runtime.nebulaRaySteps).toBeGreaterThanOrEqual(7);expect(runtime.nebulaLightSteps).toBeGreaterThanOrEqual(1);
 const pv=runtime.cinematic.planetVariants||{},cr=runtime.cinematic.cometRoute||{};expect(pv.families?.length).toBeGreaterThanOrEqual(6);expect(pv.selectionMode).toBe('seeded-shuffle-bag-v65');expect(pv.noImmediateRepeat).toBe(true);expect(pv.instanceColorJitter).toBe(true);expect(pv.orderPreview?.length).toBe(6);expect(new Set(pv.orderPreview).size).toBe(6);expect(cr.guaranteedProcedural).toBe(true);expect(cr.longIonTail).toBe(true);expect(cr.longDustTail).toBe(true);expect(cr.routeModes?.length).toBeGreaterThanOrEqual(5);expect(cr.kinematics).toBe('route-specific-parametric-v65');expect(cr.wallClockKinematics).toBe(true);expect(cr.guaranteedCloseRoute).toBe(true);expect(cr.guaranteedRouteMode).toBe('diagonal-cross');expect(cr.guaranteeSpawned).toBe(true);expect(cr.guaranteedActualCameraCrossing).toBe(true);expect(cr.actualCameraCrossings).toBeGreaterThan(0);expect(cr.actualCrossingPose).not.toBeNull();expect(cr.closestScreenApproach).not.toBeNull();
 const v65=await(await page.request.get('/runtime/journey/CinematicEncounterSystemV65.js')).text();expect(v65).toContain('seeded-shuffle-bag-v65');expect(v65).toContain('wallClockKinematics=true');expect(v65).toContain('guaranteedActualCameraCrossing');expect(v65).toContain('performance.now()');const route=await(await page.request.get('/runtime/journey/CinematicEncounterSystemV59Route.js')).text();expect(route).toContain('procedural-guaranteed');expect(route).toContain('guaranteeSpawned');const clouds=await(await page.request.get('/runtime/warp/CloudNebulaVolumeV65.js')).text();expect(clouds).toContain('luminanceCapped:true');const raymarch=await(await page.request.get('/runtime/warp/VolumetricNebulaRaymarcherV65.js')).text();expect(raymarch).toContain('luminanceCapped=true');
 await page.screenshot({path:testInfo.outputPath('v65-balanced-nebula-physical-comet-crossing.png'),animations:'disabled'});expect(errors.filter(e=>!e.includes('Failed to fetch'))).toEqual([]);
});
