import{test,expect}from'@playwright/test';

test('v61 traverses colored gas through camera, varies planets and guarantees a real comet',async({page},testInfo)=>{
 test.setTimeout(135000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.locator('#enterBtn')).toBeVisible();await page.waitForFunction(()=>Boolean((window as any).__URUX_BOOT__?.interactionReady),undefined,{timeout:30000});await expect(page.locator('#enterBtn')).toBeEnabled();await page.locator('#enterBtn').click();await page.waitForFunction(()=>Boolean((window as any).__MUSIC_PULSE_QA__?.started)&&Boolean((window as any).__MUSIC_PULSE_QA__?.runtimeReady),undefined,{timeout:45000});
 await page.waitForFunction(()=>{const c=(window as any).__MUSIC_PULSE_QA__?.performanceStats?.scene?.warp?.clouds;return Boolean(c&&c.cameraCrossings>0&&c.peakOpacity>.20&&c.coloredGas===true&&c.rectangularBillboards===false);},undefined,{timeout:35000});
 await page.waitForFunction(()=>{const c=(window as any).__MUSIC_PULSE_QA__?.cinematicEncounterStats||{};return Boolean(c.cometRoute?.passes>0);},undefined,{timeout:15000});
 const runtime=await page.evaluate(()=>{const q=(window as any).__MUSIC_PULSE_QA__,clouds=q.performanceStats?.scene?.warp?.clouds||{},cinematic=q.cinematicEncounterStats||{};return{clouds,cinematic};});
 expect(runtime.clouds.mode).toBe('continuous-volumetric-traversal');expect(runtime.clouds.volumeType).toBe('3d-point-gas-v59');expect(runtime.clouds.coloredGas).toBe(true);expect(runtime.clouds.rectangularBillboards).toBe(false);expect(runtime.clouds.supportGeometry).toBe('THREE.Points');expect(runtime.clouds.volumes).toBeGreaterThanOrEqual(4);expect(runtime.clouds.particles).toBeGreaterThanOrEqual(1600);expect(runtime.clouds.emissiveVolumes).toBeGreaterThan(0);expect(runtime.clouds.cameraCrossings).toBeGreaterThan(0);expect(runtime.clouds.peakOpacity).toBeGreaterThan(.20);
 expect(runtime.cinematic.planetVariants?.families?.length).toBeGreaterThanOrEqual(6);expect(runtime.cinematic.cometRoute?.guaranteedProcedural).toBe(true);expect(runtime.cinematic.cometRoute?.longIonTail).toBe(true);expect(runtime.cinematic.cometRoute?.longDustTail).toBe(true);expect(runtime.cinematic.cometRoute?.passes).toBeGreaterThan(0);
 const route=await(await page.request.get('/runtime/journey/CinematicEncounterSystemV59Route.js')).text();expect(route).toContain('scheduleGuaranteedComet');expect(route).toContain('timerGuaranteed=true');
 const comet=await(await page.request.get('/runtime/journey/CinematicEncounterSystemV59.js')).text();expect(comet).toContain('PLANET_VARIANTS');expect(comet).toContain('buildTailGeometry');expect(comet).toContain('spawnProcedural');
 const clouds=await(await page.request.get('/runtime/warp/CloudNebulaVolumeV59.js')).text();expect(clouds).toContain('cameraCrossings');expect(clouds).toContain('THREE.Points');expect(clouds).toContain('ShaderMaterial');expect(clouds).toContain('coloredGas:true');expect(clouds).not.toContain('THREE.Sprite');expect(clouds).not.toContain('SpriteMaterial');
 await page.screenshot({path:testInfo.outputPath('v61-colored-gas-camera-crossing-real-comet.png'),animations:'disabled'});expect(errors.filter(e=>!e.includes('Failed to fetch')).toEqual([]);
});
