import{test,expect}from'@playwright/test';

test('v62 traverses dense colored gas, exposes six planetary surface families and guarantees varied comet crossings',async({page},testInfo)=>{
 test.setTimeout(135000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.locator('#enterBtn')).toBeVisible();await page.waitForFunction(()=>Boolean((window as any).__URUX_BOOT__?.interactionReady),undefined,{timeout:30000});await expect(page.locator('#enterBtn')).toBeEnabled();await page.locator('#enterBtn').click();await page.waitForFunction(()=>Boolean((window as any).__MUSIC_PULSE_QA__?.started)&&Boolean((window as any).__MUSIC_PULSE_QA__?.runtimeReady),undefined,{timeout:45000});
 await page.waitForFunction(()=>{const q=(window as any).__MUSIC_PULSE_QA__,c=q?.performanceStats?.scene?.warp?.clouds;return Boolean(c&&c.cameraCrossings>0&&c.peakOpacity>.30&&c.coloredGas===true&&c.densityNoise==='layered-fbm-cellular'&&q.nebulaVisibility>.18);},undefined,{timeout:35000});
 await page.waitForFunction(()=>{const c=(window as any).__MUSIC_PULSE_QA__?.cinematicEncounterStats||{};return Boolean(c.cometRoute?.passes>0);},undefined,{timeout:15000});
 const runtime=await page.evaluate(()=>{const q=(window as any).__MUSIC_PULSE_QA__,clouds=q.performanceStats?.scene?.warp?.clouds||{},cinematic=q.cinematicEncounterStats||{};return{clouds,cinematic,nebulaVisibility:q.nebulaVisibility,nebulaRaySteps:q.nebulaRaySteps,nebulaLightSteps:q.nebulaLightSteps};});
 expect(runtime.clouds.mode).toBe('continuous-volumetric-traversal');expect(runtime.clouds.volumeType).toBe('3d-point-gas-v59');expect(runtime.clouds.visualRevision).toBe('v62-fbm-hybrid');expect(runtime.clouds.coloredGas).toBe(true);expect(runtime.clouds.rectangularBillboards).toBe(false);expect(runtime.clouds.supportGeometry).toBe('THREE.Points');expect(runtime.clouds.hybridRaymarchSupport).toBe(true);expect(runtime.clouds.cameraTraversal).toBe(true);expect(runtime.clouds.filaments).toBe(true);expect(runtime.clouds.holes).toBe(true);expect(runtime.clouds.colorFamilies).toBeGreaterThanOrEqual(8);expect(runtime.clouds.volumes).toBeGreaterThanOrEqual(5);expect(runtime.clouds.particles).toBeGreaterThanOrEqual(2200);expect(runtime.clouds.emissiveVolumes).toBeGreaterThan(0);expect(runtime.clouds.cameraCrossings).toBeGreaterThan(0);expect(runtime.clouds.peakOpacity).toBeGreaterThan(.30);expect(runtime.nebulaVisibility).toBeGreaterThan(.18);expect(runtime.nebulaRaySteps).toBeGreaterThanOrEqual(7);expect(runtime.nebulaLightSteps).toBeGreaterThanOrEqual(1);
 expect(runtime.cinematic.planetVariants?.families?.length).toBeGreaterThanOrEqual(6);expect(runtime.cinematic.planetVariants?.surfaceSignatures).toBe(true);expect(runtime.cinematic.planetVariants?.bands).toBe(true);expect(runtime.cinematic.planetVariants?.clouds).toBe(true);expect(runtime.cinematic.planetVariants?.conditionalEmission).toBe(true);expect(runtime.cinematic.cometRoute?.guaranteedProcedural).toBe(true);expect(runtime.cinematic.cometRoute?.longIonTail).toBe(true);expect(runtime.cinematic.cometRoute?.longDustTail).toBe(true);expect(runtime.cinematic.cometRoute?.crossingPaths).toBe(true);expect(runtime.cinematic.cometRoute?.fragmentSwarm).toBe(true);expect(runtime.cinematic.cometRoute?.routeModes?.length).toBeGreaterThanOrEqual(5);expect(runtime.cinematic.cometRoute?.passes).toBeGreaterThan(0);
 const route=await(await page.request.get('/runtime/journey/CinematicEncounterSystemV59Route.js')).text();expect(route).toContain('scheduleGuaranteedComet');expect(route).toContain('timerGuaranteed=true');
 const comet=await(await page.request.get('/runtime/journey/CinematicEncounterSystemV59.js')).text();expect(comet).toContain('amber-gas-giant');expect(comet).toContain('volcanic-world');expect(comet).toContain('violet-green-exotic');expect(comet).toContain('surfaceMaterial');expect(comet).toContain('cloudMaterial');expect(comet).toContain('COMET_ROUTE_MODES');expect(comet).toContain('fragment-swarm');expect(comet).toContain('attachFragmentSwarm');expect(comet).toContain('buildTailGeometry');
 const clouds=await(await page.request.get('/runtime/warp/CloudNebulaVolumeV59.js')).text();expect(clouds).toContain('cameraCrossings');expect(clouds).toContain('THREE.Points');expect(clouds).toContain('ShaderMaterial');expect(clouds).toContain('layered-fbm-cellular');expect(clouds).toContain('coloredGas:true');expect(clouds).not.toContain('THREE.Sprite');expect(clouds).not.toContain('SpriteMaterial');
 const raymarch=await(await page.request.get('/runtime/warp/VolumetricNebulaRaymarcherV53.js')).text();expect(raymarch).toContain("this.mobile?10:14");expect(raymarch).toContain("'#ef7658'");expect(raymarch).toContain('uNarrativeFilaments.value=.78');
 await page.screenshot({path:testInfo.outputPath('v62-planet-families-dense-nebula-comet-crossings.png'),animations:'disabled'});expect(errors.filter(e=>!e.includes('Failed to fetch'))).toEqual([]);
});
