import{test,expect}from'@playwright/test';
type Snapshot={family:string;speed:number;stage:string;heartbeat:number;livingLight:number;galaxyReveal:number;nebulaVisibility:number;deepSpacePresence:number;activeSpaceSectorCount:number;activeFlybyCount:number;closestFlybyZ:number;galacticWispOpacity:number;etherealOpacity:number;boundary:number;returnForce:number;finalFade:number;audioStage:string;sleepBedActive:boolean;started:boolean;duration:number};
async function snap(page:any):Promise<Snapshot>{return page.evaluate(()=>{const q=(window as any).__MUSIC_PULSE_QA__,s=q.warpState;return{family:q.family,speed:s.speed,stage:q.journeyStage,heartbeat:q.heartbeat,livingLight:q.livingLight,galaxyReveal:q.galaxyReveal,nebulaVisibility:q.nebulaVisibility||0,deepSpacePresence:q.deepSpacePresence||0,activeSpaceSectorCount:q.activeSpaceSectorCount||0,activeFlybyCount:q.activeFlybyCount||0,closestFlybyZ:q.closestFlybyZ??-999,galacticWispOpacity:q.galacticWispOpacity||0,etherealOpacity:q.etherealOpacity||0,boundary:q.boundary,returnForce:q.returnForce,finalFade:s.finalFade||0,audioStage:q.audioStage,sleepBedActive:q.sleepBedActive,started:q.started,duration:q.duration};});}
async function seekFraction(page:any,fraction:number,settle=650){const duration=await page.evaluate(()=>((window as any).__MUSIC_PULSE_QA__?.duration||0));await page.evaluate(({duration,fraction})=>(window as any).__MUSIC_PULSE_QA__.seek(duration*fraction),{duration,fraction});await page.waitForTimeout(settle);return snap(page);}
test('URUX traverses distinct astronomical sectors with Celestia, TrueColorTools and webgpu-galaxy code paths',async({page},testInfo)=>{test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('#enterBtn')).toBeVisible();await page.locator('#enterBtn').click();await page.waitForFunction(()=>Boolean((window as any).__MUSIC_PULSE_QA__?.started)&&((window as any).__MUSIC_PULSE_QA__?.duration||0)>0,undefined,{timeout:15000});
for(const path of['/assets/ethereal/angel-01.png','/assets/ethereal/angel-02.png','/assets/truecolor/CIE_1931_2deg.x.txt','/assets/truecolor/CIE_1931_2deg.y.txt','/assets/truecolor/CIE_1931_2deg.z.txt','/assets/truecolor/Jupiter_Li2018_visible.txt','/assets/truecolor/Mars_McCord1971_visible.txt']){const r=await page.request.get(path);expect(r.ok(),path).toBeTruthy();expect((await r.body()).length,path).toBeGreaterThan(100);}
const angel=await(await page.request.get('/runtime/warp/EtherealFiguresSystem.js')).text();expect(angel).toContain('angel-01.png');expect(angel).toContain('angel-02.png');expect(angel).not.toContain('reference-01.b64');expect(angel).not.toContain('data:image/jpeg');
const celestia=await(await page.request.get('/runtime/thirdparty/CelestiaPhotometry.js')).text();expect(celestia).toContain('magToIrradiance');expect(celestia).toContain('celestiaDimGateSoftClip');expect(celestia).toContain('celestiaGlowSoftClip');expect(celestia).toContain('ENHANCED_STAR_COLORS');
const trueColor=await(await page.request.get('/runtime/thirdparty/TrueColorToolsColor.js')).text();expect(trueColor).toContain('MATRIX_B');expect(trueColor).toContain('ColorSystem');expect(trueColor).toContain('loadCIE1931CMF');expect(trueColor).toContain('spectrumToXYZ');
const galaxyModel=await(await page.request.get('/runtime/thirdparty/WebGPUGalaxyModel.js')).text();expect(galaxyModel).toContain('webgpuGalaxyHash');expect(galaxyModel).toContain('spiralAngle');expect(galaxyModel).toContain('applyDifferentialRotation');
const sectors=await(await page.request.get('/runtime/warp/DeepSpaceSectorSystem.js')).text();expect(sectors).toContain('generateSpiralPosition');expect(sectors).toContain('generateCloudPosition');expect(sectors).toContain('normalizedStellarRadiance');
const flybys=await(await page.request.get('/runtime/warp/CelestialFlybySystem.js')).text();expect(flybys).toContain('spectrumToSRGB');expect(flybys).toContain('reflectedLuminosity');expect(flybys).toContain('Jupiter spectral fly-by');expect(flybys).toContain('Mars spectral fly-by');
const early=await seekFraction(page,.05);expect(early.family).toBe('INTERSTELLAR_WARP');expect(early.stage).toBe('DETACHMENT');expect(early.sleepBedActive).toBeTruthy();expect(early.nebulaVisibility).toBeLessThan(.45);
const firstSystem=await seekFraction(page,.18,900);expect(firstSystem.activeSpaceSectorCount).toBeGreaterThanOrEqual(1);expect(firstSystem.deepSpacePresence).toBeGreaterThan(.20);expect(firstSystem.activeFlybyCount).toBeGreaterThanOrEqual(1);expect(firstSystem.closestFlybyZ).toBeGreaterThan(-180);expect(firstSystem.nebulaVisibility).toBeLessThan(.45);await page.screenshot({path:testInfo.outputPath('journey-first-system-flyby.png'),animations:'disabled'});
const tunnelSector=await seekFraction(page,.30,800);expect(['DARK_TUNNEL','DETACHMENT','LIVING_LIGHT']).toContain(tunnelSector.stage);expect(tunnelSector.speed).toBeGreaterThan(1);expect(tunnelSector.activeSpaceSectorCount).toBeGreaterThanOrEqual(1);expect(tunnelSector.deepSpacePresence).toBeGreaterThan(.30);expect(tunnelSector.nebulaVisibility).toBeLessThan(.45);
const marsPass=await seekFraction(page,.37,900);expect(marsPass.activeFlybyCount).toBeGreaterThanOrEqual(1);expect(marsPass.closestFlybyZ).toBeGreaterThan(-180);await page.screenshot({path:testInfo.outputPath('journey-mars-spectral-flyby.png'),animations:'disabled'});
const deepCruise=await seekFraction(page,.67,900);expect(deepCruise.activeSpaceSectorCount).toBeGreaterThanOrEqual(1);expect(deepCruise.deepSpacePresence).toBeGreaterThan(.30);expect(deepCruise.nebulaVisibility).toBeLessThan(.45);expect(deepCruise.audioStage).not.toBe('FETAL');
const cosmos=await seekFraction(page,.78,1100);expect(['IDEALIZED_COSMOS','LIFE_REVIEW','LIVING_LIGHT']).toContain(cosmos.stage);expect(cosmos.galaxyReveal).toBeGreaterThan(.08);expect(cosmos.activeSpaceSectorCount).toBeGreaterThanOrEqual(1);expect(cosmos.deepSpacePresence).toBeGreaterThan(.20);expect(cosmos.activeFlybyCount).toBeGreaterThanOrEqual(1);expect(cosmos.nebulaVisibility).toBeLessThan(.45);expect(cosmos.etherealOpacity).toBeGreaterThan(.08);await page.screenshot({path:testInfo.outputPath('journey-cosmos-sector-planets-angels.png'),animations:'disabled'});
const boundary=await seekFraction(page,.91,1500);expect(['BOUNDARY','RETURN']).toContain(boundary.stage);expect(boundary.boundary).toBeGreaterThan(.003);const returning=await seekFraction(page,.975,900);expect(returning.stage).toBe('RETURN');expect(returning.returnForce).toBeGreaterThan(.04);await seekFraction(page,.995,1200);await page.waitForFunction(()=>((window as any).__MUSIC_PULSE_QA__?.finalFade||0)>.018,undefined,{timeout:12000});const ending=await snap(page);expect(ending.stage).toBe('RETURN');expect(ending.finalFade).toBeGreaterThan(.018);expect(errors).toEqual([]);});
