import{test,expect}from'@playwright/test';
type Snapshot={family:string;speed:number;streakLength:number;fov:number;stage:string;heartbeat:number;galaxyReveal:number;boundary:number;returnForce:number;finalFade:number;started:boolean;audioTime:number;duration:number};
async function snap(page:any):Promise<Snapshot>{return page.evaluate(()=>{const qa=(window as any).__MUSIC_PULSE_QA__,s=qa.warpState;return{family:qa.family,speed:s.speed,streakLength:s.streakLength,fov:s.fov,stage:qa.journeyStage,heartbeat:qa.heartbeat,galaxyReveal:qa.galaxyReveal,boundary:qa.boundary,returnForce:qa.returnForce,finalFade:s.finalFade||0,started:qa.started,audioTime:qa.audioTime,duration:qa.duration};});}
async function seekFraction(page:any,fraction:number){const duration=await page.evaluate(()=>((window as any).__MUSIC_PULSE_QA__?.duration||0));await page.evaluate(({duration,fraction})=>(window as any).__MUSIC_PULSE_QA__.seek(duration*fraction),{duration,fraction});await page.waitForTimeout(450);return snap(page);}
test('URUX follows heartbeat, light, galaxy, boundary and return chronology',async({page},testInfo)=>{test.setTimeout(75000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('#enterBtn')).toBeVisible();await page.locator('#enterBtn').click();await page.waitForFunction(()=>Boolean((window as any).__MUSIC_PULSE_QA__?.started)&&((window as any).__MUSIC_PULSE_QA__?.duration||0)>0,undefined,{timeout:15000});
for(const path of['/assets/ethereal/reference-01.b64','/assets/ethereal/reference-02.b64','/assets/ethereal/reference-03.b64','/assets/ethereal/reference-04.b64']){const response=await page.request.get(path);expect(response.ok()).toBeTruthy();expect((await response.text()).length).toBeGreaterThan(5000);}
const early=await seekFraction(page,.05);expect(early.family).toBe('INTERSTELLAR_WARP');expect(early.stage).toBe('DETACHMENT');let maxHeart=0;for(let i=0;i<12;i++){await page.waitForTimeout(90);maxHeart=Math.max(maxHeart,await page.evaluate(()=>((window as any).__MUSIC_PULSE_QA__?.heartbeat||0)));}expect(maxHeart).toBeGreaterThan(.08);await page.screenshot({path:testInfo.outputPath('journey-01-detachment.png'),animations:'disabled'});
const tunnel=await seekFraction(page,.25);expect(['DARK_TUNNEL','DETACHMENT']).toContain(tunnel.stage);expect(tunnel.speed).toBeGreaterThan(1);await page.screenshot({path:testInfo.outputPath('journey-02-tunnel.png'),animations:'disabled'});
await seekFraction(page,.60);await page.waitForFunction(()=>((window as any).__MUSIC_PULSE_QA__?.galaxyReveal||0)>.01,undefined,{timeout:6500});const light=await snap(page);expect(['LIVING_LIGHT','IDEALIZED_COSMOS']).toContain(light.stage);expect(light.heartbeat).toBeLessThan(.03);expect(light.galaxyReveal).toBeGreaterThan(.01);await page.screenshot({path:testInfo.outputPath('journey-03-light.png'),animations:'disabled'});
const review=await seekFraction(page,.76);expect(['IDEALIZED_COSMOS','LIFE_REVIEW']).toContain(review.stage);expect(review.galaxyReveal).toBeGreaterThan(.25);expect(review.speed).toBeLessThan(tunnel.speed);await page.screenshot({path:testInfo.outputPath('journey-04-life-review.png'),animations:'disabled'});
const boundary=await seekFraction(page,.89);expect(['BOUNDARY','RETURN']).toContain(boundary.stage);expect(Math.max(boundary.boundary,boundary.returnForce)).toBeGreaterThan(.05);await page.screenshot({path:testInfo.outputPath('journey-05-boundary.png'),animations:'disabled'});
const returning=await seekFraction(page,.965);expect(returning.stage).toBe('RETURN');expect(returning.returnForce).toBeGreaterThan(.05);expect(returning.speed).toBeLessThan(review.speed);await page.screenshot({path:testInfo.outputPath('journey-06-return.png'),animations:'disabled'});
const ending=await seekFraction(page,.992);expect(ending.stage).toBe('RETURN');expect(ending.finalFade).toBeGreaterThan(.35);await page.screenshot({path:testInfo.outputPath('journey-07-ending.png'),animations:'disabled'});expect(errors).toEqual([]);});
