import * as THREE from 'three';
import { runtimeCapabilities } from '../capabilities/RuntimeCapabilityRegistry.js';
export class ThreeNebulaParticleFX{
 constructor(scene){this.scene=scene;this.system=null;this.api=null;this.emitters=new Map();this.ready=false;this.failed=false;this.loading=null;this.mobile=/iPad|iPhone|iPod|Android/i.test(navigator.userAgent||'')||innerWidth<800;this.stats={ready:false,emitters:0,count:0,engine:'three-nebula',eventDriven:true,mobile:this.mobile,lastEffect:null};}
 async init(){if(this.ready)return true;if(this.failed)return false;if(this.loading)return this.loading;this.loading=(async()=>{try{const mod=await import('three-nebula');this.api=mod;const System=mod.default||mod.System;this.system=new System();this.system.addRenderer(new mod.SpriteRenderer(this.scene,THREE));this.ready=true;this.stats.ready=true;runtimeCapabilities.mark('three-nebula',true,{version:'12.1.0',renderer:'SpriteRenderer',mode:'event-driven',mobile:this.mobile});return true;}catch(error){this.failed=true;runtimeCapabilities.mark('three-nebula',false,{version:'12.1.0',error:String(error)});return false;}})();return this.loading;}
 makeEmitter(id,position,velocity,palette,kind='plasma'){if(!this.ready||this.emitters.has(id)||this.emitters.size>=3)return null;const N=this.api,dir=velocity.clone().multiplyScalar(-1),gain=kind==='plasma'?8:(kind==='fragment'?3.8:5.5),v=new N.Vector3D(dir.x*gain,dir.y*gain,dir.z*gain),emitter=new N.Emitter(),count=this.mobile?(kind==='fragment'?new N.Span(1,1):new N.Span(1,2)):(kind==='fragment'?new N.Span(1,2):new N.Span(2,4)),period=this.mobile?new N.Span(.10,.18):new N.Span(.07,.12);emitter.setPosition(position).setRate(new N.Rate(count,period)).setInitializers([new N.Position(new N.PointZone(0,0,0)),new N.Mass(1),new N.Radius(kind==='fragment'?.035:.05,kind==='fragment'?.09:.13),new N.Life(kind==='plasma'?.65:1.0,kind==='plasma'?1.25:2.0),new N.VectorVelocity(v,kind==='fragment'?18:9)]).setBehaviours([new N.Alpha(kind==='plasma'?.62:.38,0),new N.Scale(1,.12),new N.Color(new THREE.Color(palette?.[1]||'#9ab8ff'),new THREE.Color(palette?.[2]||'#fff1d6'))]).emit();this.system.addEmitter(emitter);this.emitters.set(id,{emitter,kind});this.stats.emitters=this.emitters.size;this.stats.lastEffect=kind;return emitter;}
 attachEncounter(id,root,type,velocity,palette){if(!this.ready||!root)return;if(type==='comet'){const p=root.getWorldPosition(new THREE.Vector3());this.makeEmitter(`${id}:plasma`,p,velocity,palette,'plasma');if(!this.mobile)this.makeEmitter(`${id}:dust`,p,velocity,palette,'dust');}else if(type==='debris'){this.makeEmitter(`${id}:fragment`,root.getWorldPosition(new THREE.Vector3()),velocity,palette,'fragment');}}
 syncEncounter(id,root){if(!this.ready||!root)return;const p=root.getWorldPosition(new THREE.Vector3());for(const [key,item] of this.emitters)if(key.startsWith(`${id}:`))item.emitter.setPosition(p);}
 detachEncounter(id){for(const [key,item] of [...this.emitters])if(key.startsWith(`${id}:`)){item.emitter.stopEmit();this.emitters.delete(key);}this.stats.emitters=this.emitters.size;}
 update(dt){if(!this.ready||!this.emitters.size)return;this.system?.update?.(Math.min(.05,Math.max(.001,dt||1/60)));this.stats.count=this.system?.getCount?.()||0;}
 dispose(){for(const item of this.emitters.values())item.emitter.stopEmit();this.emitters.clear();this.system?.destroy?.();}
}
