const VERSION='1.0.0';
const ALLOWED_STAGES={
 DESPRENDIMIENTO:{paletteHint:['#02030a','#07152d','#17265e'],encounterTypes:['debris','void_pulse','light_filament']},
 TUNEL:{paletteHint:['#02020a','#0d1b4b','#4b0082'],encounterTypes:['debris','comet','light_filament','void_pulse']},
 LUZ:{paletteHint:['#13051e','#6a0572','#d946a8','#ffffff'],encounterTypes:['light_filament','planet','comet']},
 MEMORIA:{paletteHint:['#08061c','#37206f','#a23885','#ffb25c'],encounterTypes:['planet','vessel','light_filament','debris']},
 FRONTERA:{paletteHint:['#02030b','#18244b','#6d3b7e','#ffd08a'],encounterTypes:['void_pulse','vessel','light_filament']},
 RETORNO:{paletteHint:['#050916','#183d6d','#8c5f9e','#fff4d6'],encounterTypes:['comet','debris','light_filament','planet']}
};
const OBJECT_TYPES=['planet','comet','debris','light_filament','vessel','void_pulse'];
const SCHEMA={name:'urux_encounter_batch',strict:true,schema:{type:'object',additionalProperties:false,required:['encounters','nebulaUpdate'],properties:{encounters:{type:'array',minItems:3,maxItems:6,items:{type:'object',additionalProperties:false,required:['id','narrativeStage','objectType','spawnDepth','spawnPosition','focalApproach','trajectoryVector','scale','speed','palette','luminosity','durationSeconds'],properties:{id:{type:'string'},narrativeStage:{type:'string',enum:Object.keys(ALLOWED_STAGES)},objectType:{type:'string',enum:OBJECT_TYPES},spawnDepth:{type:'number'},spawnPosition:{type:'object',additionalProperties:false,required:['x','y'],properties:{x:{type:'number'},y:{type:'number'}}},focalApproach:{type:'boolean'},trajectoryVector:{type:'object',additionalProperties:false,required:['x','y','z'],properties:{x:{type:'number'},y:{type:'number'},z:{type:'number'}}},scale:{type:'number'},speed:{type:'number'},palette:{type:'array',minItems:1,maxItems:6,items:{type:'string'}},luminosity:{type:'number'},durationSeconds:{type:'number'}}}},nebulaUpdate:{type:'object',additionalProperties:false,required:['darkZoneFraction','filamentDensity','luminousCore','chromaticRange'],properties:{darkZoneFraction:{type:'number',minimum:.3,maximum:1},filamentDensity:{type:'number',minimum:0,maximum:1},luminousCore:{type:'object',additionalProperties:false,required:['x','y'],properties:{x:{type:'number'},y:{type:'number'}}},chromaticRange:{type:'array',minItems:1,maxItems:8,items:{type:'string'}}}}}}};
const finite=v=>typeof v==='number'&&Number.isFinite(v),hex=v=>typeof v==='string'&&/^#[0-9a-fA-F]{6}$/.test(v);
function cors(origin,env){const allowed=(env.ALLOWED_ORIGIN||'https://pychile.github.io').split(',').map(x=>x.trim());const ok=allowed.includes(origin);return ok?{'Access-Control-Allow-Origin':origin,'Vary':'Origin','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Max-Age':'86400'}:{};}
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});}
async function eligibleModels(){const r=await fetch('https://openrouter.ai/api/v1/models?supported_parameters=structured_outputs,response_format',{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`models:${r.status}`);const body=await r.json();return(body.data||[]).filter(m=>m.id?.endsWith(':free')).filter(m=>{const p=m.supported_parameters||[];return p.includes('structured_outputs')&&p.includes('response_format');}).sort((a,b)=>a.id.localeCompare(b.id)).map(m=>({id:m.id}));}
async function selectModel(models){if(!models.length)return null;const bytes=new TextEncoder().encode(`URUX${VERSION}${JSON.stringify(models)}`),digest=await crypto.subtle.digest('SHA-256',bytes),hex=[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');return models[parseInt(hex.slice(-8),16)%models.length].id;}
function validate(batch,stage){if(!batch||!Array.isArray(batch.encounters)||batch.encounters.length<3||batch.encounters.length>6)return false;const spec=ALLOWED_STAGES[stage],n=batch.nebulaUpdate;if(!n||!finite(n.darkZoneFraction)||n.darkZoneFraction<.3||n.darkZoneFraction>1||!finite(n.filamentDensity)||n.filamentDensity<0||n.filamentDensity>1||!n.luminousCore||!finite(n.luminousCore.x)||!finite(n.luminousCore.y)||!Array.isArray(n.chromaticRange)||!n.chromaticRange.length||!n.chromaticRange.every(hex))return false;const ids=new Set();for(const e of batch.encounters){if(!e||typeof e.id!=='string'||!e.id.trim()||ids.has(e.id)||e.narrativeStage!==stage||!spec.encounterTypes.includes(e.objectType)||e.spawnDepth!==0||!e.spawnPosition||!finite(e.spawnPosition.x)||!finite(e.spawnPosition.y)||Math.abs(e.spawnPosition.x)>1.5||Math.abs(e.spawnPosition.y)>1.5||!e.trajectoryVector||!finite(e.trajectoryVector.x)||!finite(e.trajectoryVector.y)||!finite(e.trajectoryVector.z)||Math.abs(e.trajectoryVector.x)+Math.abs(e.trajectoryVector.y)+Math.abs(e.trajectoryVector.z)<.001||!finite(e.scale)||e.scale<=0||e.scale>8||!finite(e.speed)||e.speed<=0||e.speed>4||!finite(e.luminosity)||e.luminosity<0||e.luminosity>3||!finite(e.durationSeconds)||e.durationSeconds<3||e.durationSeconds>45||!Array.isArray(e.palette)||!e.palette.length||!e.palette.every(hex))return false;ids.add(e.id);}return true;}
function systemPrompt(stage){const s=ALLOWED_STAGES[stage];return`Eres el director narrativo del tránsito cósmico de URUX. Generas instrucciones para el motor Three.js que renderiza el viaje de un alma a través del cosmos. Responde ÚNICAMENTE con JSON válido, sin texto adicional, sin markdown, sin backticks. El JSON debe seguir exactamente el schema de encounters + nebulaUpdate. Cada encuentro debe tener una razón narrativa coherente con el estado: ${stage}. Usa únicamente estos objectType para este estado: ${s.encounterTypes.join(', ')}. Los objetos nacen desde la profundidad (spawnDepth: 0) y avanzan hacia el observador. Mantén zonas oscuras (darkZoneFraction >= 0.3). La paleta cromática del estado actual es: ${s.paletteHint.join(', ')}.`;}
async function generate(stage,env){const models=await eligibleModels(),model=await selectModel(models);if(!model)throw new Error('no_free_structured_model');const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${env.OPENROUTER_API_KEY}`,'Content-Type':'application/json','HTTP-Referer':'https://pychile.github.io/Music_pulse/','X-OpenRouter-Title':'URUX Journey Director'},body:JSON.stringify({model,temperature:.72,provider:{require_parameters:true},response_format:{type:'json_schema',json_schema:SCHEMA},messages:[{role:'system',content:systemPrompt(stage)},{role:'user',content:`Generate 3 to 6 future encounters for ${stage}.`}]})});if(!r.ok){const text=await r.text();throw new Error(`completion:${r.status}:${text.slice(0,180)}`);}const body=await r.json(),content=body.choices?.[0]?.message?.content;if(typeof content!=='string')throw new Error('missing_content');const parsed=JSON.parse(content);if(!validate(parsed,stage))throw new Error('invalid_batch');parsed.nebulaUpdate.darkZoneFraction=Math.max(.3,parsed.nebulaUpdate.darkZoneFraction);return{...parsed,model};}
export default{async fetch(request,env){const origin=request.headers.get('Origin')||'',headers=cors(origin,env),url=new URL(request.url);if(request.method==='OPTIONS')return Object.keys(headers).length?new Response(null,{status:204,headers}):new Response(null,{status:403});if(url.pathname==='/health'&&request.method==='GET')return json({ok:true,service:'urux-journey-api',version:VERSION,openrouterConfigured:Boolean(env.OPENROUTER_API_KEY)},200,headers);if(url.pathname!=='/v1/encounters'||request.method!=='POST')return json({error:'not_found'},404,headers);if(!Object.keys(headers).length)return json({error:'origin_not_allowed'},403);if(!env.OPENROUTER_API_KEY)return json({error:'backend_not_configured'},503,headers);if(env.URUX_RATE_LIMITER){const key='urux-public';const limited=await env.URUX_RATE_LIMITER.limit({key});if(!limited.success)return json({error:'rate_limited'},429,{...headers,'Retry-After':'20'});}let payload;try{payload=await request.json();}catch{return json({error:'invalid_json'},400,headers);}const stage=payload?.stage;if(!ALLOWED_STAGES[stage])return json({error:'invalid_stage'},400,headers);try{return json(await generate(stage,env),200,headers);}catch(error){console.error('URUX backend error',error);return json({error:'upstream_failure'},502,headers);}}};
