export type AudioMixStage='MAIN'|'LIGHT'|'FETAL'|'SILENT';
export class AudioEngine{
  readonly audio:HTMLAudioElement;readonly lightAudio:HTMLAudioElement;readonly fetalAudio:HTMLAudioElement;
  context:AudioContext|null=null;analyser:AnalyserNode|null=null;source:MediaElementAudioSourceNode|null=null;lightSource:MediaElementAudioSourceNode|null=null;fetalSource:MediaElementAudioSourceNode|null=null;mainGain:GainNode|null=null;lightGain:GainNode|null=null;fetalGain:GainNode|null=null;lightLowpass:BiquadFilterNode|null=null;fetalLowpass:BiquadFilterNode|null=null;frequencyData:Uint8Array<ArrayBuffer>|null=null;timeData:Uint8Array<ArrayBuffer>|null=null;mixStage:AudioMixStage='MAIN';private supportStarted=false;
  constructor(public readonly url:string,lightUrl:string='./light-theme.mp3',fetalUrl:string='./fetal-heartbeat.mp3'){
    this.audio=new Audio(url);this.lightAudio=new Audio(lightUrl);this.fetalAudio=new Audio(fetalUrl);
    for(const media of[this.audio,this.lightAudio,this.fetalAudio]){media.preload='auto';media.setAttribute('playsinline','');}
    this.audio.loop=false;this.lightAudio.loop=true;this.fetalAudio.loop=true;
  }
  async ensureReady():Promise<void>{if(!this.context){const AudioCtor=window.AudioContext??(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AudioCtor)throw new Error('Web Audio API unavailable');this.context=new AudioCtor({latencyHint:'interactive'});this.analyser=this.context.createAnalyser();this.analyser.fftSize=2048;this.analyser.smoothingTimeConstant=.62;this.analyser.minDecibels=-95;this.analyser.maxDecibels=-18;this.mainGain=this.context.createGain();this.lightGain=this.context.createGain();this.fetalGain=this.context.createGain();this.lightLowpass=this.context.createBiquadFilter();this.fetalLowpass=this.context.createBiquadFilter();this.lightLowpass.type='lowpass';this.lightLowpass.frequency.value=18000;this.lightLowpass.Q.value=.45;this.fetalLowpass.type='lowpass';this.fetalLowpass.frequency.value=1650;this.fetalLowpass.Q.value=.55;this.mainGain.gain.value=1;this.lightGain.gain.value=0;this.fetalGain.gain.value=0;this.source=this.context.createMediaElementSource(this.audio);this.lightSource=this.context.createMediaElementSource(this.lightAudio);this.fetalSource=this.context.createMediaElementSource(this.fetalAudio);this.source.connect(this.analyser);this.analyser.connect(this.mainGain);this.mainGain.connect(this.context.destination);this.lightSource.connect(this.lightLowpass);this.lightLowpass.connect(this.lightGain);this.lightGain.connect(this.context.destination);this.fetalSource.connect(this.fetalLowpass);this.fetalLowpass.connect(this.fetalGain);this.fetalGain.connect(this.context.destination);this.frequencyData=new Uint8Array(this.analyser.frequencyBinCount);this.timeData=new Uint8Array(this.analyser.fftSize);}if(this.context.state==='suspended')await this.context.resume();}
  private ramp(param:AudioParam,target:number,duration:number){if(!this.context)return;const t=this.context.currentTime;param.cancelScheduledValues(t);param.setValueAtTime(Math.max(.0001,param.value),t);param.linearRampToValueAtTime(target,t+Math.max(.05,duration));}
  private expRamp(param:AudioParam,target:number,duration:number){if(!this.context)return;const t=this.context.currentTime;param.cancelScheduledValues(t);param.setValueAtTime(Math.max(20,param.value),t);param.exponentialRampToValueAtTime(Math.max(20,target),t+Math.max(.05,duration));}
  private async unlockSupportTracks(){if(this.supportStarted)return;this.supportStarted=true;await Promise.allSettled([this.lightAudio.play(),this.fetalAudio.play()]);}
  async play():Promise<void>{await this.ensureReady();await this.audio.play();await this.unlockSupportTracks();if(this.mixStage==='LIGHT'&&this.lightAudio.paused)await this.lightAudio.play().catch(()=>undefined);if(this.mixStage==='FETAL'&&this.fetalAudio.paused)await this.fetalAudio.play().catch(()=>undefined);}
  pause():void{this.audio.pause();this.lightAudio.pause();this.fetalAudio.pause();}
  async transitionToLight(duration=10):Promise<void>{if(this.mixStage!=='MAIN')return;await this.ensureReady();if(!this.mainGain||!this.lightGain||!this.fetalGain||!this.lightLowpass)return;this.mixStage='LIGHT';this.lightAudio.currentTime=0;if(this.lightAudio.paused)await this.lightAudio.play().catch(()=>undefined);this.ramp(this.mainGain.gain,.07,duration);this.ramp(this.lightGain.gain,.92,duration);this.ramp(this.fetalGain.gain,0,Math.min(2,duration));this.expRamp(this.lightLowpass.frequency,18000,Math.min(1.2,duration));}
  async transitionToFetal(duration=13):Promise<void>{if(this.mixStage==='FETAL'||this.mixStage==='SILENT')return;await this.ensureReady();if(!this.mainGain||!this.lightGain||!this.fetalGain||!this.lightLowpass||!this.fetalLowpass)return;this.mixStage='FETAL';this.fetalAudio.currentTime=0;if(this.fetalAudio.paused)await this.fetalAudio.play().catch(()=>undefined);this.ramp(this.mainGain.gain,.018,duration);this.ramp(this.lightGain.gain,.075,duration);this.expRamp(this.lightLowpass.frequency,720,duration);this.ramp(this.fetalGain.gain,.82,duration*.72);this.expRamp(this.fetalLowpass.frequency,1250,duration*.72);}
  fadeToSilence(duration=4):void{if(!this.context||this.mixStage==='SILENT'||!this.mainGain||!this.lightGain||!this.fetalGain)return;this.mixStage='SILENT';this.ramp(this.mainGain.gain,0,duration);this.ramp(this.lightGain.gain,0,duration);this.ramp(this.fetalGain.gain,0,duration);}
  get paused():boolean{return this.audio.paused;}get ended():boolean{return this.audio.ended;}get currentTime():number{return this.audio.currentTime||0;}get duration():number{return Number.isFinite(this.audio.duration)?this.audio.duration:0;}
}
