import * as THREE from 'three';
import { VolumetricNebulaRaymarcher } from './VolumetricNebulaRaymarcherV53.js?v=20260813-53';
const clamp=v=>Math.max(0,Math.min(1,v));
export class CachedVolumetricNebulaPass{
 constructor(){this.mobile=/iPad|iPhone|iPod|Android/i.test(navigator.userAgent||'')||innerWidth<800;this.nebula=new VolumetricNebulaRaymarcher();this.scene=new THREE.Scene();this.scene.add(this.nebula.mesh);this.interval=1/(this.mobile?10:12);this.age=this.interval;this.initialized=false;this.targetA=this.makeTarget(320,180);this.targetB=this.makeTarget(320,180);this.current=this.targetA;this.previous=this.targetA;this.compositeScene=new THREE.Scene();this.compositeCamera=new THREE.OrthographicCamera(-1,1,1,-1,0,1);this.compositeMaterial=new THREE.ShaderMaterial({depthTest:false,depthWrite:false,transparent:false,uniforms:{uPrev:{value:this.targetA.texture},uCurr:{value:this.targetA.texture},uBlend:{value:1}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}`,fragmentShader:`varying vec2 vUv;uniform sampler2D uPrev,uCurr;uniform float uBlend;void main(){vec4 a=texture2D(uPrev,vUv),b=texture2D(uCurr,vUv);float t=uBlend*uBlend*(3.0-2.0*uBlend);gl_FragColor=mix(a,b,t);}`});this.quad=new THREE.Mesh(new THREE.PlaneGeometry(2,2),this.compositeMaterial);this.quad.frustumCulled=false;this.compositeScene.add(this.quad);this.renderCount=0;this.lastSize={w:320,h:180};}
 makeTarget(w,h){return new THREE.WebGLRenderTarget(w,h,{depthBuffer:false,stencilBuffer:false,minFilter:THREE.LinearFilter,magFilter:THREE.LinearFilter,format:THREE.RGBAFormat,type:THREE.UnsignedByteType});}
 resize(w,h){const budget=this.mobile?90000:230000,scale=Math.min(1,Math.sqrt(budget/Math.max(1,w*h))),tw=Math.max(256,Math.round(w*scale)),th=Math.max(144,Math.round(h*scale));if(tw===this.lastSize.w&&th===this.lastSize.h)return;this.lastSize={w:tw,h:th};this.targetA.setSize(tw,th);this.targetB.setSize(tw,th);this.initialized=false;this.age=this.interval;}
 update(dt,state,features){this.nebula.update(dt,state,features);this.age+=dt;this.compositeMaterial.uniforms.uBlend.value=clamp(this.age/this.interval);}
 renderCache(renderer,camera){if(!this.nebula.active||!this.nebula.mesh.visible)return false;if(this.age+1e-6<this.interval&&this.initialized)return false;const next=this.current===this.targetA?this.targetB:this.targetA;this.previous=this.initialized?this.current:next;this.current=next;const oldTarget=renderer.getRenderTarget(),oldAuto=renderer.autoClear;renderer.setRenderTarget(this.current);renderer.autoClear=true;renderer.setClearColor(0x000000,1);renderer.clear(true,true,true);renderer.render(this.scene,camera);renderer.setRenderTarget(oldTarget);renderer.autoClear=oldAuto;this.compositeMaterial.uniforms.uPrev.value=this.previous.texture;this.compositeMaterial.uniforms.uCurr.value=this.current.texture;this.compositeMaterial.uniforms.uBlend.value=this.initialized?0:1;this.age=0;this.initialized=true;this.renderCount++;return true;}
 composite(renderer){if(!this.nebula.active||!this.initialized)return false;renderer.render(this.compositeScene,this.compositeCamera);return true;}
 get material(){return this.nebula.material;}get visibility(){return this.nebula.visibility;}get raySteps(){return this.nebula.raySteps;}get lightSteps(){return this.nebula.lightSteps;}get active(){return this.nebula.active;}get stats(){return{cached:true,refreshHz:Math.round(1/this.interval),renders:this.renderCount,width:this.lastSize.w,height:this.lastSize.h,active:this.active};}
 dispose(){this.nebula.dispose();this.targetA.dispose();this.targetB.dispose();this.quad.geometry.dispose();this.compositeMaterial.dispose();}
}
