import * as THREE from 'three';
import { normalizedStellarRadiance, celestiaEnhancedTemperatureColor, reflectedLuminosity } from '../thirdparty/CelestiaPhotometry.js?v=20260812-1';
import { parseSpectrumText, spectrumToSRGB, rgbToHex } from '../thirdparty/TrueColorToolsColor.js?v=20260812-1';
const clamp01=v=>Math.max(0,Math.min(1,v));
const smooth01=x=>{const t=clamp01(x);return t*t*(3-2*t);};
const tonePlanet=(rgb,type)=>{const y=rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722,sat=type<.5?.46:.58,neutral=type<.5?[.64,.58,.51]:[.48,.27,.18];return rgb.map((v,i)=>clamp01((y+(v-y)*sat)*.72+neutral[i]*.28));};
const focalTrajectory=(t,s)=>{const rush=Math.pow(t,2.35),peel=smooth01((t-.42)/.50),lateral=peel*peel,x=s.side*lateral*(4+30*Math.pow(t,1.6)),y=lateral*(s.y+Math.sin(t*Math.PI)*s.side*1.2),z=-270+rush*282;return{x,y,z,peel,lateral,rush};};
const planetVertex=`varying vec3 vNormal;varying vec3 vPos;void main(){vNormal=normalize(normalMatrix*normal);vec4 mv=modelViewMatrix*vec4(position,1.0);vPos=mv.xyz;gl_Position=projectionMatrix*mv;}`;
const planetFragment=`precision highp float;varying vec3 vNormal;varying vec3 vPos;uniform vec3 uBase;uniform vec3 uAccent;uniform float uType;uniform float uTime;uniform float uOpacity;uniform float uLunarLambert;uniform float uSpecular;float hash(vec3 p){p=fract(p*.3183099+.1);p*=17.0;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);float n000=hash(i),n100=hash(i+vec3(1,0,0)),n010=hash(i+vec3(0,1,0)),n110=hash(i+vec3(1,1,0)),n001=hash(i+vec3(0,0,1)),n101=hash(i+vec3(1,0,1)),n011=hash(i+vec3(0,1,1)),n111=hash(i+vec3(1,1,1));return mix(mix(mix(n000,n100,f.x),mix(n010,n110,f.x),f.y),mix(mix(n001,n101,f.x),mix(n011,n111,f.x),f.y),f.z);}void main(){vec3 N=normalize(vNormal),V=normalize(-vPos),L=normalize(vec3(-.52,.36,.78));float NL=max(0.0,dot(N,L)),NV=max(0.001,dot(N,V));float cosPhaseAngle=dot(V,L);float phaseAngle=degrees(acos(clamp(cosPhaseAngle,-1.0,1.0)));float lunarLimbDarkening=1.0+phaseAngle*(-0.019+phaseAngle*(0.242e-3-phaseAngle*1.46e-6));float lunarWeight=clamp(uLunarLambert*max(lunarLimbDarkening,0.0),0.0,1.0);float lunarDiffuse=mix(NL,2.0*NL/(NV+NL),lunarWeight);float micro=noise(N*24.0+vec3(uTime*.003,0.0,0.0)),fine=noise(N*71.0);float latitude=asin(clamp(N.y,-1.0,1.0));float bands=.5+.5*sin(latitude*27.0+noise(vec3(N.xz*8.0,0.0))*1.55+uTime*.005);float jet=.5+.5*sin(latitude*54.0+noise(N*13.0)*.85);float spot=exp(-dot(vec2(N.x+.34,N.y+.17),vec2(N.x+.34,N.y+.17))*72.0);float rocky=mix(.78,1.14,micro*.68+fine*.32);float gas=mix(.84,1.10,bands*.76+jet*.24);float pattern=mix(gas,rocky,step(.5,uType));vec3 albedo=mix(uBase,uAccent,uType<.5?bands*.14:(micro-.5)*.12+.08)*pattern;if(uType<.5)albedo=mix(albedo,uAccent*vec3(.92,.66,.54),spot*.12);vec3 H=normalize(L+V);float spec=pow(max(dot(N,H),0.0),mix(28.0,58.0,1.0-uType))*uSpecular*NL;float terminator=smoothstep(-.018,.14,dot(N,L));vec3 col=albedo*(lunarDiffuse*.92)*terminator+albedo*.003+vec3(1.0,.96,.90)*spec;float limb=pow(1.0-NV,3.5);col+=uAccent*limb*.018;gl_FragColor=vec4(col,uOpacity);}`;
const atmosphereFragment=`precision highp float;varying vec3 vNormal;varying vec3 vPos;uniform vec3 uColor;uniform float uOpacity;void main(){vec3 N=normalize(vNormal),V=normalize(-vPos),L=normalize(vec3(-.52,.36,.78));float NV=clamp(dot(N,V),0.0,1.0),NL=max(dot(N,L),0.0);float rim=pow(1.0-NV,3.4);float a=rim*(.18+.82*NL)*uOpacity;gl_FragColor=vec4(uColor*(.38+.62*NL),a);}`;
function makeGlowTexture(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,1,64,64,62);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.12,'rgba(255,255,255,.95)');g.addColorStop(.34,'rgba(190,220,255,.35)');g.addColorStop(1,'rgba(80,120,255,0)');x.fillStyle=g;x.fillRect(0,0,128,128);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.generateMipmaps=false;return t;}
function makePlanetMaterial(base,accent,type){return new THREE.ShaderMaterial({vertexShader:planetVertex,fragmentShader:planetFragment,transparent:true,depthWrite:true,depthTest:true,uniforms:{uBase:{value:new THREE.Color(rgbToHex(base))},uAccent:{value:new THREE.Color(rgbToHex(accent))},uType:{value:type},uTime:{value:0},uOpacity:{value:0},uLunarLambert:{value:type<.5?.24:.76},uSpecular:{value:type<.5?.028:.012}}});}
function makeAtmosphere(radius,color){const geo=new THREE.SphereGeometry(radius*1.035,96,64),mat=new THREE.ShaderMaterial({vertexShader:planetVertex,fragmentShader:atmosphereFragment,transparent:true,depthWrite:false,depthTest:true,side:THREE.FrontSide,blending:THREE.AdditiveBlending,uniforms:{uColor:{value:new THREE.Color(rgbToHex(color))},uOpacity:{value:0}}}),mesh=new THREE.Mesh(geo,mat);mesh.renderOrder=-70;return{mesh,geo,mat};}
function makeRing(color,radius){const geo=new THREE.RingGeometry(radius*1.08,radius*1.54,160),mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false,blending:THREE.NormalBlending}),mesh=new THREE.Mesh(geo,mat);mesh.rotation.x=Math.PI*.57;mesh.rotation.z=.16;return{mesh,geo,mat};}
const EVENTS=[
 {name:'Jupiter spectral fly-by',start:.211,end:.241,side:-1,y:2.1,radius:6.4,type:0,base:[.68,.61,.54],accent:[.82,.72,.62],spectrum:'./assets/truecolor/Jupiter_Li2018_visible.txt?v=1',unit:'nm',ring:false,starTemp:6200,atmos:[.42,.58,.74]},
 {name:'Mars spectral fly-by',start:.391,end:.413,side:1,y:-1.6,radius:4.1,type:1,base:[.48,.27,.18],accent:[.66,.38,.23],spectrum:'./assets/truecolor/Mars_McCord1971_visible.txt?v=1',unit:'nm',ring:false,starTemp:9800,atmos:[.46,.28,.20]},
 {name:'Outer ringed gas system',start:.561,end:.591,side:-1,y:-.9,radius:6.0,type:0,base:[.53,.59,.63],accent:[.68,.73,.78],spectrum:'./assets/truecolor/Jupiter_Li2018_visible.txt?v=1',unit:'nm',ring:true,starTemp:7800,atmos:[.38,.55,.74]},
 {name:'Final rocky system',start:.731,end:.759,side:1,y:1.7,radius:3.6,type:1,base:[.42,.30,.22],accent:[.61,.43,.30],spectrum:'./assets/truecolor/Mars_McCord1971_visible.txt?v=1',unit:'nm',ring:false,starTemp:5600,atmos:[.36,.31,.27]}
];
export class CelestialFlybySystem{
 constructor(){this.group=new THREE.Group();this.time=0;this.activeFlybyCount=0;this.closestObjectZ=-999;this.closestLateralOffset=0;this.focusOriginError=0;this.flybyProgress=0;this.glowTexture=makeGlowTexture();this.flybys=[];for(let i=0;i<EVENTS.length;i++){const spec=EVENTS[i],group=new THREE.Group(),geometry=new THREE.SphereGeometry(spec.radius,128,80),material=makePlanetMaterial(spec.base,spec.accent,spec.type),planet=new THREE.Mesh(geometry,material);planet.renderOrder=-80;group.add(planet);const atmosphere=makeAtmosphere(spec.radius,spec.atmos);group.add(atmosphere.mesh);let ring=null;if(spec.ring){ring=makeRing(rgbToHex(spec.accent),spec.radius);group.add(ring.mesh);}const starColor=celestiaEnhancedTemperatureColor(spec.starTemp),starMat=new THREE.SpriteMaterial({map:this.glowTexture,color:rgbToHex(starColor),transparent:true,opacity:0,depthWrite:false,depthTest:false,blending:THREE.AdditiveBlending,toneMapped:false}),star=new THREE.Sprite(starMat);star.scale.set(7,7,1);star.position.set(-spec.side*12,-spec.y*.35,-18);star.renderOrder=-120;group.add(star);const moonGeo=new THREE.SphereGeometry(spec.radius*.19,64,40),moonMat=makePlanetMaterial([.30,.31,.33],[.50,.52,.56],1),moon=new THREE.Mesh(moonGeo,moonMat);group.add(moon);group.visible=false;this.group.add(group);const item={spec,group,geometry,material,planet,atmosphere,ring,star,starMat,moon,moonGeo,moonMat};this.flybys.push(item);this.loadSpectralColor(item);}}
 async loadSpectralColor(item){try{const text=await fetch(item.spec.spectrum).then(r=>{if(!r.ok)throw new Error(`${r.status}`);return r.text();}),raw=await spectrumToSRGB(parseSpectrumText(text,{wavelengthUnit:item.spec.unit})),rgb=tonePlanet(raw,item.spec.type),accent=rgb.map((v,i)=>clamp01(v*(i===0?1.07:i===2?1.04:1.02)+.015));item.material.uniforms.uBase.value.setHex(rgbToHex(rgb));item.material.uniforms.uAccent.value.setHex(rgbToHex(accent));if(item.ring)item.ring.mat.color.setHex(rgbToHex(accent));}catch(e){console.warn('URUX TrueColorTools spectral color fallback',item.spec.name,e);}}
 update(dt,state){this.time+=dt;const p=clamp01(state.soulProgress||0),fade=1-clamp01(state.finalFade||0);this.activeFlybyCount=0;this.closestObjectZ=-999;this.closestLateralOffset=0;this.focusOriginError=0;this.flybyProgress=0;for(let i=0;i<this.flybys.length;i++){const f=this.flybys[i],s=f.spec,raw=(p-s.start)/(s.end-s.start);if(raw<=0||raw>=1){f.group.visible=false;continue;}const env=smooth01(raw/.10)*(1-smooth01((raw-.90)/.10))*fade,t=smooth01(raw),traj=focalTrajectory(t,s);this.activeFlybyCount++;f.group.visible=env>.005;f.group.position.set(traj.x,traj.y,traj.z);f.group.rotation.y=traj.lateral*(this.time*.025*s.side+t*.42);f.group.rotation.x=traj.lateral*Math.sin(t*Math.PI)*.06*s.side;f.planet.rotation.y+=dt*(.035+.025*i);f.material.uniforms.uTime.value=this.time;f.material.uniforms.uOpacity.value=Math.min(.98,env*1.04);f.atmosphere.mat.uniforms.uOpacity.value=Math.min(.20,env*(s.type<.5?.11:.07));f.moonMat.uniforms.uTime.value=this.time*.8;f.moonMat.uniforms.uOpacity.value=Math.min(.72,env*traj.peel);const orbit=t*Math.PI*2.0+i;f.moon.position.set(Math.cos(orbit)*8.2,Math.sin(orbit*.72)*2.6,-3+Math.sin(orbit)*2);const starRadiance=normalizedStellarRadiance(1.4-5.5*t,.50,.0015,5.2);f.starMat.opacity=Math.min(.68,env*(.07+starRadiance*.12)*(.12+.88*traj.peel));const starScale=4+Math.min(8,starRadiance*.8);f.star.scale.set(starScale,starScale,1);const reflected=reflectedLuminosity(1,Math.max(1.4,8.5-5*t),s.radius*.08);f.material.uniforms.uOpacity.value*=Math.min(1,.78+Math.sqrt(reflected)*2.4);if(f.ring)f.ring.mat.opacity=Math.min(.24,env*.22*(.18+.82*traj.peel));this.closestObjectZ=Math.max(this.closestObjectZ,traj.z);this.closestLateralOffset=Math.max(this.closestLateralOffset,Math.hypot(traj.x,traj.y));this.focusOriginError=traj.peel<.05?Math.hypot(traj.x,traj.y):this.focusOriginError;this.flybyProgress=Math.max(this.flybyProgress,t);}}
 dispose(){for(const f of this.flybys){f.geometry.dispose();f.material.dispose();f.atmosphere.geo.dispose();f.atmosphere.mat.dispose();f.moonGeo.dispose();f.moonMat.dispose();f.starMat.dispose();if(f.ring){f.ring.geo.dispose();f.ring.mat.dispose();}}this.glowTexture.dispose();}
}
