import * as THREE from 'three';
import { normalizedStellarRadiance, celestiaEnhancedTemperatureColor, reflectedLuminosity } from '../thirdparty/CelestiaPhotometry.js?v=20260812-1';
import { parseSpectrumText, spectrumToSRGB, rgbToHex } from '../thirdparty/TrueColorToolsColor.js?v=20260812-1';

const clamp01=v=>Math.max(0,Math.min(1,v));
const smooth01=x=>{const t=clamp01(x);return t*t*(3-2*t);};

const planetVertex=`varying vec3 vNormal;varying vec3 vPos;void main(){vNormal=normalize(normalMatrix*normal);vec4 mv=modelViewMatrix*vec4(position,1.0);vPos=mv.xyz;gl_Position=projectionMatrix*mv;}`;
const planetFragment=`precision highp float;varying vec3 vNormal;varying vec3 vPos;uniform vec3 uBase;uniform vec3 uAccent;uniform float uType;uniform float uTime;uniform float uOpacity;float hash(vec3 p){p=fract(p*.3183099+.1);p*=17.0;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}void main(){vec3 n=normalize(vNormal);vec3 L=normalize(vec3(-.52,.36,.78));float lam=max(dot(n,L),0.0);float rim=pow(1.0-max(dot(n,normalize(-vPos)),0.0),2.8);float bands=.5+.5*sin((n.y*18.0+sin(n.x*7.0)*1.4)+uTime*.020);float rough=hash(floor(n*38.0))*.55+hash(floor(n*71.0))*.45;float pattern=uType<.5?mix(.72,1.18,smoothstep(.22,.78,bands)):mix(.70,1.22,rough);vec3 albedo=mix(uBase,uAccent,uType<.5?bands*.28:rough*.22)*pattern;vec3 col=albedo*(.10+lam*.88)+uAccent*rim*.14;gl_FragColor=vec4(col,uOpacity);}`;

function makeGlowTexture(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,1,64,64,62);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.12,'rgba(255,255,255,.95)');g.addColorStop(.34,'rgba(190,220,255,.35)');g.addColorStop(1,'rgba(80,120,255,0)');x.fillStyle=g;x.fillRect(0,0,128,128);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.generateMipmaps=false;return t;}
function makePlanetMaterial(base,accent,type){return new THREE.ShaderMaterial({vertexShader:planetVertex,fragmentShader:planetFragment,transparent:true,depthWrite:true,depthTest:true,uniforms:{uBase:{value:new THREE.Color(rgbToHex(base))},uAccent:{value:new THREE.Color(rgbToHex(accent))},uType:{value:type},uTime:{value:0},uOpacity:{value:0}}});}
function makeRing(color){const geo=new THREE.RingGeometry(4.7,7.2,96),mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.0,side:THREE.DoubleSide,depthWrite:false,blending:THREE.NormalBlending}),mesh=new THREE.Mesh(geo,mat);mesh.rotation.x=Math.PI*.56;mesh.rotation.z=.18;return{mesh,geo,mat};}

const EVENTS=[
 {name:'Jupiter spectral fly-by',start:.145,end:.225,side:-1,y:2.6,radius:5.0,type:0,base:[.76,.65,.52],accent:[.96,.82,.67],spectrum:'./assets/truecolor/Jupiter_Li2018_visible.txt?v=1',unit:'nm',ring:true,starTemp:6200},
 {name:'Mars spectral fly-by',start:.335,end:.405,side:1,y:-2.0,radius:3.15,type:1,base:[.62,.25,.12],accent:[.92,.46,.22],spectrum:'./assets/truecolor/Mars_McCord1971_visible.txt?v=1',unit:'nm',ring:false,starTemp:9800},
 {name:'Outer gas system',start:.545,end:.625,side:-1,y:-1.2,radius:4.35,type:0,base:[.46,.62,.75],accent:[.78,.87,.98],spectrum:'./assets/truecolor/Jupiter_Li2018_visible.txt?v=1',unit:'nm',ring:true,starTemp:7800},
 {name:'Final rocky system',start:.735,end:.805,side:1,y:2.2,radius:2.75,type:1,base:[.56,.29,.17],accent:[.88,.58,.36],spectrum:'./assets/truecolor/Mars_McCord1971_visible.txt?v=1',unit:'nm',ring:false,starTemp:5600}
];

export class CelestialFlybySystem{
 constructor(){this.group=new THREE.Group();this.time=0;this.activeFlybyCount=0;this.closestObjectZ=-999;this.glowTexture=makeGlowTexture();this.flybys=[];for(let i=0;i<EVENTS.length;i++){const spec=EVENTS[i],group=new THREE.Group(),geometry=new THREE.SphereGeometry(spec.radius,48,30),material=makePlanetMaterial(spec.base,spec.accent,spec.type),planet=new THREE.Mesh(geometry,material);planet.renderOrder=-80;group.add(planet);let ring=null;if(spec.ring){ring=makeRing(rgbToHex(spec.accent));group.add(ring.mesh);}const starColor=celestiaEnhancedTemperatureColor(spec.starTemp),starMat=new THREE.SpriteMaterial({map:this.glowTexture,color:rgbToHex(starColor),transparent:true,opacity:0,depthWrite:false,depthTest:false,blending:THREE.AdditiveBlending,toneMapped:false}),star=new THREE.Sprite(starMat);star.scale.set(7,7,1);star.position.set(-spec.side*13,-spec.y*.4,-16);star.renderOrder=-120;group.add(star);const moonGeo=new THREE.SphereGeometry(spec.radius*.22,24,14),moonMat=makePlanetMaterial(spec.type<.5?[.42,.43,.45]:[.30,.31,.34],[.65,.67,.70],1),moon=new THREE.Mesh(moonGeo,moonMat);moon.position.set(spec.side*7,2.4,-4);group.add(moon);group.visible=false;this.group.add(group);const item={spec,group,geometry,material,planet,ring,star,starMat,moon,moonGeo,moonMat};this.flybys.push(item);this.loadSpectralColor(item);}}
 async loadSpectralColor(item){try{const text=await fetch(item.spec.spectrum).then(r=>{if(!r.ok)throw new Error(`${r.status}`);return r.text();});const rgb=await spectrumToSRGB(parseSpectrumText(text,{wavelengthUnit:item.spec.unit}));item.material.uniforms.uBase.value.setHex(rgbToHex(rgb));const accent=rgb.map((v,i)=>Math.min(1,v*(i===0?1.17:i===2?1.10:1.06)));item.material.uniforms.uAccent.value.setHex(rgbToHex(accent));if(item.ring)item.ring.mat.color.setHex(rgbToHex(accent));}catch(e){console.warn('URUX TrueColorTools spectral color fallback',item.spec.name,e);}}
 update(dt,state){this.time+=dt;const p=clamp01(state.soulProgress||0),fade=1-clamp01(state.finalFade||0);this.activeFlybyCount=0;this.closestObjectZ=-999;for(let i=0;i<this.flybys.length;i++){const f=this.flybys[i],s=f.spec,raw=(p-s.start)/(s.end-s.start);if(raw<=0||raw>=1){f.group.visible=false;continue;}const enter=smooth01(raw/.12),exit=1-smooth01((raw-.86)/.14),env=enter*exit*fade,t=smooth01(raw);this.activeFlybyCount++;f.group.visible=env>.005;const z=-185+t*197,x=s.side*(4.5+Math.pow(t,1.55)*23),y=s.y+Math.sin(t*Math.PI)*s.side*1.4;f.group.position.set(x,y,z);f.group.rotation.y=this.time*.055*s.side+t*.52;f.planet.rotation.y+=dt*(.12+.10*i);f.material.uniforms.uTime.value=this.time;f.material.uniforms.uOpacity.value=Math.min(1,env*1.18);f.moonMat.uniforms.uTime.value=this.time*.8;f.moonMat.uniforms.uOpacity.value=Math.min(.85,env);const orbit=t*Math.PI*2.2+i;f.moon.position.set(Math.cos(orbit)*7.5,Math.sin(orbit*.7)*2.7,-3+Math.sin(orbit)*2);const appMag=1.2-5.8*t;const starRadiance=normalizedStellarRadiance(appMag,.55,.0015,5.5);f.starMat.opacity=Math.min(.92,env*(.12+starRadiance*.18));const starScale=5+Math.min(11,starRadiance*1.1);f.star.scale.set(starScale,starScale,1);const reflected=reflectedLuminosity(1,Math.max(1.2,8-5*t),s.radius*.08);f.material.uniforms.uOpacity.value*=Math.min(1,.78+Math.sqrt(reflected)*3.2);if(f.ring)f.ring.mat.opacity=Math.min(.48,env*.43);this.closestObjectZ=Math.max(this.closestObjectZ,z);}}
 dispose(){for(const f of this.flybys){f.geometry.dispose();f.material.dispose();f.moonGeo.dispose();f.moonMat.dispose();f.starMat.dispose();if(f.ring){f.ring.geo.dispose();f.ring.mat.dispose();}}this.glowTexture.dispose();}
}
