import * as THREE from 'three';

const clamp01=v=>Math.max(0,Math.min(1,v));
const smooth01=v=>{const t=clamp01(v);return t*t*(3-2*t);};
const hash=n=>{const x=Math.sin(n*12.9898+78.233)*43758.5453123;return x-Math.floor(x);};
const signed=n=>hash(n)*2-1;
const GAS_COLORS=[
 new THREE.Color(0x5f98ff),new THREE.Color(0x9570e6),new THREE.Color(0xed7d94),
 new THREE.Color(0xe79b58),new THREE.Color(0xe66552),new THREE.Color(0x4f7dcc),
 new THREE.Color(0xbd72c7),new THREE.Color(0x72b9d9),new THREE.Color(0x9e6885),
 new THREE.Color(0xb7a3ef)
];

const vertexShader=`
precision mediump float;
attribute float aSize;attribute float aSeed;attribute float aDensity;attribute float aGlow;attribute vec3 color;
uniform float uTime;uniform float uPixelRatio;varying float vSeed;varying float vDensity;varying float vGlow;varying vec3 vColor;
void main(){vec3 p=position;float sway=sin(uTime*.10+aSeed*23.0)*.26;p.x+=sway;p.y+=cos(uTime*.075+aSeed*17.0)*.18;vec4 mv=modelViewMatrix*vec4(p,1.0);float perspective=290.0/max(1.0,-mv.z);gl_PointSize=clamp(aSize*uPixelRatio*perspective,1.5,300.0);gl_Position=projectionMatrix*mv;vSeed=aSeed;vDensity=aDensity;vGlow=aGlow;vColor=color;}`;

const fragmentShader=`
precision mediump float;uniform float uOpacity;uniform float uTime;varying float vSeed;varying float vDensity;varying float vGlow;varying vec3 vColor;
float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7))+vSeed*41.13)*43758.5453);}float n2(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);float a=h(i),b=h(i+vec2(1,0)),c=h(i+vec2(0,1)),d=h(i+vec2(1,1));return mix(mix(a,b,f.x),mix(c,d,f.x),f.y);}float fbm2(vec2 p){float v=0.0,a=.50;for(int i=0;i<3;i++){v+=n2(p)*a;p=p*2.07+vec2(5.1,-3.7);a*=.50;}return v;}
void main(){vec2 p=gl_PointCoord-.5;float ang=atan(p.y,p.x);float warp=.074*sin(ang*3.0+vSeed*19.0)+.047*sin(ang*7.0-vSeed*13.0)+.027*sin(ang*11.0+uTime*.03);float r=length(p*vec2(1.0,.80))+warp;float body=1.0-smoothstep(.29,.55,r);vec2 q=(p+.5)*vec2(7.0,6.2)+vec2(vSeed*11.0,vSeed*17.0);float macro=fbm2(q*.62+uTime*.002),fine=fbm2(q*1.72-vec2(uTime*.003,0.0));float cellular=h(floor(q*1.52));float filament=.5+.5*sin((q.x*.72+q.y*.53+macro*3.2+vSeed*7.0)*3.14159);filament=smoothstep(.46,.88,filament);float hole=smoothstep(.61,.84,fbm2(q*2.10+vec2(13.1,-8.4)));float breakup=mix(.45,1.0,macro)*mix(.58,1.0,fine)*mix(.64,1.0,cellular)*mix(.72,1.0,filament);breakup*=1.0-hole*.72;float alpha=body*breakup*vDensity*uOpacity;alpha*=smoothstep(.006,.108,alpha);if(alpha<.008)discard;float core=pow(max(0.0,1.0-r*1.58),2.1);vec3 hot=vec3(1.0,.88,.78),ion=vec3(.78,.88,1.0);vec3 c=mix(vColor,hot,core*(.10+.30*vGlow));c=mix(c,ion,filament*vGlow*.12);c*=.86+vGlow*.50;gl_FragColor=vec4(c,alpha);}`;

function makeMaterial(mobile,additive=false){return new THREE.ShaderMaterial({vertexShader,fragmentShader,uniforms:{uTime:{value:0},uOpacity:{value:0},uPixelRatio:{value:Math.min(devicePixelRatio||1,mobile?1:1.35)}},transparent:true,depthWrite:false,depthTest:false,toneMapped:false,blending:additive?THREE.AdditiveBlending:THREE.NormalBlending});}

function buildVolumeGeometry(seed,count,mobile,emissive=false){
 const positions=new Float32Array(count*3),sizes=new Float32Array(count),seeds=new Float32Array(count),densities=new Float32Array(count),glows=new Float32Array(count),colors=new Float32Array(count*3);const lobes=mobile?7:9,centers=[];
 for(let l=0;l<lobes;l++){const a=(l/lobes)*Math.PI*2+signed(seed+l*9.1)*.48,radius=2.2+hash(seed+l*4.3)*9.0;centers.push({x:Math.cos(a)*radius*(.62+hash(seed+l*5.7)*.58),y:Math.sin(a)*radius*(.42+hash(seed+l*7.9)*.48),z:signed(seed+l*11.3)*12});}
 for(let i=0;i<count;i++){const s=seed+i*1.731,l=i%lobes,c=centers[l],filament=i%5===0,rr=Math.pow(hash(s+2.1),filament?.40:.65),a=hash(s+4.7)*Math.PI*2,radial=(filament?13.2:9.4)*rr*(.56+hash(s+8.1)*.96),x=c.x+Math.cos(a)*radial+signed(s+12.7)*(filament?5.8:3.0),y=c.y+Math.sin(a)*radial*(.40+hash(s+14.2)*.50)+signed(s+15.1)*(filament?4.1:2.2),z=c.z+signed(s+17.3)*(filament?23:15)+signed(s+19.1)*radial*.42;positions[i*3]=x;positions[i*3+1]=y;positions[i*3+2]=z;sizes[i]=(filament?11:15)+hash(s+23.7)*(filament?15:22);seeds[i]=hash(s+29.4);densities[i]=(emissive?.28:.38)+hash(s+31.7)*(emissive?.38:.50);glows[i]=emissive?(.64+hash(s+34.2)*.36):(.14+hash(s+34.2)*.34);const base=GAS_COLORS[(l+i+(emissive?3:0))%GAS_COLORS.length],brightness=(emissive?.96:.79)+hash(s+37.9)*(emissive?.52:.46);colors[i*3]=base.r*brightness;colors[i*3+1]=base.g*brightness;colors[i*3+2]=base.b*brightness;}
 const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(positions,3));g.setAttribute('aSize',new THREE.BufferAttribute(sizes,1));g.setAttribute('aSeed',new THREE.BufferAttribute(seeds,1));g.setAttribute('aDensity',new THREE.BufferAttribute(densities,1));g.setAttribute('aGlow',new THREE.BufferAttribute(glows,1));g.setAttribute('color',new THREE.BufferAttribute(colors,3));g.computeBoundingSphere();return g;
}

export class CloudNebulaVolume{
 constructor(){this.group=new THREE.Group();this.volumes=[];this.time=0;this.crossings=0;this.cameraCrossings=0;this.nearClouds=0;this.maxOpacity=0;this.peakOpacity=0;this.ready=true;this.mobile=/iPad|iPhone|iPod|Android/i.test(navigator.userAgent||'')||innerWidth<800;this.lastWall=performance.now();const volumeCount=this.mobile?5:6,particlesPerVolume=this.mobile?440:600;for(let i=0;i<volumeCount;i++)this.createVolume(i,particlesPerVolume,i%3===1);this.totalParticles=volumeCount*particlesPerVolume;}
 createVolume(i,count,emissive){const seed=71+i*47.3,geometry=buildVolumeGeometry(seed,count,this.mobile,emissive),material=makeMaterial(this.mobile,emissive),points=new THREE.Points(geometry,material);points.frustumCulled=false;points.renderOrder=-760+i;const z=i===0?-3:-14-i*(this.mobile?46:48),x=signed(seed+2.4)*(i===0?1.5:6.4),y=signed(seed+5.1)*(i===0?1.2:4.8);points.position.set(x,y,z);points.rotation.z=signed(seed+8.2)*.46;this.group.add(points);this.volumes.push({points,geometry,material,seed,emissive,speed:.86+hash(seed+13.2)*.28,spin:signed(seed+19.4)*.00026,lastZ:z});}
 recycle(q){let far=-178;for(const v of this.volumes)far=Math.min(far,v.points.position.z);q.points.position.z=far-(this.mobile?42:44)-hash(q.seed+this.crossings*1.17)*15;q.points.position.x=signed(q.seed+this.crossings*2.31)*7;q.points.position.y=signed(q.seed+this.crossings*3.17)*5.5;q.points.rotation.z=signed(q.seed+this.crossings*4.11)*.52;q.lastZ=q.points.position.z;this.crossings++;}
 update(dt,state){const now=performance.now(),simDt=Math.min(.12,Math.max(dt,(now-this.lastWall)/1000));this.lastWall=now;this.time+=simDt;const n=clamp01(state.nebulaPresence||0),g=clamp01(state.galaxyReveal||0),light=clamp01(state.livingLight||0),tunnel=clamp01(state.tunnelDrive||0),fade=1-clamp01(state.finalFade||0),presence=Math.min(1,.80+n*.24+g*.16+light*.12+tunnel*.10)*fade,speed=Math.max(5.0,(state.speed||8)*.96);this.nearClouds=0;this.maxOpacity=0;for(const q of this.volumes){q.points.position.z+=speed*q.speed*simDt;let z=q.points.position.z;if(q.lastZ<0&&z>=0)this.cameraCrossings++;q.lastZ=z;if(z>40){this.recycle(q);z=q.points.position.z;}const farFade=smooth01((z+248)/86),nearFade=1-smooth01((z-26)/40),nearBoost=.86+1.44*Math.exp(-Math.pow((z+10)/27,2)),base=q.emissive?.44:.58,cap=q.emissive?.84:.97,opacity=Math.min(cap,base*presence*farFade*nearFade*nearBoost);q.material.uniforms.uOpacity.value=opacity;q.material.uniforms.uTime.value=this.time;q.points.rotation.z+=q.spin*simDt*60;q.points.position.x+=Math.sin(this.time*.024+q.seed)*simDt*.024;q.points.position.y+=Math.cos(this.time*.020+q.seed*.71)*simDt*.020;if(z>-68&&z<28&&opacity>.10)this.nearClouds++;this.maxOpacity=Math.max(this.maxOpacity,opacity);this.peakOpacity=Math.max(this.peakOpacity,opacity);}}
 get stats(){return{mode:'continuous-volumetric-traversal',ready:this.ready,volumeType:'3d-point-gas-v59',visualRevision:'v62-fbm-hybrid',coloredGas:true,rectangularBillboards:false,supportGeometry:'THREE.Points',hybridRaymarchSupport:true,densityNoise:'layered-fbm-cellular',cameraTraversal:true,filaments:true,holes:true,performanceBalanced:true,colorFamilies:GAS_COLORS.length,volumes:this.volumes.length,particles:this.totalParticles,layers:this.totalParticles,crossings:this.crossings,cameraCrossings:this.cameraCrossings,nearClouds:this.nearClouds,maxOpacity:+this.maxOpacity.toFixed(3),peakOpacity:+this.peakOpacity.toFixed(3),emissiveVolumes:this.volumes.filter(v=>v.emissive).length};}
 dispose(){for(const q of this.volumes){q.geometry.dispose();q.material.dispose();}this.volumes.length=0;}
}
