import * as THREE from 'three';
import { getGalaxyCloudTexture } from '../assets/SharedSpaceAssetsV53.js?v=20260813-53';

const clamp01=v=>Math.max(0,Math.min(1,v));
const smooth01=v=>{const t=clamp01(v);return t*t*(3-2*t);};
const hash=n=>{const x=Math.sin(n*12.9898+78.233)*43758.5453;return x-Math.floor(x);};
const GAS_COLORS=[0x7798cf,0x8d72b7,0xb27c77,0x708da9,0xa36f91,0xa78960];
function fallbackCloudTexture(){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.clearRect(0,0,256,256);for(let i=0;i<22;i++){const px=(.06+hash(11+i*2.7)*.88)*256,py=(.06+hash(33+i*3.1)*.88)*256,r=(.09+hash(51+i*4.7)*.24)*256,g=x.createRadialGradient(px,py,r*.035,px,py,r);g.addColorStop(0,'rgba(255,255,255,.92)');g.addColorStop(.24,'rgba(255,255,255,.58)');g.addColorStop(.60,'rgba(255,255,255,.18)');g.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=g;x.fillRect(0,0,256,256);}x.globalCompositeOperation='destination-out';for(let i=0;i<7;i++){const px=hash(91+i*5.1)*256,py=hash(121+i*3.9)*256,r=(.05+hash(151+i*4.3)*.16)*256,g=x.createRadialGradient(px,py,0,px,py,r);g.addColorStop(0,'rgba(0,0,0,.48)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.fillRect(0,0,256,256);}x.globalCompositeOperation='source-over';const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.generateMipmaps=false;t.minFilter=THREE.LinearFilter;t.magFilter=THREE.LinearFilter;return t;}

export class CloudNebulaLayer{
 constructor(){
  this.group=new THREE.Group();this.layers=[];this.ready=true;this.time=0;this.crossings=0;this.nearClouds=0;this.maxOpacity=0;this.peakOpacity=0;this.textureSource='procedural-fallback';this.mobile=/iPad|iPhone|iPod|Android/i.test(navigator.userAgent||'')||innerWidth<800;this.fallbackTexture=fallbackCloudTexture();const count=this.mobile?11:14;for(let i=0;i<count;i++)this.createLayer(i,count);getGalaxyCloudTexture().then(texture=>{for(let i=0;i<this.layers.length;i++){const q=this.layers[i];if(i%2===1){q.material.map=texture;q.material.needsUpdate=true;}}this.textureSource='hybrid-local-webgpu';}).catch(()=>{});
 }
 createLayer(i,count){
  const role=i%7===0?'dust':(i%5===0?'emission':'gas'),seed=17+i*13.17,center=i%3===0,color=role==='dust'?0x070910:(role==='emission'?0xcbdaf2:GAS_COLORS[i%GAS_COLORS.length]),material=new THREE.SpriteMaterial({map:this.fallbackTexture,transparent:true,opacity:0,depthWrite:false,depthTest:false,color:new THREE.Color(color),blending:role==='emission'?THREE.AdditiveBlending:THREE.NormalBlending,toneMapped:false}),sprite=new THREE.Sprite(material),z=-16-i*(this.mobile?19:17),x=center?(hash(seed)-.5)*6:(hash(seed)-.5)*38,y=center?(hash(seed+2)-.5)*4.5:(hash(seed+2)-.5)*25,width=(center?112:82)+hash(seed+3)*(center?68:78),aspect=.58+hash(seed+4)*.40;sprite.position.set(x,y,z);sprite.scale.set(width,width*aspect,1);material.rotation=(hash(seed+5)-.5)*Math.PI*1.8;sprite.renderOrder=role==='dust'?8:(role==='emission'?-870:-900);this.group.add(sprite);const base=role==='dust'?.090:(role==='emission'?.052:(center?.180:.120+hash(seed+9)*.025));this.layers.push({sprite,material,role,seed,center,width,aspect,speed:.78+hash(seed+6)*.34,spin:(hash(seed+7)>.5?1:-1)*(.00011+hash(seed+8)*.00020),base});
 }
 recycle(q){let far=-155;for(const p of this.layers)far=Math.min(far,p.sprite.position.z);q.sprite.position.z=far-(this.mobile?17:14)-hash(q.seed+this.crossings)*8;q.sprite.position.x=q.center?(hash(q.seed+this.crossings*.71)-.5)*7:(hash(q.seed+this.crossings*.71)-.5)*40;q.sprite.position.y=q.center?(hash(q.seed+this.crossings*.93)-.5)*5:(hash(q.seed+this.crossings*.93)-.5)*26;this.crossings++;}
 update(dt,state){
  this.time+=dt;const n=clamp01(state.nebulaPresence||0),r=clamp01(state.galaxyReveal||0),light=clamp01(state.livingLight||0),tunnel=clamp01(state.tunnelDrive||0),fade=1-clamp01(state.finalFade||0),presence=Math.min(1,.84+n*.22+r*.16+light*.10+tunnel*.08)*fade,speed=Math.max(3.6,(state.speed||8)*.92);this.nearClouds=0;this.maxOpacity=0;
  for(const q of this.layers){q.sprite.position.z+=speed*q.speed*dt;if(q.sprite.position.z>3)this.recycle(q);const z=q.sprite.position.z,farFade=smooth01((z+245)/105),nearFade=1-smooth01((z+13)/16),nearBoost=.96+.92*Math.exp(-Math.pow((z+23)/30,2)),pulse=.94+.06*Math.sin(this.time*.13+q.seed),cap=q.role==='dust'?.165:(q.role==='emission'?.105:(q.center?.34:.255)),opacity=Math.min(cap,q.base*presence*farFade*nearFade*nearBoost*pulse);q.material.opacity=opacity;q.material.rotation+=q.spin*dt*60;const drift=1-clamp01((-z)/220);q.sprite.position.x+=Math.sin(this.time*.017+q.seed)*dt*.025*(1+drift);q.sprite.position.y+=Math.cos(this.time*.014+q.seed*.7)*dt*.018*(1+drift);if(z>-50&&z<-2&&opacity>.035)this.nearClouds++;this.maxOpacity=Math.max(this.maxOpacity,opacity);this.peakOpacity=Math.max(this.peakOpacity,opacity);}
 }
 get stats(){return{mode:'continuous-traversal',ready:this.ready,textureSource:this.textureSource,layers:this.layers.length,crossings:this.crossings,nearClouds:this.nearClouds,maxOpacity:+this.maxOpacity.toFixed(3),peakOpacity:+this.peakOpacity.toFixed(3)};}
 dispose(){for(const q of this.layers)q.material.dispose();this.fallbackTexture.dispose();this.layers.length=0;}
}
