import * as THREE from 'three';
import { generateSpiralPosition, DEFAULT_WEBGPU_GALAXY_CONFIG } from '../thirdparty/WebGPUGalaxyModel.js?v=20260812-1';
import { normalizedStellarRadiance, celestiaEnhancedTemperatureColor } from '../thirdparty/CelestiaPhotometry.js?v=20260812-1';
import { getGalaxyCloudTexture } from '../assets/SharedSpaceAssetsV53.js?v=20260813-53';
const clamp=v=>Math.max(0,Math.min(1,v));
const smooth=v=>{const t=clamp(v);return t*t*(3-2*t)};
const SECTORS=[
 {start:.055,end:.205,x:-7,y:3.2,seed:11,starK:10500,arms:4,color:0x6b8ed4},
 {start:.245,end:.385,x:7.4,y:-3.1,seed:29,starK:7200,arms:3,color:0x8a66ad},
 {start:.415,end:.555,x:-7.8,y:-1,seed:47,starK:12800,arms:5,color:0x4777bb},
 {start:.595,end:.725,x:7.1,y:3.8,seed:73,starK:8600,arms:4,color:0xb06b67},
 {start:.765,end:.895,x:-6.4,y:1.6,seed:101,starK:6200,arms:3,color:0x9f6b91}
];
function config(spec){return{...DEFAULT_WEBGPU_GALAXY_CONFIG,galaxyRadius:23,galaxyThickness:6.2,spiralTightness:1.12+(spec.seed%5)*.065,armCount:spec.arms,armWidth:6.2,randomness:1.18,rotationSpeed:.042};}
function makeCluster(spec,count){const cfg=config(spec),positions=new Float32Array(count*3),sizes=new Float32Array(count),colors=new Float32Array(count*3);for(let i=0;i<count;i++){const m=generateSpiralPosition(i,cfg,spec.seed*100),p=i*3;positions[p]=m.position[0];positions[p+1]=m.position[1];positions[p+2]=m.position[2];const appMag=-1.1+m.normalizedRadius*5.8+m.sparsityFactor*1.7,rad=normalizedStellarRadiance(appMag,.22,.0012,4.6);sizes[i]=.45+Math.min(3.1,rad*.68)+(1-m.normalizedRadius)*.7;const hot=celestiaEnhancedTemperatureColor(spec.starK),cool=celestiaEnhancedTemperatureColor(Math.max(3600,spec.starK*.56)),t=m.sparsityFactor;colors[p]=hot[0]+(cool[0]-hot[0])*t;colors[p+1]=hot[1]+(cool[1]-hot[1])*t;colors[p+2]=hot[2]+(cool[2]-hot[2])*t;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(positions,3));g.setAttribute('aSize',new THREE.BufferAttribute(sizes,1));g.setAttribute('aColor',new THREE.BufferAttribute(colors,3));const mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,depthTest:false,blending:THREE.AdditiveBlending,uniforms:{uOpacity:{value:0},uTime:{value:0},uRotationSpeed:{value:cfg.rotationSpeed}},vertexShader:`attribute float aSize;attribute vec3 aColor;varying vec3 vColor;uniform float uTime,uRotationSpeed;void main(){vColor=aColor;vec3 p=position;float d=length(p.xz),a=-uRotationSpeed*uTime/(d*.1+1.0),c=cos(a),s=sin(a);vec3 q=vec3(p.x*c-p.z*s,p.y,p.x*s+p.z*c);vec4 mv=modelViewMatrix*vec4(q,1.0);gl_PointSize=aSize*clamp(128.0/max(7.0,-mv.z),.48,4.0);gl_Position=projectionMatrix*mv;}`,fragmentShader:`varying vec3 vColor;uniform float uOpacity;void main(){vec2 p=gl_PointCoord-.5;float d=length(p),core=smoothstep(.45,.03,d),halo=smoothstep(.51,.14,d);gl_FragColor=vec4(vColor,(core+halo*.17)*uOpacity);}`});const points=new THREE.Points(g,mat);points.frustumCulled=false;return{points,g,mat};}
export class DeepSpaceSectorSystem{
 constructor(){this.group=new THREE.Group();this.maxPresence=0;this.activeSectorCount=0;this.cloudReady=false;this.physicalPaletteReady=true;this.sectors=[];const mobile=/iPad|iPhone|iPod|Android/i.test(navigator.userAgent||'')||innerWidth<800,count=mobile?180:320;for(const spec of SECTORS){const group=new THREE.Group(),cluster=makeCluster(spec,count),cloudMat=new THREE.SpriteMaterial({transparent:true,opacity:0,depthWrite:false,depthTest:false,blending:THREE.NormalBlending,color:spec.color,toneMapped:true}),cloud=new THREE.Sprite(cloudMat);cloud.scale.set(106,68,1);cloud.renderOrder=-840;group.add(cloud,cluster.points);group.visible=false;this.group.add(group);this.sectors.push({spec,group,cluster,cloud,cloudMat});}getGalaxyCloudTexture().then(t=>{for(const s of this.sectors){s.cloudMat.map=t;s.cloudMat.needsUpdate=true;}this.cloudReady=true;}).catch(()=>{});}
 update(dt,state){const p=clamp(state.soulProgress||0),fade=1-clamp(state.finalFade||0);this.maxPresence=0;this.activeSectorCount=0;for(const s of this.sectors){const raw=(p-s.spec.start)/(s.spec.end-s.spec.start);if(raw<=0||raw>=1){s.group.visible=false;s.cluster.mat.uniforms.uOpacity.value=0;continue;}const env=smooth(raw/.12)*(1-smooth((raw-.93)/.07))*fade,a=1-Math.pow(1-clamp(raw),3.05);s.group.visible=env>.003;s.group.position.set(s.spec.x*(1-a*.72),s.spec.y*(1-a*.56),-224+a*252);s.group.scale.setScalar(.76+a*2.65);s.group.rotation.x=.14+Math.sin(s.spec.seed)*.08;s.group.rotation.z=.09*Math.sin(s.spec.seed*.71);s.cluster.mat.uniforms.uTime.value+=dt;s.cluster.mat.uniforms.uOpacity.value=Math.min(.68,env*(.18+a*.46));s.cloudMat.opacity=this.cloudReady?Math.min(.16,env*(.05+a*.11)):0;this.maxPresence=Math.max(this.maxPresence,env);this.activeSectorCount++;}}
 dispose(){for(const s of this.sectors){s.cluster.g.dispose();s.cluster.mat.dispose();s.cloudMat.dispose();}}
}
