import * as THREE from 'three';
import { TRUE_COLOR_PALETTES, rgbToHex, temperatureToSRGB } from '../space/ColorScience.js?v=20260812-1';
const clamp01=v=>Math.max(0,Math.min(1,v));
const smooth01=x=>{const t=clamp01(x);return t*t*(3-2*t);};
const hash=n=>{const x=Math.sin(n*12.9898+78.233)*43758.5453;return x-Math.floor(x);};
function makeCloudTexture(seed,dust=false){const size=256,canvas=document.createElement('canvas');canvas.width=canvas.height=size;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,size,size);ctx.globalCompositeOperation='source-over';for(let i=0;i<(dust?8:15);i++){const x=(.10+hash(seed+i*5.7)*.80)*size,y=(.10+hash(seed+i*7.9)*.80)*size,r=(.08+hash(seed+i*11.1)*.28)*size,g=ctx.createRadialGradient(x,y,r*.02,x,y,r);if(dust){g.addColorStop(0,'rgba(255,255,255,.44)');g.addColorStop(.45,'rgba(255,255,255,.24)');g.addColorStop(1,'rgba(255,255,255,0)');}else{g.addColorStop(0,'rgba(255,255,255,.72)');g.addColorStop(.24,'rgba(255,255,255,.34)');g.addColorStop(.62,'rgba(255,255,255,.10)');g.addColorStop(1,'rgba(255,255,255,0)');}ctx.fillStyle=g;ctx.fillRect(0,0,size,size);}if(!dust){ctx.globalCompositeOperation='lighter';ctx.lineCap='round';for(let i=0;i<22;i++){const x0=hash(seed+80+i*3.1)*size,y0=hash(seed+120+i*4.3)*size,x1=hash(seed+160+i*5.1)*size,y1=hash(seed+200+i*5.9)*size,cx1=(x0+x1)*.5+(hash(seed+240+i*6.7)-.5)*size*.56,cy1=(y0+y1)*.5+(hash(seed+280+i*7.1)-.5)*size*.56,cx2=(x0+x1)*.5+(hash(seed+320+i*7.7)-.5)*size*.56,cy2=(y0+y1)*.5+(hash(seed+360+i*8.3)-.5)*size*.56;ctx.beginPath();ctx.moveTo(x0,y0);ctx.bezierCurveTo(cx1,cy1,cx2,cy2,x1,y1);ctx.lineWidth=.45+hash(seed+i*9.1)*2.4;ctx.strokeStyle=`rgba(255,255,255,${.018+hash(seed+i*10.3)*.080})`;ctx.stroke();}ctx.globalCompositeOperation='destination-out';for(let i=0;i<5;i++){const x0=hash(seed+420+i*3.7)*size,y0=hash(seed+460+i*4.1)*size,x1=hash(seed+500+i*4.7)*size,y1=hash(seed+540+i*5.3)*size,cx=(x0+x1)*.5+(hash(seed+580+i*5.9)-.5)*size*.48,cy=(y0+y1)*.5+(hash(seed+620+i*6.3)-.5)*size*.48;ctx.beginPath();ctx.moveTo(x0,y0);ctx.quadraticCurveTo(cx,cy,x1,y1);ctx.lineWidth=9+hash(seed+i*6.9)*22;ctx.strokeStyle=`rgba(0,0,0,${.28+hash(seed+i*7.3)*.42})`;ctx.stroke();}}ctx.globalCompositeOperation='source-over';const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.generateMipmaps=false;texture.minFilter=THREE.LinearFilter;texture.magFilter=THREE.LinearFilter;return texture;}
const SECTORS=[
 {start:.06,end:.22,x:-10,y:4,seed:11,primary:TRUE_COLOR_PALETTES.ionizedBlue,secondary:TRUE_COLOR_PALETTES.hydrogenRose,starK:9500},
 {start:.26,end:.41,x:11,y:-4,seed:29,primary:TRUE_COLOR_PALETTES.oxygenTeal,secondary:TRUE_COLOR_PALETTES.amberDust,starK:7200},
 {start:.44,end:.58,x:-12,y:-2,seed:47,primary:TRUE_COLOR_PALETTES.hydrogenRose,secondary:TRUE_COLOR_PALETTES.ionizedBlue,starK:11000},
 {start:.56,end:.72,x:10,y:5,seed:73,primary:TRUE_COLOR_PALETTES.ionizedBlue,secondary:TRUE_COLOR_PALETTES.oxygenTeal,starK:8200},
 {start:.74,end:.90,x:-9,y:2,seed:101,primary:TRUE_COLOR_PALETTES.amberDust,secondary:TRUE_COLOR_PALETTES.hydrogenRose,starK:6100}
];
function makeStarCluster(seed,temperature){const count=110,positions=new Float32Array(count*3),sizes=new Float32Array(count);for(let i=0;i<count;i++){const a=hash(seed+i*2.1)*Math.PI*2,r=Math.pow(hash(seed+i*3.7),1.8)*16,z=(hash(seed+i*5.3)-.5)*28,p=i*3;positions[p]=Math.cos(a)*r;positions[p+1]=Math.sin(a)*r*.72;positions[p+2]=z;sizes[i]=.45+Math.pow(hash(seed+i*7.1),2.4)*2.4;}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.setAttribute('aSize',new THREE.BufferAttribute(sizes,1));const vertex=`attribute float aSize;void main(){vec4 mv=modelViewMatrix*vec4(position,1.0);gl_PointSize=aSize*clamp(110.0/max(8.0,-mv.z),.55,3.2);gl_Position=projectionMatrix*mv;}`;const fragment=`uniform vec3 uColor;uniform float uOpacity;void main(){float d=length(gl_PointCoord-vec2(.5));float core=smoothstep(.48,.03,d);float halo=smoothstep(.50,.18,d);gl_FragColor=vec4(uColor, (core+halo*.18)*uOpacity);}`;const material=new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:fragment,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uColor:{value:new THREE.Color(rgbToHex(temperatureToSRGB(temperature)))},uOpacity:{value:0}}});const points=new THREE.Points(geometry,material);points.frustumCulled=false;points.renderOrder=-820;return{points,geometry,material};}
export class DeepSpaceSectorSystem{
 constructor(){this.group=new THREE.Group();this.time=0;this.maxPresence=0;this.activeSectorCount=0;this.sectors=[];this.textures=[];for(const spec of SECTORS){const g=new THREE.Group(),layers=[];for(let i=0;i<7;i++){const texture=makeCloudTexture(spec.seed+i*17,false);this.textures.push(texture);const color=i%3===0?spec.secondary:spec.primary,material=new THREE.SpriteMaterial({map:texture,color:rgbToHex(color),transparent:true,opacity:0,depthWrite:false,depthTest:false,blending:i===0?THREE.AdditiveBlending:THREE.NormalBlending,toneMapped:i!==0}),sprite=new THREE.Sprite(material),angle=hash(spec.seed+i*9.7)*Math.PI*2,rr=3+hash(spec.seed+i*11.9)*12,width=14+hash(spec.seed+i*13.3)*22;sprite.position.set(Math.cos(angle)*rr,Math.sin(angle)*rr*.62,(hash(spec.seed+i*15.7)-.5)*26);sprite.scale.set(width,width*(.62+hash(spec.seed+i*18.1)*.38),1);sprite.material.rotation=hash(spec.seed+i*21.7)*Math.PI*2;sprite.renderOrder=i===0?-810:-850;g.add(sprite);layers.push({sprite,material,baseOpacity:i===0?.13:.18+hash(spec.seed+i*23.3)*.10,seed:spec.seed+i});}for(let i=0;i<3;i++){const texture=makeCloudTexture(spec.seed+200+i*31,true);this.textures.push(texture);const material=new THREE.SpriteMaterial({map:texture,color:0x010207,transparent:true,opacity:0,depthWrite:false,depthTest:false,blending:THREE.NormalBlending,toneMapped:false}),sprite=new THREE.Sprite(material),angle=hash(spec.seed+240+i*7.3)*Math.PI*2,rr=2+hash(spec.seed+260+i*8.9)*10,width=18+hash(spec.seed+280+i*10.1)*20;sprite.position.set(Math.cos(angle)*rr,Math.sin(angle)*rr*.58,(hash(spec.seed+300+i*11.3)-.5)*20);sprite.scale.set(width,width*(.55+hash(spec.seed+320+i*12.7)*.35),1);sprite.material.rotation=hash(spec.seed+340+i*13.9)*Math.PI*2;sprite.renderOrder=-825;g.add(sprite);layers.push({sprite,material,baseOpacity:.26+hash(spec.seed+360+i*15.1)*.12,seed:spec.seed+300+i,dust:true});}const cluster=makeStarCluster(spec.seed+500,spec.starK);g.add(cluster.points);g.visible=false;this.group.add(g);this.sectors.push({spec,group:g,layers,cluster});}}
 update(dt,state){this.time+=dt;const p=clamp01(state.soulProgress||0),finalFade=1-clamp01(state.finalFade||0),narrative=.62+clamp01(state.nebulaPresence||0)*.22+clamp01(state.galaxyReveal||0)*.16;this.maxPresence=0;this.activeSectorCount=0;for(const sector of this.sectors){const{spec,group,layers,cluster}=sector,raw=(p-spec.start)/(spec.end-spec.start);if(raw<=0||raw>=1){group.visible=false;cluster.material.uniforms.uOpacity.value=0;continue;}const fadeIn=smooth01(raw/.15),fadeOut=1-smooth01((raw-.78)/.22),envelope=clamp01(fadeIn*fadeOut)*finalFade,travel=smooth01(raw);this.maxPresence=Math.max(this.maxPresence,envelope);this.activeSectorCount++;group.visible=envelope>.006;group.position.set(spec.x*(1+travel*.74),spec.y*(1+travel*.42),-210+travel*206);group.rotation.z=Math.sin(this.time*.010+spec.seed)*.035;for(const layer of layers){const pulse=.96+Math.sin(this.time*.036+layer.seed)*.035,depthGain=.72+travel*.28,opacity=layer.baseOpacity*envelope*narrative*depthGain*pulse;layer.material.opacity=Math.min(layer.dust?.36:.30,opacity);layer.sprite.material.rotation+=dt*(layer.dust?.00016:.00032)*(layer.seed%2?-1:1);}cluster.material.uniforms.uOpacity.value=Math.min(.72,envelope*(.26+travel*.48));}}
 dispose(){for(const sector of this.sectors){for(const layer of sector.layers)layer.material.dispose();sector.cluster.geometry.dispose();sector.cluster.material.dispose();}for(const texture of this.textures)texture.dispose();}
}
