import * as THREE from 'three';

const clamp01=v=>Math.max(0,Math.min(1,v));
const smooth01=x=>{const t=clamp01(x);return t*t*(3-2*t);};
const gaussian=(x,c,w)=>Math.exp(-.5*Math.pow((x-c)/w,2));
const REFERENCES=[
  {url:'./assets/ethereal/angel-01.png?v=20260812-png6',width:28.0,center:.25,maxOpacity:.64,x:-1.35,y:.18,z:-24.5,phase:0.0},
  {url:'./assets/ethereal/angel-02.png?v=20260812-png6',width:26.0,center:.72,maxOpacity:.58,x:1.15,y:.08,z:-26.5,phase:14.0}
];
export class EtherealFiguresSystem{
  constructor(){this.group=new THREE.Group();this.layers=[];this.time=0;this.readyCount=0;this.loader=new THREE.TextureLoader();for(const ref of REFERENCES){const bodyMaterial=new THREE.SpriteMaterial({color:0xf4f8ff,transparent:true,opacity:0,depthWrite:false,depthTest:false,alphaTest:.0025,blending:THREE.NormalBlending,toneMapped:false});const glowMaterial=new THREE.SpriteMaterial({color:0xbfd8ff,transparent:true,opacity:0,depthWrite:false,depthTest:false,alphaTest:.001,blending:THREE.AdditiveBlending,toneMapped:false});const body=new THREE.Sprite(bodyMaterial),glow=new THREE.Sprite(glowMaterial);body.position.set(ref.x,ref.y,ref.z);glow.position.set(ref.x,ref.y,ref.z-.18);body.renderOrder=58;glow.renderOrder=57;this.group.add(glow,body);const layer={...ref,bodyMaterial,glowMaterial,body,glow,texture:null,aspect:1};this.layers.push(layer);this.loadReference(layer);}this.group.position.set(0,0,0);this.group.visible=false;}
  get maxOpacity(){return this.layers.reduce((m,l)=>Math.max(m,(l.bodyMaterial.opacity||0)+(l.glowMaterial.opacity||0)*.35),0);}
  loadReference(layer){this.loader.load(layer.url,texture=>{const image=texture.image;layer.aspect=image?.width&&image?.height?image.width/image.height:1;texture.colorSpace=THREE.SRGBColorSpace;texture.generateMipmaps=false;texture.minFilter=THREE.LinearFilter;texture.magFilter=THREE.LinearFilter;texture.premultiplyAlpha=true;layer.texture=texture;layer.bodyMaterial.map=texture;layer.glowMaterial.map=texture;layer.bodyMaterial.needsUpdate=true;layer.glowMaterial.needsUpdate=true;const h=layer.width/layer.aspect;layer.body.scale.set(layer.width,h,1);layer.glow.scale.set(layer.width*1.045,h*1.045,1);this.readyCount++;},undefined,error=>console.warn('URUX supplied transparent PNG could not be loaded',layer.url,error));}
  update(dt,state,features){this.time+=dt;const stage=state.journeyStage||'',living=clamp01(state.livingLight||0),ideal=clamp01(state.idealized||0),review=clamp01(state.lifeReview||0),boundary=clamp01(state.boundary||0),ret=clamp01(state.returnForce||0),finalFade=clamp01(state.finalFade||0),p=clamp01(state.soulProgress||0);const eligible=stage==='LIVING_LIGHT'||stage==='IDEALIZED_COSMOS'||stage==='LIFE_REVIEW';const progressGate=smooth01((p-.40)/.09)*(1-smooth01((p-.945)/.045));const stageFloor=eligible?.42:0;const presence=clamp01(Math.max(living,ideal,review,stageFloor))*progressGate*(1-boundary*.82)*(1-ret*.76)*(1-finalFade);const sequence=clamp01((p-.40)/.52);this.group.position.set(0,0,0);let total=0;const weights=this.layers.map(l=>{const w=gaussian(sequence,l.center,.43);total+=w;return w;});const norm=Math.max(.82,total*.68);for(let i=0;i<this.layers.length;i++){const l=this.layers[i],weight=weights[i]/norm,breathe=1+Math.sin(this.time*.16+i*1.71)*.012,eventT=(this.time+l.phase)%28,eventIn=smooth01((eventT-1.0)/3.5),eventOut=1-smooth01((eventT-14.5)/4.5),eventWindow=clamp01(eventIn*eventOut),baseWindow=.22+.78*eventWindow,audioLift=.98+(features?.mid||0)*.045,focus=.36+.64*weight,opacity=(l.texture?1:0)*presence*focus*l.maxOpacity*baseWindow*audioLift;l.body.position.set(l.x,l.y,l.z);l.glow.position.set(l.x,l.y,l.z-.18);const width=l.width*breathe,height=width/l.aspect;l.body.scale.set(width,height,1);l.glow.scale.set(width*1.045,height*1.045,1);l.bodyMaterial.opacity=opacity*.78;l.glowMaterial.opacity=opacity*.24;}this.group.visible=this.readyCount>0&&presence>.010;}
  dispose(){for(const l of this.layers){l.bodyMaterial.dispose();l.glowMaterial.dispose();l.texture?.dispose();}}
}
