import * as THREE from 'three';
const clamp01=v=>Math.max(0,Math.min(1,v));
const hash=n=>{const x=Math.sin(n*12.9898+78.233)*43758.5453;return x-Math.floor(x);};
function makeTexture(seed){const size=128,canvas=document.createElement('canvas');canvas.width=canvas.height=size;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,size,size);for(let i=0;i<11;i++){const x=(.16+hash(seed+i*7.1)*.68)*size,y=(.16+hash(seed+i*11.3)*.68)*size,r=(.17+hash(seed+i*17.9)*.31)*size,g=ctx.createRadialGradient(x,y,r*.035,x,y,r);g.addColorStop(0,'rgba(255,255,255,.60)');g.addColorStop(.30,'rgba(255,255,255,.34)');g.addColorStop(.68,'rgba(255,255,255,.12)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(0,0,size,size);}ctx.globalCompositeOperation='destination-out';for(let i=0;i<4;i++){const x=(.22+hash(seed+51+i*3.7)*.56)*size,y=(.22+hash(seed+73+i*4.3)*.56)*size,r=(.10+hash(seed+97+i*5.9)*.20)*size,g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,'rgba(0,0,0,.66)');g.addColorStop(.70,'rgba(0,0,0,.26)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,size,size);}ctx.globalCompositeOperation='source-over';const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.generateMipmaps=false;texture.minFilter=THREE.LinearFilter;texture.magFilter=THREE.LinearFilter;return texture;}
const CLUSTERS=[{x:10,y:7,z:-62,color:0x7898ff},{x:-14,y:-8,z:-78,color:0x7d58e6},{x:16,y:-13,z:-92,color:0xc56c3d},{x:-17,y:12,z:-101,color:0x537af0}];
export class GalacticWispSystem{
 constructor(count=36){this.group=new THREE.Group();this.group.position.set(0,0,0);this.time=0;this.layers=[];this.textures=[makeTexture(3),makeTexture(29),makeTexture(61)];for(let i=0;i<count;i++){const cluster=CLUSTERS[i%CLUSTERS.length],seed=i+1,angle=hash(seed*2.1)*Math.PI*2,rr=1.8+hash(seed*4.7)*8.8,dust=hash(seed*9.3)<.20,x=cluster.x+Math.cos(angle)*rr,y=cluster.y+Math.sin(angle)*rr*.58,z=cluster.z+(hash(seed*13.1)-.5)*13,width=14+hash(seed*5.2)*25,baseOpacity=dust?.082:.072+hash(seed*7.7)*.070,material=new THREE.SpriteMaterial({map:this.textures[i%this.textures.length],color:dust?0x01030a:cluster.color,transparent:true,opacity:0,depthWrite:false,depthTest:false,blending:dust?THREE.NormalBlending:THREE.AdditiveBlending,toneMapped:false}),sprite=new THREE.Sprite(material);sprite.position.set(x,y,z);sprite.scale.set(width,width*(.68+hash(seed*8.4)*.42),1);sprite.material.rotation=hash(seed*12.4)*Math.PI*2;sprite.renderOrder=-650;this.group.add(sprite);this.layers.push({sprite,material,x,y,z,width,baseOpacity,seed,dust});}this.group.visible=true;}
 get maxOpacity(){return this.layers.reduce((m,l)=>Math.max(m,l.material.opacity||0),0);}
 update(dt,state,features){this.time+=dt;const nebula=clamp01(state.nebulaPresence||0),reveal=clamp01(state.galaxyReveal||0),ideal=clamp01(state.idealized||0),review=clamp01(state.lifeReview||0),fade=1-clamp01(state.finalFade||0),presence=clamp01(.40+nebula*.28+(state.tunnelDrive||0)*.06+reveal*.34+ideal*.18+review*.10)*fade;for(const l of this.layers){const slow=l.dust?.00050:.00078,phase=l.seed*.73,scale=1+Math.sin(this.time*.045+phase)*.018,driftX=Math.sin(this.time*.018+phase)*.16,driftY=Math.cos(this.time*.015+phase*.7)*.12,audioLift=.96+(features?.mid||0)*.07;l.sprite.position.set(l.x+driftX,l.y+driftY,l.z);l.sprite.scale.set(l.width*scale,l.width*(.68+hash(l.seed*8.4)*.42)*scale,1);l.material.rotation+=dt*slow*(l.dust?-1:1);l.material.opacity=Math.min(.16,l.baseOpacity*presence*audioLift*(l.dust?.72:1));}this.group.visible=presence>.02;}
 dispose(){for(const l of this.layers)l.material.dispose();for(const t of this.textures)t.dispose();}
}
