import * as THREE from 'three';
import { runtimeCapabilities } from '../capabilities/RuntimeCapabilityRegistry.js';

const vertexShader=`varying vec3 vDir;void main(){vDir=normalize(position);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`;
const fragmentShader=`
precision highp float;
varying vec3 vDir;
uniform float uTime,uTravel,uVisibility,uTunnelDrive,uLivingLight,uGalaxyReveal,uFinalFade,uAudioHeartPulse,uHeartLightFade,uRaySteps,uLightSteps,uNarrativeBlend,uNarrativeDarkZone,uNarrativeFilaments,uDensityScale,uExtinction,uScattering,uPhaseG,uShadowStrength;
uniform vec2 uNarrativeCore;uniform vec3 uNarrativeColor0,uNarrativeColor1,uNarrativeColor2;
#define MAX_STEPS 24
#define MAX_LIGHT_STEPS 6
float h31(vec3 p){p=fract(p*.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}
vec3 h33(vec3 p){p=vec3(dot(p,vec3(127.1,311.7,74.7)),dot(p,vec3(269.5,183.3,246.1)),dot(p,vec3(113.5,271.9,124.6)));return fract(sin(p)*43758.5453123);}
float valueNoise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);float a=h31(i),b=h31(i+vec3(1,0,0)),c=h31(i+vec3(0,1,0)),d=h31(i+vec3(1,1,0)),e=h31(i+vec3(0,0,1)),g=h31(i+vec3(1,0,1)),h=h31(i+vec3(0,1,1)),j=h31(i+vec3(1,1,1));return mix(mix(mix(a,b,f.x),mix(c,d,f.x),f.y),mix(mix(e,g,f.x),mix(h,j,f.x),f.y),f.z);}
float worley3(vec3 p){vec3 ip=floor(p),fp=fract(p);float d=2.;for(int z=-1;z<=1;z++)for(int y=-1;y<=1;y++)for(int x=-1;x<=1;x++){vec3 o=vec3(float(x),float(y),float(z)),r=o+h33(ip+o)-fp;d=min(d,dot(r,r));}return sqrt(d);}
float fbm3(vec3 p){float v=0.,a=.54;mat3 m=mat3(.00,.80,.60,-.80,.36,-.48,-.60,-.48,.64);for(int i=0;i<4;i++){v+=valueNoise(p)*a;p=m*p*2.03+vec3(5.2,-3.7,2.4);a*=.48;}return v;}
float ridge(float v){return 1.-abs(v*2.-1.);}
float gauss(vec2 p,vec2 c,float k){vec2 q=p-c;return exp(-dot(q,q)*k);}
float hg(float c,float g){float g2=g*g,q=max(.035,1.+g2-2.*g*c);return (1.-g2)/(12.56637*pow(q,1.5));}
vec4 densityField(vec3 p){vec3 q=p+vec3(uTravel*.00032,uTime*.0023,-uTravel*.00048);float w0=fbm3(q*.19+vec3(3.1,5.7,-2.4)),w1=valueNoise(q*.34+vec3(-2.4,7.1,4.8)),w2=valueNoise(q*.29+vec3(8.3,-1.8,3.4));q+=vec3(w0-.5,w1-.5,w2-.5)*(1.25+.55*uNarrativeFilaments);float macro=fbm3(q*.30),mid=fbm3(q*.72+vec3(5.2,-2.7,1.9)),cell=1.-clamp(worley3(q*(.58+.12*uNarrativeFilaments)),0.,1.),fil=ridge(fbm3(q*(1.18+uNarrativeFilaments*.52)+8.3));float body=smoothstep(.42,.69,macro*.52+mid*.31+cell*.17),f=smoothstep(mix(.78,.53,uNarrativeFilaments),mix(.93,.70,uNarrativeFilaments),fil)*body,dust=smoothstep(.53,.79,fbm3(q*.93+vec3(-7.,3.,5.))*.72+cell*.28)*body,emit=smoothstep(.58,.84,mid*.56+f*.69)*body;float carve=1.-smoothstep(.60,.84,fbm3(q*.47+vec3(11.,-6.,2.)))*mix(.34,.82,uNarrativeDarkZone);float density=body*carve*(.70+.34*f)*uDensityScale;return vec4(max(0.,density),dust,emit,f);}
float shadowTransmittance(vec3 p,vec3 lightDir,float lightStep){float tau=0.;for(int j=0;j<MAX_LIGHT_STEPS;j++){if(float(j)>=uLightSteps)break;vec3 sp=p+lightDir*(float(j)+1.0)*lightStep;vec4 sf=densityField(sp);tau+=sf.x*(.72+sf.y*.92)*uExtinction*lightStep;}return exp(-tau*uShadowStrength);}
void main(){vec3 rd=normalize(vDir),lightDir=normalize(vec3(-.36,.25,-.90));float forward=smoothstep(.04,1.,-rd.z);vec2 screen=rd.xy/max(.32,abs(rd.z));float steps=max(8.,uRaySteps),stepSize=8.4/steps,lightStep=.58,t=.35+fract(sin(dot(gl_FragCoord.xy,vec2(12.9898,78.233))+uTime*3.1)*43758.5453)*stepSize*.65,trans=1.;vec3 accum=vec3(0.);vec3 cold=vec3(.012,.026,.074),midC=vec3(.10,.075,.16),warm=vec3(.44,.13,.035),c0=mix(cold,uNarrativeColor0,uNarrativeBlend*.66),c1=mix(midC,uNarrativeColor1,uNarrativeBlend*.66),c2=mix(warm,uNarrativeColor2,uNarrativeBlend*.52);float phase=hg(dot(rd,lightDir),uPhaseG),core=gauss(screen,uNarrativeCore,4.2)*uNarrativeBlend;
for(int i=0;i<MAX_STEPS;i++){if(float(i)>=steps)break;vec3 p=rd*t;vec4 f=densityField(p);float density=f.x*(.46+.28*uTunnelDrive+.20*uGalaxyReveal),dust=f.y*mix(.66,1.54,uNarrativeDarkZone),sigmaT=(density*(.76+dust*1.28))*uExtinction,alpha=1.-exp(-sigmaT*stepSize);if(alpha>.001){float shadow=shadowTransmittance(p,lightDir,lightStep);vec3 gas=mix(c0,c1,clamp(f.w*.76+f.z*.18,0.,1.));gas=mix(gas,c2,clamp(f.z*.70+core*.22,0.,1.));float singleScatter=density*uScattering*(.10+phase*1.65)*(1.-dust*.55)*shadow;vec3 emission=gas*f.z*(.18+.16*shadow)+vec3(.98,.92,.84)*f.z*f.z*.045;accum+=(emission+gas*singleScatter)*trans*alpha;trans*=1.-alpha;}if(trans<.035)break;t+=stepSize;}
float pocket=smoothstep(.61,.84,fbm3(vec3(screen*1.12,uTime*.0011)+vec3(3.,-2.,6.)))*mix(.13,.52,uNarrativeDarkZone);accum*=1.-pocket;accum*=forward;float r=length(rd.xy),living=uLivingLight;accum+=vec3(.75,.86,1.)*exp(-r*r*5.4)*living*.022+vec3(1.,.97,.91)*exp(-r*r*31.)*living*living*.20;float fetal=clamp(uHeartLightFade,0.,1.),pulse=clamp(uAudioHeartPulse,0.,1.);accum+=vec3(1.,.96,.90)*exp(-r*r*mix(38.,26.,pulse))*fetal*(.11+pulse*.16);accum*=uVisibility;accum=mix(accum,vec3(0.),uFinalFade*(1.-fetal*.9));gl_FragColor=vec4(accum,1.);}`;

export class NebulaBackdrop{
 constructor(){this.travel=0;this.avgDt=1/60;this.qualityClock=0;const mobile=/iPad|iPhone|Android/i.test(navigator.userAgent||'')||innerWidth<800;this.mobile=mobile;this.baseSteps=mobile?12:22;this.minSteps=mobile?9:15;this.baseLightSteps=mobile?3:6;this.minLightSteps=mobile?2:4;this.geometry=new THREE.SphereGeometry(220,mobile?32:48,mobile?20:30);this.material=new THREE.ShaderMaterial({vertexShader,fragmentShader,side:THREE.BackSide,depthWrite:false,depthTest:false,transparent:false,uniforms:{uTime:{value:0},uTravel:{value:0},uVisibility:{value:.15},uTunnelDrive:{value:0},uLivingLight:{value:0},uGalaxyReveal:{value:0},uFinalFade:{value:0},uAudioHeartPulse:{value:0},uHeartLightFade:{value:0},uRaySteps:{value:this.baseSteps},uLightSteps:{value:this.baseLightSteps},uDensityScale:{value:1.0},uExtinction:{value:.92},uScattering:{value:.34},uPhaseG:{value:.38},uShadowStrength:{value:.78},uNarrativeBlend:{value:0},uNarrativeDarkZone:{value:.6},uNarrativeFilaments:{value:.3},uNarrativeCore:{value:new THREE.Vector2(0,0)},uNarrativeColor0:{value:new THREE.Color('#0d1b4b')},uNarrativeColor1:{value:new THREE.Color('#4b3f64')},uNarrativeColor2:{value:new THREE.Color('#b66d32')}}});this.mesh=new THREE.Mesh(this.geometry,this.material);this.mesh.frustumCulled=false;this.mesh.renderOrder=-1000;runtimeCapabilities.mark('shader-noise',true,{gpu:true,noise:['3D value noise','Worley 3D','FBM 3D','ridge'],textureIndependent:true});runtimeCapabilities.mark('volumetric-raymarch',true,{densityField:'3D procedural',extinction:'Beer-Lambert',scattering:'Henyey-Greenstein single scattering',selfShadowing:true,maxPrimarySteps:24,maxLightSteps:6,adaptive:true});}
 get visibility(){return this.material.uniforms.uVisibility.value||0;}
 get raySteps(){return this.material.uniforms.uRaySteps.value||0;}
 get lightSteps(){return this.material.uniforms.uLightSteps.value||0;}
 update(dt,state,features){this.travel+=Math.max(0,state.speed)*dt;this.avgDt=this.avgDt*.94+dt*.06;this.qualityClock+=dt;const u=this.material.uniforms;u.uTime.value+=dt;u.uTravel.value=this.travel;if(this.qualityClock>1){this.qualityClock=0;const stressed=this.avgDt>.027,warm=this.avgDt>.021;u.uRaySteps.value=stressed?this.minSteps:(warm?Math.max(this.minSteps,this.baseSteps-3):this.baseSteps);u.uLightSteps.value=stressed?this.minLightSteps:(warm?Math.max(this.minLightSteps,this.baseLightSteps-1):this.baseLightSteps);}const tunnel=state.tunnelDrive||0,reveal=state.galaxyReveal||0,light=state.livingLight||0,nebula=state.nebulaPresence||0,energy=features.energy||0,mid=features.mid||0;u.uVisibility.value=Math.min(.235,.10+nebula*.055+tunnel*.025+reveal*.047+light*.015+mid*.007);u.uTunnelDrive.value=tunnel;u.uLivingLight.value=light;u.uGalaxyReveal.value=reveal;u.uFinalFade.value=state.finalFade||0;u.uAudioHeartPulse.value=state.audioHeartPulse||0;u.uHeartLightFade.value=state.heartLightFade||0;u.uDensityScale.value=.90+nebula*.22+tunnel*.09+energy*.035;u.uExtinction.value=.84+(state.dustDensity||0)*.18;u.uScattering.value=.30+reveal*.08+light*.05;u.uPhaseG.value=.34+tunnel*.07;u.uShadowStrength.value=.72+(state.dustDensity||0)*.16;}
 dispose(){this.geometry.dispose();this.material.dispose();}
}
