import * as THREE from 'three';
import { StreakController } from './StreakController.js?v=20260812-7';
import { DepthLayerManager } from './DepthLayerManager.js?v=20260812-core2';
const clamp01=v=>Math.max(0,Math.min(1,v));
const smooth01=x=>{const t=clamp01(x);return t*t*(3-2*t);};
const pointVertex=`attribute float aSize;attribute float aAlpha;attribute float aSeed;varying float vAlpha;varying float vSeed;void main(){vec4 mv=modelViewMatrix*vec4(position,1.0);float perspective=clamp(120.0/max(4.0,-mv.z),0.45,5.0);gl_PointSize=aSize*perspective;vAlpha=aAlpha;vSeed=aSeed;gl_Position=projectionMatrix*mv;}`;
const pointFragment=`varying float vAlpha;varying float vSeed;uniform float uShimmer;uniform float uPulse;vec3 stellarColor(float seed){float t=fract(seed*13.731);vec3 hotBlue=vec3(.68,.80,1.00),blueWhite=vec3(.84,.90,1.00),neutralWhite=vec3(.98,.965,.92),ivory=vec3(1.00,.89,.73);if(t<.16)return hotBlue;if(t<.58)return blueWhite;if(t<.94)return neutralWhite;return ivory;}void main(){vec2 p=gl_PointCoord-vec2(.5);float d=length(p);float core=smoothstep(.44,.015,d),inner=smoothstep(.50,.08,d),halo=smoothstep(.55,.14,d);float magnitude=pow(1.0-fract(vSeed*7.913),2.4);float peak=.70+magnitude*.82+uShimmer*.10+uPulse*.14;float softPeak=peak/(1.0+peak*.22);float glowGate=.26+.74*sqrt(magnitude);float alpha=min(.90,(core+inner*.28+halo*.24*glowGate)*vAlpha*(1.0+uPulse*.10));vec3 c=stellarColor(vSeed);gl_FragColor=vec4(c*softPeak,alpha);}`;
const lineVertex=`attribute float aAlpha;varying float vAlpha;void main(){vAlpha=aAlpha;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`;
const lineFragment=`varying float vAlpha;uniform float uIntensity;void main(){vec3 c=mix(vec3(.19,.38,.72),vec3(.82,.91,1.0),clamp(vAlpha*1.15,0.0,1.0));gl_FragColor=vec4(c*uIntensity,vAlpha*.82);}`;
export class StarTunnelSystem{
  constructor(maxStars=1400){this.maxStars=maxStars;this.activeCount=maxStars;this.group=new THREE.Group();this.group.frustumCulled=false;this.streakController=new StreakController();this.depthLayer=new DepthLayerManager();this.depth=130;this.pulse=0;this.previousBass=0;this.flightAge=0;this.breathTime=0;this.stars=new Array(maxStars);this.pointPositions=new Float32Array(maxStars*3);this.pointSizes=new Float32Array(maxStars);this.pointAlpha=new Float32Array(maxStars);this.pointSeeds=new Float32Array(maxStars);this.linePositions=new Float32Array(maxStars*6);this.lineAlpha=new Float32Array(maxStars*2);this.pointGeometry=new THREE.BufferGeometry();this.pointGeometry.setAttribute('position',new THREE.BufferAttribute(this.pointPositions,3));this.pointGeometry.setAttribute('aSize',new THREE.BufferAttribute(this.pointSizes,1));this.pointGeometry.setAttribute('aAlpha',new THREE.BufferAttribute(this.pointAlpha,1));this.pointGeometry.setAttribute('aSeed',new THREE.BufferAttribute(this.pointSeeds,1));this.pointMaterial=new THREE.ShaderMaterial({vertexShader:pointVertex,fragmentShader:pointFragment,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,uniforms:{uShimmer:{value:.10},uPulse:{value:0}}});this.points=new THREE.Points(this.pointGeometry,this.pointMaterial);this.points.frustumCulled=false;this.lineGeometry=new THREE.BufferGeometry();this.lineGeometry.setAttribute('position',new THREE.BufferAttribute(this.linePositions,3));this.lineGeometry.setAttribute('aAlpha',new THREE.BufferAttribute(this.lineAlpha,1));this.lineMaterial=new THREE.ShaderMaterial({vertexShader:lineVertex,fragmentShader:lineFragment,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,uniforms:{uIntensity:{value:.50}}});this.lines=new THREE.LineSegments(this.lineGeometry,this.lineMaterial);this.lines.frustumCulled=false;this.group.add(this.lines,this.points);for(let i=0;i<maxStars;i++)this.recycle(i,true);this.writeBuffers({speed:10,streakLength:1.2,warpIntensity:.3,shimmer:.1,starDensity:.72},0);}
  get pulseLevel(){return this.pulse;}
  randomStar(depth){const theta=Math.random()*Math.PI*2,radius=this.depthLayer.sampleRadius(Math.random());return{x:Math.cos(theta)*radius,y:Math.sin(theta)*radius*(.88+Math.random()*.24),z:this.depthLayer.sampleDepth(Math.random(),depth),speedFactor:.82+Math.random()*.36,size:.72+Math.random()*1.30,seed:Math.random()};}
  recycle(i,initial=false){const s=this.randomStar(this.depth);if(!initial)s.z=-this.depth-Math.random()*22;this.stars[i]=s;this.pointSeeds[i]=s.seed;}
  setActiveCount(count){const requested=Number.isFinite(count)?Math.floor(count):this.maxStars;this.activeCount=Math.max(1,Math.min(this.maxStars,requested));this.pointGeometry.setDrawRange(0,this.activeCount);this.lineGeometry.setDrawRange(0,this.activeCount*2);}
  update(dt,state,features){this.depth=state.tunnelDepth;this.flightAge+=dt;this.breathTime+=dt;const startup=.06+.94*smooth01(this.flightAge/3);const forward=state.speed*startup;this.group.position.set(0,0,0);const compression=1-(state.compression||0)*.07,breath=1+Math.sin((this.breathTime/4)*Math.PI*2)*.006;this.group.scale.set(compression*breath,compression*breath,1);const bassRise=Math.max(0,features.bass-this.previousBass);this.previousBass=features.bass;const lift=Math.max(0,features.shortTermEnergy-features.mediumTermEnergy);const audioTrigger=clamp01(features.transient*1.25+bassRise*7+lift*3.5+features.spectralFlux*.42);const heartbeatStage=!state.heartStopped&&(state.journeyStage==='DETACHMENT'||state.journeyStage==='DARK_TUNNEL');const residual=audioTrigger*.018;const pulseTarget=heartbeatStage?Math.max((state.heartPulse||0)*.72,residual):residual*.25;const response=pulseTarget>this.pulse?13:4.5;this.pulse+=(pulseTarget-this.pulse)*(1-Math.exp(-response*dt));this.pointMaterial.uniforms.uShimmer.value=Math.min(.24,(state.shimmer||0)*.58+(state.lifeReview||0)*.035);this.pointMaterial.uniforms.uPulse.value=this.pulse;const lineFade=1-(state.travelFade||0),nebulaRelief=Math.max(.46,1-(state.galaxyReveal||0)*.34-(state.livingLight||0)*.16-(state.idealized||0)*.10);this.lineMaterial.uniforms.uIntensity.value=Math.min(.60,(.28+state.warpIntensity*.34+features.high*.045+this.pulse*.045)*(.18+.82*lineFade)*nebulaRelief);for(let i=0;i<this.activeCount;i++){const s=this.stars[i];s.z+=forward*s.speedFactor*dt;if(s.z>-1.15)this.recycle(i,false);}this.writeBuffers(state,features.high);}
  writeBuffers(state,highEnergy){const depth=Math.max(95,this.depth),finalFade=state.finalFade||0,density=clamp01(state.starDensity||.72);for(let i=0;i<this.activeCount;i++){const s=this.stars[i],depth01=clamp01((-s.z)/depth),p=i*3,pulseWeight=.55+(1-depth01)*.45,hero=s.seed<.20,mid=s.seed>=.20&&s.seed<.65,sizeMul=hero?2.45:(mid?1.38:.72),trailMul=hero?1.85:(mid?1.10:.52),alphaMul=hero?1.15:(mid?.92:.60);this.pointPositions[p]=s.x;this.pointPositions[p+1]=s.y;this.pointPositions[p+2]=s.z;this.pointSizes[i]=s.size*sizeMul*(.66+state.warpIntensity*.20+highEnergy*.07)*(1+this.pulse*.24*pulseWeight)*(1-finalFade*.72);this.pointAlpha[i]=Math.min(.86,(.10+(1-depth01)*.42+s.seed*.07)*(.62+.38*density)*(1+this.pulse*.08)*(1-finalFade*.96)*alphaMul);const lp=i*6,length=this.streakController.getWorldLength(state,depth01)*trailMul,alpha=Math.min(.78,this.streakController.getAlpha(state,depth01,s.seed)*.78*alphaMul);this.linePositions[lp]=s.x;this.linePositions[lp+1]=s.y;this.linePositions[lp+2]=s.z;this.linePositions[lp+3]=s.x;this.linePositions[lp+4]=s.y;this.linePositions[lp+5]=s.z-length;this.lineAlpha[i*2]=alpha;this.lineAlpha[i*2+1]=alpha*.018;}this.pointGeometry.attributes.position.needsUpdate=true;this.pointGeometry.attributes.aSize.needsUpdate=true;this.pointGeometry.attributes.aAlpha.needsUpdate=true;this.lineGeometry.attributes.position.needsUpdate=true;this.lineGeometry.attributes.aAlpha.needsUpdate=true;}
  dispose(){this.pointGeometry.dispose();this.lineGeometry.dispose();this.pointMaterial.dispose();this.lineMaterial.dispose();}
}
