import * as THREE from 'three';
import { StarTunnelSystem } from './StarTunnelSystem.js?v=20260812-19';
import { NebulaBackdrop } from './NebulaBackdrop.js?v=20260813-1';
import { DeepSpaceSectorSystem } from './DeepSpaceSectorSystem.js?v=20260812-5';
import { GalacticWispSystem } from './GalacticWispSystem.js?v=20260812-3';
const dustVertex=`attribute float aSize;varying float vFade;void main(){vec4 mv=modelViewMatrix*vec4(position,1.0);vFade=clamp(1.0-(-mv.z/140.0),0.0,1.0);gl_PointSize=aSize*clamp(90.0/max(5.0,-mv.z),0.3,2.1);gl_Position=projectionMatrix*mv;}`;
const dustFragment=`varying float vFade;uniform float uOpacity;void main(){float d=length(gl_PointCoord-vec2(.5));float a=smoothstep(.5,.10,d)*uOpacity*(.20+vFade*.80);gl_FragColor=vec4(vec3(.18,.32,.62),a);}`;
export class WarpFieldManager{
 constructor(maxStars){this.group=new THREE.Group();this.nebula=new NebulaBackdrop();this.deepSpace=new DeepSpaceSectorSystem();this.galacticWisps=new GalacticWispSystem(maxStars<=1200?28:36);this.starTunnel=new StarTunnelSystem(maxStars);this.group.add(this.nebula.mesh);this.group.add(this.deepSpace.group);this.group.add(this.galacticWisps.group);this.group.add(this.starTunnel.group);const dustCount=Math.max(140,Math.floor(maxStars*.075));this.dustPositions=new Float32Array(dustCount*3);this.dustSpeeds=new Float32Array(dustCount);this.dustCount=dustCount;for(let i=0;i<dustCount;i++)this.resetDust(i,true);this.dustGeometry=new THREE.BufferGeometry();this.dustGeometry.setAttribute('position',new THREE.BufferAttribute(this.dustPositions,3));const sizes=new Float32Array(dustCount);for(let i=0;i<dustCount;i++)sizes[i]=.5+Math.random()*.9;this.dustGeometry.setAttribute('aSize',new THREE.BufferAttribute(sizes,1));this.dustMaterial=new THREE.ShaderMaterial({vertexShader:dustVertex,fragmentShader:dustFragment,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,uniforms:{uOpacity:{value:.034}}});this.dust=new THREE.Points(this.dustGeometry,this.dustMaterial);this.dust.frustumCulled=false;this.group.add(this.dust);}
 resetDust(i,initial=false){const theta=Math.random()*Math.PI*2,r=5+Math.random()*34,p=i*3;this.dustPositions[p]=Math.cos(theta)*r;this.dustPositions[p+1]=Math.sin(theta)*r;this.dustPositions[p+2]=initial?-10-Math.random()*130:-140-Math.random()*20;this.dustSpeeds[i]=.46+Math.random()*.40;}
 update(dt,state,features){this.deepSpace.update(dt,state);for(const sector of this.deepSpace.sectors||[]){for(const layer of sector.layers||[]){layer.material.opacity*=layer.dust?.62:.38;}if(sector.cluster?.material?.uniforms?.uOpacity)sector.cluster.material.uniforms.uOpacity.value*=.88;}const sector=this.deepSpace.maxPresence||0;state.spaceSectorPresence=sector;this.nebula.update(dt,state,features);const volumetric=this.nebula.material.uniforms.uVisibility;volumetric.value=Math.min(.28,volumetric.value*(.68-.18*sector));this.galacticWisps.update(dt,state,features);this.starTunnel.update(dt,state,features);if(sector>.01){const pointRelief=.28+.72*(1-sector*.72),lineRelief=.18+.82*(1-sector*.82);for(let i=0;i<this.starTunnel.activeCount;i++){this.starTunnel.pointAlpha[i]*=pointRelief;this.starTunnel.lineAlpha[i*2]*=lineRelief;this.starTunnel.lineAlpha[i*2+1]*=lineRelief;}this.starTunnel.pointGeometry.attributes.aAlpha.needsUpdate=true;this.starTunnel.lineGeometry.attributes.aAlpha.needsUpdate=true;this.starTunnel.lineMaterial.uniforms.uIntensity.value*=.28+.72*(1-sector*.78);}const fade=1-(state.finalFade||0),light=state.livingLight||0,reveal=state.galaxyReveal||0;this.dustMaterial.uniforms.uOpacity.value=Math.min(.028,(.003+state.dustDensity*.014)*(1-light*.48)*(1-reveal*.24)*(1-sector*.48)*fade);const speed=state.speed*.50;for(let i=0;i<this.dustCount;i++){const p=i*3;this.dustPositions[p+2]+=speed*this.dustSpeeds[i]*dt;if(this.dustPositions[p+2]>-1.5)this.resetDust(i,false);}this.dustGeometry.attributes.position.needsUpdate=true;}
 dispose(){this.nebula.dispose();this.deepSpace.dispose();this.galacticWisps.dispose();this.starTunnel.dispose();this.dustGeometry.dispose();this.dustMaterial.dispose();}
}
