import { runtimeCapabilities } from '../capabilities/RuntimeCapabilityRegistry.js';

const BASE='./assets/astronomy/';
const MANIFEST_URL=`${BASE}manifest.json`;
async function fetchJson(url,required=false){try{const r=await fetch(`${url}${url.includes('?')?'&':'?'}t=${Date.now()}`,{cache:'no-store'});if(!r.ok){if(required)throw new Error(`${url}_http_${r.status}`);return null;}return await r.json();}catch(error){if(required)throw error;return null;}}

export class ScientificAstronomyRuntime{
  constructor(){this.manifest=null;this.gaia=null;this.horizons=null;this.eso=null;this.nist=null;this.celestiaManifest=null;this.celestiaStatic=null;this.celestiaContent=null;this.celestiaSimulation=null;this.ready=false;this.failed=false;this.stats={ready:false,pending:true,stars:0,bodies:0,gaia:false,horizons:false,eso:false,skyview:false,wcs:false,reproject:false,aplpy:false,spectralCube:false,trueColorSpectra:false,celestiaBuild:false,celestiaStatic:false,celestiaSimulation:false,lastError:null};this.readyPromise=this.load();}
  async load(){
    try{
      const [manifest,celestiaManifest,celestiaStaticData,celestiaContent,celestiaSimulation]=await Promise.all([
        fetchJson(MANIFEST_URL,true),fetchJson(`${BASE}celestia-native-manifest.json`),fetchJson(`${BASE}celestia-static-runtime.json`),fetchJson(`${BASE}celestia-content-index.json`),fetchJson(`${BASE}celestia-simulation.json`)
      ]);
      this.manifest=manifest;this.celestiaManifest=celestiaManifest;this.celestiaStatic=celestiaStaticData;this.celestiaContent=celestiaContent;this.celestiaSimulation=celestiaSimulation;
      const caps=this.manifest?.capabilities||{};
      if(caps['astroquery.gaia'])this.gaia=await fetchJson(`${BASE}gaia-dr3.json`);
      if(caps['astroquery.jplhorizons'])this.horizons=await fetchJson(`${BASE}jpl-earth-vector.json`);
      if(caps['astroquery.eso'])this.eso=await fetchJson(`${BASE}eso-archive.json`);
      if(caps['astroquery.nist'])this.nist=await fetchJson(`${BASE}nist-visible-emission-lines.json`);
      const generated=Boolean(this.manifest?.generatedAt&&!this.manifest?.pendingPipeline),gaia=Boolean(caps['astroquery.gaia']&&this.gaia?.records?.length),horizons=Boolean(caps['astroquery.jplhorizons']&&this.horizons?.records?.length),eso=Boolean(caps['astroquery.eso']&&this.eso),skyview=Boolean(caps['astroquery.skyview']),wcs=Boolean(caps['astropy.wcsaxes']&&caps['astropy.visualization']),reprojection=Boolean(caps['reproject.interp']&&caps['reproject.adaptive']&&caps['reproject.exact']),aplpyReady=Boolean(caps.aplpy),spectral=Boolean(caps['spectral-cube']),trueColorSpectra=Boolean(caps['truecolor.spectralSource']&&this.nist?.records?.length);
      const celestiaBuild=Boolean(celestiaManifest?.nativeBuildVerified&&celestiaManifest?.sidecarBinaryVerified),celestiaSimulationReady=Boolean(celestiaBuild&&celestiaManifest?.simulationInitialized&&this.celestiaSimulation?.simulationInitialized&&this.celestiaSimulation?.catalogCounts?.stars>1000&&this.celestiaSimulation?.catalogCounts?.deepSky>0&&this.celestiaSimulation?.catalogCounts?.solarSystems>0),celestiaStaticReady=Boolean(celestiaSimulationReady&&celestiaManifest?.staticRuntimeActive&&this.celestiaStatic?.native&&this.celestiaStatic?.photometryLut?.length&&this.celestiaStatic?.anomalyLut?.length&&this.celestiaContent?.rootTreeFingerprint);
      this.ready=true;this.stats={ready:true,pending:!generated,stars:this.gaia?.records?.length||0,bodies:this.horizons?.records?.length||0,gaia,horizons,eso,skyview,wcs,reproject:reprojection,aplpy:aplpyReady,spectralCube:spectral,trueColorSpectra,celestiaBuild,celestiaStatic:celestiaStaticReady,celestiaSimulation:celestiaSimulationReady,lastError:null};
      runtimeCapabilities.mark('astropy-stack',generated,{libraries:this.manifest?.libraries||{},generatedAt:this.manifest?.generatedAt||null,provenance:this.manifest?.provenance||[]});runtimeCapabilities.mark('astroquery',Boolean(caps['astroquery.simbad']||gaia||horizons||skyview||eso||caps['astroquery.nist']),{simbad:Boolean(caps['astroquery.simbad']),gaia,horizons,skyview,eso,nist:Boolean(caps['astroquery.nist'])});runtimeCapabilities.mark('gaia-catalog',gaia,{count:this.stats.stars,source:'ESA Gaia DR3'});runtimeCapabilities.mark('nasa-jpl-catalog',horizons,{count:this.stats.bodies,source:'NASA/JPL Horizons'});runtimeCapabilities.mark('eso-catalog',eso,{count:this.eso?.records?.length||0,instruments:this.eso?.availableInstruments?.length||0,source:'ESO Science Archive'});runtimeCapabilities.mark('wcs-science',wcs,{wcsAxes:Boolean(caps['astropy.wcsaxes']),visualization:Boolean(caps['astropy.visualization'])});runtimeCapabilities.mark('reproject',reprojection,{interp:Boolean(caps['reproject.interp']),adaptive:Boolean(caps['reproject.adaptive']),exact:Boolean(caps['reproject.exact'])});runtimeCapabilities.mark('aplpy',aplpyReady,{source:'generated FITS visualization'});runtimeCapabilities.mark('spectral-cube',spectral,{source:'observational FITS cube + moment maps'});runtimeCapabilities.mark('truecolor-spectra',trueColorSpectra,{source:'NIST Atomic Spectra via astroquery.nist',records:this.nist?.records?.length||0});runtimeCapabilities.mark('celestia-native-build',celestiaBuild,{compiledSubsystems:celestiaManifest?.compiledSubsystems||[],sourceRef:celestiaManifest?.sourceRef||null});runtimeCapabilities.mark('celestia-static-runtime',celestiaStaticReady,{execution:celestiaStaticReady?'GitHub Actions native precompute':null,delivery:'GitHub Pages static JSON',usage:this.celestiaStatic?.usage||null,simulation:celestiaSimulationReady?this.celestiaSimulation?.catalogCounts:null,content:this.celestiaContent?.resourceFamilies||null});runtimeCapabilities.mark('celestia-literal',celestiaStaticReady,{mode:'literal CelestiaCore + Simulation + Universe precomputed in GitHub Actions',compiledSubsystems:celestiaManifest?.compiledSubsystems||[],executedHighLevelAPIs:celestiaManifest?.executedHighLevelAPIs||[],catalogCounts:this.celestiaSimulation?.catalogCounts||null,objectsFound:this.celestiaSimulation?.objectsFound||0,usage:this.celestiaStatic?.usage||null,content:this.celestiaContent?.resourceFamilies||null,renderLoop:false,costModel:'no permanent Celestia server'});return true;
    }catch(error){this.failed=true;this.stats.lastError=String(error);runtimeCapabilities.mark('astropy-stack',false,{error:String(error)});runtimeCapabilities.mark('celestia-literal',false,{error:String(error)});return false;}
  }
  stars(limit=256){return(this.gaia?.records||[]).slice(0,limit);}bodies(){return this.horizons?.records||[];}body(name){const n=String(name||'').toLowerCase();return this.bodies().find(b=>String(b.targetname||b.name||'').toLowerCase().includes(n))||null;}emissionLines(limit=512){return(this.nist?.records||[]).slice(0,limit);}get epoch(){return this.horizons?.epochTDB||this.manifest?.generatedAt||null;}snapshot(){return{...this.stats,epoch:this.epoch,libraries:this.manifest?.libraries||{},capabilities:this.manifest?.capabilities||{},provenance:this.manifest?.provenance||[],celestia:{manifest:this.celestiaManifest,staticRuntime:this.celestiaStatic,simulation:this.celestiaSimulation,content:this.celestiaContent},eso:this.eso?{records:this.eso.records?.length||0,instruments:this.eso.availableInstruments?.length||0}:null,nistLines:this.nist?.records?.length||0};}
}

export const scientificAstronomy=new ScientificAstronomyRuntime();
