export class AIStatusOverlay{
  constructor(getDiagnostics){
    this.getDiagnostics=getDiagnostics;this.expanded=false;this.lastRender=0;this.root=document.createElement('div');this.root.id='urux-ai-status';Object.assign(this.root.style,{position:'fixed',top:'max(14px, env(safe-area-inset-top))',right:'12px',zIndex:'9999',fontFamily:'ui-monospace,SFMono-Regular,Menlo,monospace',fontSize:'11px',lineHeight:'1.35',color:'#eef5ff',background:'rgba(3,7,18,.66)',border:'1px solid rgba(180,210,255,.18)',borderRadius:'14px',backdropFilter:'blur(10px)',WebkitBackdropFilter:'blur(10px)',boxShadow:'0 8px 30px rgba(0,0,0,.28)',maxWidth:'84vw',userSelect:'none',WebkitUserSelect:'none'});this.button=document.createElement('button');this.button.type='button';this.button.setAttribute('aria-label','Estado IA URUX');Object.assign(this.button.style,{appearance:'none',border:'0',background:'transparent',color:'inherit',padding:'8px 10px',font:'inherit',display:'flex',alignItems:'center',gap:'7px',cursor:'pointer'});this.dot=document.createElement('span');Object.assign(this.dot.style,{width:'7px',height:'7px',borderRadius:'50%',background:'#777',boxShadow:'0 0 10px rgba(255,255,255,.18)',flex:'0 0 auto'});this.label=document.createElement('span');this.label.textContent='IA';this.button.append(this.dot,this.label);this.panel=document.createElement('div');Object.assign(this.panel.style,{display:'none',padding:'0 10px 10px',minWidth:'225px',whiteSpace:'normal',wordBreak:'break-word'});this.root.append(this.button,this.panel);document.body.appendChild(this.root);this.button.addEventListener('click',()=>{this.expanded=!this.expanded;this.panel.style.display=this.expanded?'block':'none';this.render(true);});
  }
  bool(v){return v?'sí':'no';}
  decisionText(d){const c=d.cinematic||{},n=d.nebulaDirective||{};if(!d.llmActive)return 'Aún sin decisiones LLM aceptadas.';const type=c.lastType||d.lastEncounterType||'encounter',parts=[`seleccionó ${type}`];if(n.active)parts.push('actualizó densidad/filamentos/paleta de nebulosa');if(d.stage)parts.push(`adaptó la escena a ${d.stage}`);return parts.join(' · ')+'.';}
  agentText(d){const c=d.cinematic||{},n=d.nebulaDirective||{},parts=[];if((c.llmSpawned||0)>0){parts.push('ejecutó trayectoria 3D');parts.push('aplicó aproximación al punto focal');parts.push('ajustó escala, velocidad, luminosidad y presencia visual');}if(n.active)parts.push('interpoló la nebulosa sin bloquear el render');if(!parts.length)parts.push('mantiene fallback procedural mientras espera al LLM');return parts.join(' · ')+'.';}
  render(force=false){const now=performance.now();if(!force&&now-this.lastRender<800)return;this.lastRender=now;let d={};try{d=this.getDiagnostics?.()||{};}catch{}const active=Boolean(d.llmActive),configured=Boolean(d.backendConfigured),status=d.backendStatus??'—';this.dot.style.background=active?'#78ffa8':configured?'#ffd36b':'#ff7373';this.dot.style.boxShadow=active?'0 0 12px rgba(120,255,168,.8)':configured?'0 0 12px rgba(255,211,107,.65)':'0 0 12px rgba(255,115,115,.65)';this.label.textContent=active?'IA activa':configured?'IA conectada':'IA offline';if(!this.expanded)return;const c=d.cinematic||{},n=d.nebulaDirective||{},err=d.backendError?String(d.backendError).replace(/^Error:\s*/,''):'';const usage=d.openrouterUsage==null?'—':String(d.openrouterUsage);const keyState=d.openrouterKeyOk==null?'—':(d.openrouterKeyOk?'OK':'ERROR');this.panel.innerHTML=`<div style="opacity:.72;margin-bottom:5px">URUX Journey Director</div><div>Worker: <b>${configured?'OK':'NO'}</b> · HTTP ${status} · v${d.workerVersion||'—'}</div><div>OpenRouter key: <b>${keyState}</b> · Uso: ${usage}</div><div>LLM: <b>${active?'ACTIVO':(d.backendRequestState||'esperando')}</b></div><div>Intentos: ${d.backendRequestAttempts??0} · Inicio: ${d.startState||'—'}</div><div>Modelo: <span style="opacity:.9">${d.model||'—'}</span>${d.modelMode?` · ${d.modelMode}`:''}</div><div>Etapa: ${d.stage||'—'}</div><div>Batches IA: ${d.acceptedBatches??0}</div><div>Último: ${c.lastType||d.lastEncounterType||'—'} <span style="opacity:.6">${c.lastSource||''}</span></div><div>Encounter IA: ${c.llmSpawned??0}</div><div>Nebulosa IA: ${this.bool(Boolean(n.active))}</div>${err?`<div style="margin-top:6px;color:#ffb4b4"><b>Error:</b> ${err.slice(0,300)}</div>`:''}<div style="margin-top:7px;padding-top:6px;border-top:1px solid rgba(180,210,255,.12)"><b>IA decidió</b><br><span style="opacity:.78">${this.decisionText(d)}</span></div><div style="margin-top:6px"><b>Agente aplicó</b><br><span style="opacity:.78">${this.agentText(d)}</span></div><div style="opacity:.55;margin-top:7px">Toca “IA” para cerrar</div>`;}
  update(){this.render(false);}
}
