import * as THREE from 'three';

const clamp01=v=>Math.max(0,Math.min(1,v));
const STAGE_PALETTES={
 DESPRENDIMIENTO:['#07152d','#17265e','#8fb7ff'],TUNEL:['#0d1b4b','#4b0082','#c35cff'],LUZ:['#6a0572','#d946a8','#ffffff'],MEMORIA:['#37206f','#a23885','#ffb25c'],FRONTERA:['#18244b','#6d3b7e','#ffd08a'],RETORNO:['#183d6d','#8c5f9e','#fff4d6']
};
const STAGE_TYPES={DESPRENDIMIENTO:['debris','void_pulse','light_filament'],TUNEL:['debris','comet','light_filament','void_pulse'],LUZ:['light_filament','planet','comet'],MEMORIA:['planet','vessel','light_filament','debris'],FRONTERA:['void_pulse','vessel','light_filament'],RETORNO:['comet','debris','light_filament','planet']};

function glowTexture(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.18,'rgba(255,255,255,.72)');g.addColorStop(.5,'rgba(255,255,255,.18)');g.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=g;x.fillRect(0,0,128,128);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}

export class CinematicEncounterSystem{
 constructor(scene){this.scene=scene;this.group=new THREE.Group();this.group.renderOrder=-120;scene.add(this.group);this.active=[];this.clock=0;this.nextAt=3.5;this.seq=0;this.glow=glowTexture();this.stage='DESPRENDIMIENTO';this.maxActive=3;this.stats={active:0,spawned:0,lastType:null};}
 setStage(stage){if(stage&&stage!==this.stage){this.stage=stage;this.nextAt=Math.min(this.nextAt,this.clock+1.5);}}
 update(dt){this.clock+=dt;for(let i=this.active.length-1;i>=0;i--){const a=this.active[i];a.age+=dt;const t=clamp01(a.age/a.duration),ease=t*t*(3-2*t),speed=a.speed*(.65+ease*.85);a.root.position.addScaledVector(a.velocity,speed*dt);a.root.rotation.y+=dt*a.spinY;a.root.rotation.z+=dt*a.spinZ;a.root.position.x+=Math.sin(a.age*.33+a.phase)*dt*.035;if(a.update)a.update(dt,t);const fadeIn=clamp01(t/.12),fadeOut=1-clamp01((t-.78)/.22),opacity=fadeIn*fadeOut;this.setOpacity(a.root,opacity);if(t>=1||a.root.position.z>10){this.group.remove(a.root);this.disposeRoot(a.root);this.active.splice(i,1);}}
 if(this.clock>=this.nextAt&&this.active.length<this.maxActive)this.spawnProcedural();this.stats.active=this.active.length;}
 spawnProcedural(){const types=STAGE_TYPES[this.stage]||STAGE_TYPES.DESPRENDIMIENTO,palette=STAGE_PALETTES[this.stage]||STAGE_PALETTES.DESPRENDIMIENTO;this.seq++;const phase=this.seq*1.61803398875,type=types[this.seq%types.length],root=this.create(type,palette,phase),x=Math.sin(phase*1.71)*8.2,y=Math.cos(phase*1.13)*4.8,z=-125-Math.abs(Math.sin(phase*.47))*35;root.position.set(x,y,z);const velocity=new THREE.Vector3(-x*.0035,-y*.0025,1).normalize(),speed=8.5+Math.abs(Math.cos(phase))*7.5,duration=10+Math.abs(Math.sin(phase*.77))*8;this.group.add(root);this.active.push({root,age:0,duration,velocity,speed,spinY:.025+Math.abs(Math.sin(phase))*.07,spinZ:(Math.sin(phase*.8))*.035,phase});this.nextAt=this.clock+6.5+Math.abs(Math.cos(phase*.52))*5.5;this.stats.spawned++;this.stats.lastType=type;}
 create(type,palette,phase){if(type==='planet')return this.planet(palette,phase);if(type==='comet')return this.comet(palette,phase);if(type==='void_pulse')return this.voidPulse(palette,phase);if(type==='light_filament')return this.filament(palette,phase);if(type==='vessel')return this.vessel(palette,phase);return this.debris(palette,phase);}
 planet(p,phase){const root=new THREE.Group(),geo=new THREE.IcosahedronGeometry(2.2,5),mat=new THREE.MeshStandardMaterial({color:new THREE.Color(p[0]),roughness:.78,metalness:.04,emissive:new THREE.Color(p[1]),emissiveIntensity:.08});const planet=new THREE.Mesh(geo,mat);root.add(planet);const atmGeo=new THREE.SphereGeometry(2.34,48,32),atm=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.BackSide,blending:THREE.AdditiveBlending,uniforms:{uColor:{value:new THREE.Color(p[2]||'#ffffff')},uStrength:{value:.55}},vertexShader:'varying vec3 vN;varying vec3 vW;void main(){vN=normalize(normalMatrix*normal);vec4 w=modelMatrix*vec4(position,1.0);vW=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}',fragmentShader:'varying vec3 vN;varying vec3 vW;uniform vec3 uColor;uniform float uStrength;void main(){vec3 V=normalize(cameraPosition-vW);float rim=pow(1.0-max(dot(normalize(vN),V),0.0),3.0);gl_FragColor=vec4(uColor,rim*uStrength);}' });root.add(new THREE.Mesh(atmGeo,atm));const ring=new THREE.Mesh(new THREE.RingGeometry(2.8,4.5,96),new THREE.MeshBasicMaterial({color:new THREE.Color(p[1]),transparent:true,opacity:.08,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));ring.rotation.x=Math.PI*.47;ring.rotation.z=phase*.4;root.add(ring);return root;}
 comet(p,phase){const root=new THREE.Group(),nucleus=new THREE.Mesh(new THREE.IcosahedronGeometry(.55,2),new THREE.MeshStandardMaterial({color:0x151820,roughness:.8,emissive:new THREE.Color(p[2]||'#ffffff'),emissiveIntensity:.8}));root.add(nucleus);for(let i=0;i<5;i++){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:this.glow,color:new THREE.Color(i%2?p[1]:p[2]||'#ffffff'),transparent:true,opacity:.16-i*.018,depthWrite:false,blending:THREE.AdditiveBlending}));s.position.set(0,0,-1.6-i*1.8);s.scale.set(2.4+i*1.0,1.1+i*.45,1);root.add(s);}root.rotation.z=phase;return root;}
 voidPulse(p,phase){const root=new THREE.Group();for(let i=0;i<3;i++){const tor=new THREE.Mesh(new THREE.TorusGeometry(1.8+i*.7,.055+i*.012,10,96),new THREE.MeshBasicMaterial({color:new THREE.Color(p[(i+1)%p.length]),transparent:true,opacity:.12-i*.02,depthWrite:false,blending:THREE.AdditiveBlending}));tor.rotation.x=Math.PI/2+i*.18;tor.rotation.z=phase+i*.7;root.add(tor);}const s=new THREE.Sprite(new THREE.SpriteMaterial({map:this.glow,color:new THREE.Color(p[1]),transparent:true,opacity:.10,depthWrite:false,blending:THREE.AdditiveBlending}));s.scale.set(7,7,1);root.add(s);return root;}
 filament(p,phase){const root=new THREE.Group();for(let j=0;j<3;j++){const pts=[];for(let i=0;i<18;i++){const z=-5+i*.6,x=Math.sin(i*.43+phase+j)*(.25+j*.10),y=Math.cos(i*.31+phase*.7+j)*(.18+j*.08);pts.push(new THREE.Vector3(x,y,z));}const curve=new THREE.CatmullRomCurve3(pts),tube=new THREE.Mesh(new THREE.TubeGeometry(curve,72,.035+j*.018,6,false),new THREE.MeshBasicMaterial({color:new THREE.Color(p[(j+1)%p.length]),transparent:true,opacity:.14-j*.018,depthWrite:false,blending:THREE.AdditiveBlending}));root.add(tube);}root.rotation.x=Math.PI/2;return root;}
 vessel(p,phase){const root=new THREE.Group(),body=new THREE.Mesh(new THREE.OctahedronGeometry(1.4,1),new THREE.MeshStandardMaterial({color:new THREE.Color('#11141d'),metalness:.8,roughness:.28,emissive:new THREE.Color(p[1]),emissiveIntensity:.18}));body.scale.set(1,.45,2.2);root.add(body);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(body.geometry),new THREE.LineBasicMaterial({color:new THREE.Color(p[2]||'#ffffff'),transparent:true,opacity:.22,blending:THREE.AdditiveBlending}));edges.scale.copy(body.scale);root.add(edges);for(const sx of[-1,1]){const light=new THREE.Sprite(new THREE.SpriteMaterial({map:this.glow,color:new THREE.Color(p[1]),transparent:true,opacity:.18,depthWrite:false,blending:THREE.AdditiveBlending}));light.position.set(sx*.9,0,-1.7);light.scale.set(1.1,1.1,1);root.add(light);}root.rotation.y=phase;return root;}
 debris(p,phase){const root=new THREE.Group();for(let i=0;i<7;i++){const g=new THREE.TetrahedronGeometry(.28+((i*37)%5)*.09,0),m=new THREE.MeshStandardMaterial({color:new THREE.Color(i%2?p[0]:p[1]),roughness:.82,metalness:.12,emissive:new THREE.Color(p[1]),emissiveIntensity:.05}),mesh=new THREE.Mesh(g,m);mesh.position.set(Math.sin(phase+i*1.7)*1.6,Math.cos(phase*.7+i)*1.0,(i-3)*.8);mesh.rotation.set(i*.7,phase+i*.4,i*.3);root.add(mesh);}return root;}
 setOpacity(root,k){root.traverse(o=>{const m=o.material;if(!m)return;const list=Array.isArray(m)?m:[m];for(const x of list){if(!x.userData.baseOpacity)x.userData.baseOpacity=x.opacity??1;if(x.transparent)x.opacity=x.userData.baseOpacity*k;}});}
 disposeRoot(root){root.traverse(o=>{o.geometry?.dispose?.();const m=o.material;if(Array.isArray(m))m.forEach(x=>x.dispose?.());else m?.dispose?.();});}
 dispose(){this.active.forEach(a=>this.disposeRoot(a.root));this.active=[];this.scene.remove(this.group);this.glow.dispose();}
}
