import * as THREE from 'three';
const clamp01=v=>Math.max(0,Math.min(1,v)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const STAGE_PALETTES={DESPRENDIMIENTO:['#07152d','#17265e','#8fb7ff'],TUNEL:['#050817','#17265e','#7b8fff'],LUZ:['#39235f','#8b6acb','#fff4dc'],MEMORIA:['#251b46','#725283','#e6a56f'],FRONTERA:['#0b1730','#344c78','#d5b482'],RETORNO:['#122c4c','#58718e','#f1e4c8']};
const STAGE_TYPES={DESPRENDIMIENTO:['debris','light_filament'],TUNEL:['comet','light_filament','debris'],LUZ:['light_filament','planet','comet'],MEMORIA:['planet','light_filament','debris'],FRONTERA:['light_filament','comet'],RETORNO:['comet','debris','light_filament','planet']};
function glowTexture(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.15,'rgba(255,255,255,.5)');g.addColorStop(.5,'rgba(255,255,255,.09)');g.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=g;x.fillRect(0,0,128,128);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function cloudTexture(){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.clearRect(0,0,256,256);for(let i=0;i<70;i++){const px=128+(Math.random()-.5)*125,py=128+(Math.random()-.5)*100,r=12+Math.random()*50,g=x.createRadialGradient(px,py,0,px,py,r);g.addColorStop(0,`rgba(255,255,255,${.025+Math.random()*.07})`);g.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=g;x.fillRect(px-r,py-r,r*2,r*2);}return new THREE.CanvasTexture(c);}
export class CinematicEncounterSystem{
 constructor(scene){this.scene=scene;this.group=new THREE.Group();scene.add(this.group);this.active=[];this.clock=0;this.nextAt=4;this.seq=0;this.glow=glowTexture();this.cloud=cloudTexture();this.stage='DESPRENDIMIENTO';this.maxActive=2;this.stats={active:0,spawned:0,llmSpawned:0,proceduralSpawned:0,lastType:null,lastSource:null,lastId:null};}
 setStage(stage){if(stage&&stage!==this.stage){this.stage=stage;this.nextAt=Math.min(this.nextAt,this.clock+2);}}
 update(dt){this.clock+=dt;for(let i=this.active.length-1;i>=0;i--){const a=this.active[i];a.age+=dt;const t=clamp01(a.age/a.duration),ease=t*t*(3-2*t);a.root.position.addScaledVector(a.velocity,a.speed*(.62+ease*.9)*dt);a.root.rotation.y+=dt*a.spinY;a.root.rotation.z+=dt*a.spinZ;if(a.update)a.update(dt,t);const opacity=clamp01(t/.16)*(1-clamp01((t-.76)/.24));this.setOpacity(a.root,opacity*a.luminosityFactor);if(t>=1||a.root.position.z>12){this.group.remove(a.root);this.disposeRoot(a.root);this.active.splice(i,1);}}if(this.clock>=this.nextAt&&this.active.length<this.maxActive)this.spawnProcedural();this.stats.active=this.active.length;}
 spawnEncounter(e,meta={source:'llm'}){if(!e||this.active.length>=this.maxActive)return false;const palette=Array.isArray(e.palette)&&e.palette.length?e.palette:(STAGE_PALETTES[e.narrativeStage]||STAGE_PALETTES[this.stage]),phase=(this.seq+1)*1.618,root=this.create(e.objectType,palette,phase);this.seq++;const sx=clamp(Number(e.spawnPosition?.x)||0,-1.5,1.5),sy=clamp(Number(e.spawnPosition?.y)||0,-1.5,1.5),z=-150;root.position.set(sx*11,sy*7,z);root.scale.setScalar(clamp(Number(e.scale)||1,.35,4));const raw=new THREE.Vector3(Number(e.trajectoryVector?.x)||0,Number(e.trajectoryVector?.y)||0,Math.abs(Number(e.trajectoryVector?.z)||1));if(e.focalApproach){raw.x-=sx*.14;raw.y-=sy*.1;}const velocity=raw.normalize(),speed=clamp(Number(e.speed)||.8,.15,4)*11,duration=clamp(Number(e.durationSeconds)||14,5,45),luminosityFactor=clamp(.45+(Number(e.luminosity)||.6)*.35,.35,1.35);this.group.add(root);this.active.push({root,age:0,duration,velocity,speed,spinY:.005+Math.abs(Math.sin(phase))*.018,spinZ:Math.sin(phase)*.008,luminosityFactor});this.nextAt=this.clock+Math.max(7,duration*.5);this.stats.spawned++;this.stats.llmSpawned+=meta.source==='llm'?1:0;this.stats.proceduralSpawned+=meta.source==='procedural'?1:0;this.stats.lastType=e.objectType;this.stats.lastSource=meta.source||'external';this.stats.lastId=e.id||null;return true;}
 spawnProcedural(){const types=STAGE_TYPES[this.stage]||STAGE_TYPES.DESPRENDIMIENTO,palette=STAGE_PALETTES[this.stage]||STAGE_PALETTES.DESPRENDIMIENTO;this.seq++;const phase=this.seq*1.618,type=types[this.seq%types.length],x=Math.sin(phase*1.71)*.8,y=Math.cos(phase*1.13)*.55;this.spawnEncounter({id:`cosmic-${this.seq}`,narrativeStage:this.stage,objectType:type,spawnPosition:{x,y},focalApproach:true,trajectoryVector:{x:-x*.04,y:-y*.03,z:1},scale:.8+Math.abs(Math.sin(phase))*.7,speed:.5+Math.abs(Math.cos(phase))*.45,palette,luminosity:.3+Math.abs(Math.sin(phase*.44))*.35,durationSeconds:14+Math.abs(Math.sin(phase))*7},{source:'procedural'});this.nextAt=this.clock+9+Math.abs(Math.cos(phase))*6;}
 create(type,p,phase){if(type==='planet')return this.planet(p,phase);if(type==='comet')return this.comet(p,phase);if(type==='light_filament')return this.filament(p,phase);if(type==='debris')return this.debris(p,phase);return this.filament(p,phase);}
 planet(p,phase){const root=new THREE.Group(),geo=new THREE.SphereGeometry(2.3,64,48),mat=new THREE.MeshStandardMaterial({color:new THREE.Color(p[0]),roughness:.9,metalness:0,emissive:new THREE.Color(p[1]||p[0]),emissiveIntensity:.025});root.add(new THREE.Mesh(geo,mat));const atm=new THREE.Sprite(new THREE.SpriteMaterial({map:this.glow,color:new THREE.Color(p[2]||'#d9e7ff'),transparent:true,opacity:.09,depthWrite:false,blending:THREE.AdditiveBlending}));atm.scale.set(6.1,6.1,1);root.add(atm);return root;}
 comet(p,phase){const root=new THREE.Group();const nucleus=new THREE.Mesh(new THREE.IcosahedronGeometry(.48,3),new THREE.MeshStandardMaterial({color:0x15171b,roughness:.98,emissive:new THREE.Color('#d9e8ff'),emissiveIntensity:.12}));root.add(nucleus);const coma=new THREE.Sprite(new THREE.SpriteMaterial({map:this.glow,color:new THREE.Color('#e8f2ff'),transparent:true,opacity:.28,depthWrite:false,blending:THREE.AdditiveBlending}));coma.scale.set(2.6,2.6,1);root.add(coma);for(let i=0;i<14;i++){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:this.cloud,color:new THREE.Color(i%3===0?(p[1]||'#7894c8'):'#c9d8ef'),transparent:true,opacity:.045*(1-i/16),depthWrite:false,blending:THREE.AdditiveBlending}));const d=1.1+i*.7;s.position.set(-d*.13+Math.sin(i*2.1)*.15,Math.cos(i*1.4)*.12,-d);s.scale.set(1.4+i*.38,.75+i*.2,1);root.add(s);}return root;}
 filament(p,phase){const root=new THREE.Group();for(let j=0;j<9;j++){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:this.cloud,color:new THREE.Color(p[(j+1)%p.length]||p[0]),transparent:true,opacity:.025+Math.random()*.025,depthWrite:false,blending:THREE.AdditiveBlending}));s.position.set(Math.sin(phase+j*.8)*1.8,Math.cos(phase*.7+j)*1.2,(j-4)*1.1);s.scale.set(4.5+Math.random()*3,2.2+Math.random()*2,1);root.add(s);}return root;}
 debris(p,phase){const root=new THREE.Group();for(let i=0;i<18;i++){const g=new THREE.IcosahedronGeometry(.07+Math.random()*.16,1),m=new THREE.MeshStandardMaterial({color:new THREE.Color('#454a55'),roughness:1,metalness:.05,emissive:new THREE.Color(p[1]||p[0]),emissiveIntensity:.01}),mesh=new THREE.Mesh(g,m);mesh.position.set((Math.random()-.5)*4,(Math.random()-.5)*2.7,(Math.random()-.5)*6);mesh.rotation.set(Math.random()*3,Math.random()*3,Math.random()*3);root.add(mesh);}return root;}
 setOpacity(root,k){root.traverse(o=>{const m=o.material;if(!m)return;for(const x of(Array.isArray(m)?m:[m])){if(x.userData.baseOpacity===undefined)x.userData.baseOpacity=x.opacity??1;if(x.transparent)x.opacity=x.userData.baseOpacity*k;}});}
 disposeRoot(root){root.traverse(o=>{o.geometry?.dispose?.();const m=o.material;if(Array.isArray(m))m.forEach(x=>x.dispose?.());else m?.dispose?.();});}
 dispose(){this.active.forEach(a=>this.disposeRoot(a.root));this.active=[];this.scene.remove(this.group);this.glow.dispose();this.cloud.dispose();}
}
