import * as THREE from 'three';
const clamp01=v=>Math.max(0,Math.min(1,v)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const STAGE_PALETTES={DESPRENDIMIENTO:['#07152d','#17265e','#8fb7ff'],TUNEL:['#050817','#17265e','#7b8fff'],LUZ:['#39235f','#8b6acb','#fff4dc'],MEMORIA:['#251b46','#725283','#e6a56f'],FRONTERA:['#0b1730','#344c78','#d5b482'],RETORNO:['#122c4c','#58718e','#f1e4c8']};
const STAGE_TYPES={DESPRENDIMIENTO:['comet','debris','light_filament'],TUNEL:['comet','planet','light_filament'],LUZ:['planet','comet','light_filament'],MEMORIA:['planet','comet','debris'],FRONTERA:['comet','light_filament','planet'],RETORNO:['planet','comet','debris']};
function glowTexture(){const c=document.createElement('canvas');c.width=c.height=96;const x=c.getContext('2d'),g=x.createRadialGradient(48,48,0,48,48,48);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.14,'rgba(255,255,255,.46)');g.addColorStop(.48,'rgba(255,255,255,.08)');g.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=g;x.fillRect(0,0,96,96);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function cloudTexture(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');for(let i=0;i<34;i++){const px=64+(Math.random()-.5)*68,py=64+(Math.random()-.5)*58,r=8+Math.random()*25,g=x.createRadialGradient(px,py,0,px,py,r);g.addColorStop(0,`rgba(255,255,255,${.025+Math.random()*.055})`);g.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=g;x.fillRect(px-r,py-r,r*2,r*2);}return new THREE.CanvasTexture(c);}
export class CinematicEncounterSystem{
 constructor(scene){this.scene=scene;this.group=new THREE.Group();this.group.renderOrder=80;scene.add(this.group);this.active=[];this.clock=0;this.nextAt=2.5;this.seq=0;this.glow=glowTexture();this.cloud=cloudTexture();this.stage='DESPRENDIMIENTO';this.maxActive=2;this.keyLight=new THREE.DirectionalLight(0xffffff,.85);this.keyLight.position.set(4,3,2);scene.add(this.keyLight);this.fillLight=new THREE.AmbientLight(0x466080,.16);scene.add(this.fillLight);this.stats={active:0,spawned:0,llmSpawned:0,proceduralSpawned:0,lastType:null,lastSource:null,lastId:null};}
 setStage(stage){if(stage&&stage!==this.stage){this.stage=stage;this.nextAt=Math.min(this.nextAt,this.clock+1.2);}}
 update(dt){this.clock+=dt;for(let i=this.active.length-1;i>=0;i--){const a=this.active[i];a.age+=dt;const t=clamp01(a.age/a.duration),ease=t*t*(3-2*t);a.root.position.addScaledVector(a.velocity,a.speed*(.72+ease*.95)*dt);a.root.rotation.y+=dt*a.spinY;a.root.rotation.z+=dt*a.spinZ;const opacity=clamp01(t/.12)*(1-clamp01((t-.82)/.18));this.setOpacity(a.root,opacity*a.luminosityFactor);if(t>=1||a.root.position.z>15){this.group.remove(a.root);this.disposeRoot(a.root);this.active.splice(i,1);}}if(this.clock>=this.nextAt&&this.active.length<this.maxActive)this.spawnProcedural();this.stats.active=this.active.length;}
 spawnEncounter(e,meta={source:'llm'}){if(!e||this.active.length>=this.maxActive)return false;const palette=Array.isArray(e.palette)&&e.palette.length?e.palette:(STAGE_PALETTES[e.narrativeStage]||STAGE_PALETTES[this.stage]),phase=(this.seq+1)*1.618,root=this.create(e.objectType,palette,phase);this.seq++;const sx=clamp(Number(e.spawnPosition?.x)||0,-1.5,1.5),sy=clamp(Number(e.spawnPosition?.y)||0,-1.5,1.5),z=-112;root.position.set(sx*9.2,sy*5.6,z);const baseScale=e.objectType==='planet'?1.45:e.objectType==='comet'?1.2:1;root.scale.setScalar(clamp((Number(e.scale)||1)*baseScale,.45,4.5));const raw=new THREE.Vector3(Number(e.trajectoryVector?.x)||0,Number(e.trajectoryVector?.y)||0,Math.abs(Number(e.trajectoryVector?.z)||1));if(e.focalApproach){raw.x-=sx*.12;raw.y-=sy*.08;}const velocity=raw.normalize(),speed=clamp(Number(e.speed)||.8,.25,4)*15,duration=clamp(Number(e.durationSeconds)||12,7,30),luminosityFactor=clamp(.62+(Number(e.luminosity)||.6)*.34,.5,1.35);this.group.add(root);this.active.push({root,age:0,duration,velocity,speed,spinY:.004+Math.abs(Math.sin(phase))*.013,spinZ:Math.sin(phase)*.006,luminosityFactor});this.nextAt=this.clock+Math.max(4.5,Math.min(7.5,duration*.34));this.stats.spawned++;this.stats.llmSpawned+=meta.source==='llm'?1:0;this.stats.proceduralSpawned+=meta.source==='procedural'?1:0;this.stats.lastType=e.objectType;this.stats.lastSource=meta.source||'external';this.stats.lastId=e.id||null;return true;}
 spawnProcedural(){const types=STAGE_TYPES[this.stage]||STAGE_TYPES.DESPRENDIMIENTO,palette=STAGE_PALETTES[this.stage]||STAGE_PALETTES.DESPRENDIMIENTO;this.seq++;const phase=this.seq*1.618,type=types[(this.seq-1)%types.length],x=Math.sin(phase*1.71)*.72,y=Math.cos(phase*1.13)*.46;this.spawnEncounter({id:`cosmic-${this.seq}`,narrativeStage:this.stage,objectType:type,spawnPosition:{x,y},focalApproach:true,trajectoryVector:{x:-x*.035,y:-y*.026,z:1},scale:type==='planet'?1.25:1,speed:.72+Math.abs(Math.cos(phase))*.34,palette,luminosity:.46+Math.abs(Math.sin(phase*.44))*.28,durationSeconds:10+Math.abs(Math.sin(phase))*5},{source:'procedural'});this.nextAt=this.clock+5+Math.abs(Math.cos(phase))*2.5;}
 create(type,p,phase){if(type==='planet')return this.planet(p);if(type==='comet')return this.comet(p);if(type==='light_filament')return this.filament(p,phase);return this.debris(p);}
 planet(p){const root=new THREE.Group(),geo=new THREE.SphereGeometry(2.35,32,24),mat=new THREE.MeshStandardMaterial({color:new THREE.Color(p[0]),roughness:.94,metalness:0,emissive:new THREE.Color(p[1]||p[0]),emissiveIntensity:.018});root.add(new THREE.Mesh(geo,mat));const atm=new THREE.Sprite(new THREE.SpriteMaterial({map:this.glow,color:new THREE.Color(p[2]||'#dbe8ff'),transparent:true,opacity:.075,depthWrite:false,blending:THREE.AdditiveBlending}));atm.scale.set(6.2,6.2,1);root.add(atm);return root;}
 comet(p){const root=new THREE.Group(),nucleus=new THREE.Mesh(new THREE.IcosahedronGeometry(.5,2),new THREE.MeshStandardMaterial({color:0x17191e,roughness:1,emissive:new THREE.Color('#dceaff'),emissiveIntensity:.07}));root.add(nucleus);const coma=new THREE.Sprite(new THREE.SpriteMaterial({map:this.glow,color:new THREE.Color('#edf5ff'),transparent:true,opacity:.23,depthWrite:false,blending:THREE.AdditiveBlending}));coma.scale.set(2.5,2.5,1);root.add(coma);for(let i=0;i<8;i++){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:this.cloud,color:new THREE.Color(i%3===0?(p[1]||'#7894c8'):'#cbd8eb'),transparent:true,opacity:.038*(1-i/10),depthWrite:false,blending:THREE.AdditiveBlending}));const d=1+i*.85;s.position.set(-d*.11+Math.sin(i*1.9)*.10,Math.cos(i*1.3)*.08,-d);s.scale.set(1.25+i*.42,.64+i*.18,1);root.add(s);}return root;}
 filament(p,phase){const root=new THREE.Group();for(let j=0;j<5;j++){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:this.cloud,color:new THREE.Color(p[(j+1)%p.length]||p[0]),transparent:true,opacity:.018+Math.random()*.016,depthWrite:false,blending:THREE.AdditiveBlending}));s.position.set(Math.sin(phase+j*.9)*1.4,Math.cos(phase*.7+j)*.9,(j-2)*1.35);s.scale.set(4.2+Math.random()*2.2,2+Math.random()*1.2,1);root.add(s);}return root;}
 debris(){const root=new THREE.Group();for(let i=0;i<8;i++){const g=new THREE.IcosahedronGeometry(.08+Math.random()*.13,0),m=new THREE.MeshStandardMaterial({color:0x464b54,roughness:1,metalness:.03}),mesh=new THREE.Mesh(g,m);mesh.position.set((Math.random()-.5)*3.6,(Math.random()-.5)*2.4,(Math.random()-.5)*5);root.add(mesh);}return root;}
 setOpacity(root,k){root.traverse(o=>{const m=o.material;if(!m)return;for(const x of(Array.isArray(m)?m:[m])){if(x.userData.baseOpacity===undefined)x.userData.baseOpacity=x.opacity??1;if(x.transparent)x.opacity=x.userData.baseOpacity*k;}});}
 disposeRoot(root){root.traverse(o=>{o.geometry?.dispose?.();const m=o.material;if(Array.isArray(m))m.forEach(x=>x.dispose?.());else m?.dispose?.();});}
 dispose(){this.active.forEach(a=>this.disposeRoot(a.root));this.active=[];this.scene.remove(this.group);this.scene.remove(this.keyLight);this.scene.remove(this.fillLight);this.glow.dispose();this.cloud.dispose();}
}
