import * as THREE from 'three';
import { CinematicEncounterSystem as Base } from './CinematicEncounterSystemV55.js?v=20260814-55';

const clamp01=v=>Math.max(0,Math.min(1,v));
const smooth01=v=>{const t=clamp01(v);return t*t*(3-2*t);};
const hash=n=>{const x=Math.sin(n*91.733+17.113)*43758.5453;return x-Math.floor(x);};
const PLANET_VARIANTS=[
 {id:'amber-giant',tint:0xd0a56e,emissive:0x21140b,atmosphere:0xf0c795,roughness:.84},
 {id:'cobalt-giant',tint:0x729fd0,emissive:0x08162b,atmosphere:0x9fd5ff,roughness:.80},
 {id:'ice-world',tint:0xb9d4e4,emissive:0x0a1d2b,atmosphere:0xd8efff,roughness:.69},
 {id:'rose-giant',tint:0xb97979,emissive:0x261013,atmosphere:0xeab1c1,roughness:.86},
 {id:'copper-world',tint:0xb66f4c,emissive:0x291008,atmosphere:0xe5a378,roughness:.77},
 {id:'violet-giant',tint:0x8e82bb,emissive:0x160d2b,atmosphere:0xc6b8ff,roughness:.82}
];
const COMET_PALETTES={DESPRENDIMIENTO:['#eef7ff','#8ec9ff','#d9e9f5'],TUNEL:['#ffffff','#79a9ff','#b9d5f4'],LUZ:['#fffbe9','#9ccaff','#ead8ba'],MEMORIA:['#f7f4eb','#adc7db','#d9c7ae'],FRONTERA:['#f4f8ff','#7da5e8','#c8d8ee'],RETORNO:['#fffaf0','#9ec3e5','#ead9bd']};

const tailVertex=`attribute float aSize;attribute float aSeed;attribute vec3 color;uniform float uTime;uniform float uOpacity;varying vec3 vColor;varying float vAlpha;varying float vSeed;void main(){vec3 p=position;float trail=max(0.0,-p.z);p.x+=sin(uTime*.7+aSeed*19.0+trail*.08)*(.025+trail*.003);p.y+=cos(uTime*.55+aSeed*13.0+trail*.06)*(.018+trail*.002);vec4 mv=modelViewMatrix*vec4(p,1.0);float perspective=230.0/max(1.0,-mv.z);gl_PointSize=clamp(aSize*perspective,1.0,72.0);gl_Position=projectionMatrix*mv;vColor=color;vAlpha=uOpacity*(1.0-smoothstep(26.0,39.0,trail));vSeed=aSeed;}`;
const tailFragment=`precision mediump float;varying vec3 vColor;varying float vAlpha;varying float vSeed;void main(){vec2 p=gl_PointCoord-.5;float r=length(p);float rag=.035*sin(atan(p.y,p.x)*5.0+vSeed*17.0);float a=(1.0-smoothstep(.18,.52,r+rag))*vAlpha;if(a<.008)discard;gl_FragColor=vec4(vColor,a);}`;
function tailMaterial(opacity){return new THREE.ShaderMaterial({vertexShader:tailVertex,fragmentShader:tailFragment,uniforms:{uTime:{value:0},uOpacity:{value:opacity}},transparent:true,depthWrite:false,depthTest:false,toneMapped:false,blending:THREE.AdditiveBlending});}
function buildTailGeometry(count,dust=false){const positions=new Float32Array(count*3),sizes=new Float32Array(count),seeds=new Float32Array(count),colors=new Float32Array(count*3);const c0=new THREE.Color(dust?0xffe2b8:0xf7fbff),c1=new THREE.Color(dust?0xd4a878:0x78a8ff);for(let i=0;i<count;i++){const t=i/(count-1),s=i*3.17+17.1,spread=(dust?.12:.07)+t*(dust?2.9:1.6),curve=dust?Math.pow(t,1.35)*2.8:0;positions[i*3]=(hash(s)-.5)*spread+curve;positions[i*3+1]=(hash(s+7.3)-.5)*spread*.62;positions[i*3+2]=-1.2-t*(dust?30:38);sizes[i]=(dust?5.0:4.2)+hash(s+11.2)*(dust?12:8)+t*(dust?5:3);seeds[i]=hash(s+19.4);const c=c0.clone().lerp(c1,t);colors[i*3]=c.r;colors[i*3+1]=c.g;colors[i*3+2]=c.b;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(positions,3));g.setAttribute('aSize',new THREE.BufferAttribute(sizes,1));g.setAttribute('aSeed',new THREE.BufferAttribute(seeds,1));g.setAttribute('color',new THREE.BufferAttribute(colors,3));g.computeBoundingSphere();return g;}

export class CinematicEncounterSystem extends Base{
 constructor(scene,renderer=null){super(scene,renderer);this.planetVariantCursor=0;this.proceduralCycle=0;this.ionTailGeometry=buildTailGeometry(150,false);this.dustTailGeometry=buildTailGeometry(120,true);this.stats.planetVariants={last:null,shown:0,families:PLANET_VARIANTS.map(v=>v.id)};this.stats.cometRoute={guaranteedProcedural:true,longIonTail:true,longDustTail:true,passes:0};}
 createPlanet(p){const root=super.createPlanet(p),variant=PLANET_VARIANTS[this.planetVariantCursor++%PLANET_VARIANTS.length],mesh=root.userData.surfaceMesh||root.userData.body?.children?.[0];if(mesh?.material){mesh.material.color.set(variant.tint);mesh.material.emissive?.set?.(variant.emissive);mesh.material.emissiveIntensity=.045;mesh.material.roughness=variant.roughness;}const atmosphere=root.userData.atmosphere;if(atmosphere?.material?.uniforms?.uColor)atmosphere.material.uniforms.uColor.value.set(variant.atmosphere);const halo=root.children.find(o=>o.isSprite);if(halo?.material?.color)halo.material.color.set(variant.atmosphere);root.userData.planetVariant=variant;root.userData.enhancements?.push(`familia cromática ${variant.id}`);this.stats.planetVariants.last=variant.id;this.stats.planetVariants.shown++;return root;}
 createComet(){const root=super.createComet(),oldFx=root.userData.routeFx;if(oldFx){root.remove(oldFx);oldFx.traverse?.(o=>o.material?.dispose?.());}const ionMat=tailMaterial(.88),dustMat=tailMaterial(.58),ion=new THREE.Points(this.ionTailGeometry,ionMat),dust=new THREE.Points(this.dustTailGeometry,dustMat);ion.frustumCulled=false;dust.frustumCulled=false;ion.renderOrder=22;dust.renderOrder=21;const tails=new THREE.Group();tails.add(dust,ion);root.add(tails);root.userData.routeFx=tails;root.userData.ionTail=ion;root.userData.dustTail=dust;root.userData.enhancements?.push('cola iónica larga de partículas 3D','cola de polvo curvada de partículas 3D','cabeza luminosa con núcleo 67P');return root;}
 spawnProcedural(){this.proceduralCycle++;if(this.proceduralCycle%2===1){const side=this.proceduralCycle%4===1?-1:1,p=COMET_PALETTES[this.stage]||COMET_PALETTES.DESPRENDIMIENTO;this.spawnEncounter({id:`real-route-comet-${this.proceduralCycle}`,narrativeStage:this.stage,objectType:'comet',spawnPosition:{x:side*.72,y:(hash(this.proceduralCycle*2.7)-.5)*.46},focalApproach:true,trajectoryVector:{x:-side*.055,y:0,z:1},scale:1.18,speed:.92,palette:p,luminosity:.70,durationSeconds:18},{source:'procedural'});return;}super.spawnProcedural();}
 spawnEncounter(e,meta={source:'llm'}){const ok=super.spawnEncounter(e,meta);if(!ok)return false;const a=this.active[this.active.length-1];if(a?.type==='comet'){a.root.userData.ionTail?.material?.uniforms&&(a.root.userData.ionTail.material.uniforms.uOpacity.value=.88);a.root.userData.dustTail?.material?.uniforms&&(a.root.userData.dustTail.material.uniforms.uOpacity.value=.58);this.stats.cometRoute.passes++;}return true;}
 update(dt){super.update(dt);for(const a of this.active){if(a.type==='planet'){const v=a.root.userData.planetVariant,m=a.root.userData.surfaceMesh?.material;if(v&&m){m.color.set(v.tint);m.roughness=v.roughness;}}if(a.type!=='comet')continue;const t=clamp01(a.age/a.duration),near=Math.exp(-Math.pow((a.root.position.z+5)/28,2)),ion=a.root.userData.ionTail,dust=a.root.userData.dustTail;if(ion?.material?.uniforms){ion.material.uniforms.uTime.value=this.clock;ion.material.uniforms.uOpacity.value=.62+near*.34;ion.scale.z=1.0+near*.72;}if(dust?.material?.uniforms){dust.material.uniforms.uTime.value=this.clock*.82;dust.material.uniforms.uOpacity.value=.34+near*.36;dust.scale.z=.95+near*.58;dust.rotation.z=.06+smooth01(t)*.08;}const coma=a.root.userData.coma;if(coma?.material){coma.material.color.set(0xf4fbff);coma.material.opacity=.10+near*.18;}const halo=a.root.userData.comaHalo;if(halo?.material){halo.material.color.set(0xa8c8ed);halo.material.opacity=.018+near*.06;}}}
 dispose(){this.ionTailGeometry.dispose();this.dustTailGeometry.dispose();super.dispose();}
}
