import * as THREE from 'three';
import { CinematicEncounterSystem as Base } from './CinematicEncounterSystemV55.js?v=20260814-55';

const clamp01=v=>Math.max(0,Math.min(1,v));
const smooth01=v=>{const t=clamp01(v);return t*t*(3-2*t);};
const hash=n=>{const x=Math.sin(n*91.733+17.113)*43758.5453;return x-Math.floor(x);};

const PLANET_VARIANTS=[
 {id:'amber-gas-giant',kind:0,tint:0xc19057,secondary:0x6a4023,cloud:0xf1d2aa,emissive:0x21140b,atmosphere:0xf0c795,roughness:.84,bands:.94,clouds:.42,emission:.025,cloudDrift:.010},
 {id:'cyan-gas-giant',kind:0,tint:0x4f8fc5,secondary:0x214f75,cloud:0xb5e8f2,emissive:0x08162b,atmosphere:0x94ddff,roughness:.80,bands:.86,clouds:.48,emission:.030,cloudDrift:.013},
 {id:'ice-world',kind:1,tint:0xb9d8e8,secondary:0x668ca8,cloud:0xf2fbff,emissive:0x0a1d2b,atmosphere:0xd8efff,roughness:.69,bands:.18,clouds:.25,emission:.018,cloudDrift:.004},
 {id:'red-rocky',kind:2,tint:0xa9573f,secondary:0x47251f,cloud:0xd5a18d,emissive:0x1b0c09,atmosphere:0xc77a68,roughness:.96,bands:.08,clouds:.10,emission:.010,cloudDrift:.002},
 {id:'volcanic-world',kind:3,tint:0x2a1915,secondary:0x090706,cloud:0x7c4934,emissive:0xff5a18,atmosphere:0xd46932,roughness:.93,bands:.10,clouds:.07,emission:.42,cloudDrift:.001},
 {id:'violet-green-exotic',kind:4,tint:0x766eaa,secondary:0x315b50,cloud:0xa8d6bd,emissive:0x24153a,atmosphere:0xc4b3ff,roughness:.74,bands:.38,clouds:.40,emission:.075,cloudDrift:.008}
];

const COMET_ROUTE_MODES=['diagonal-cross','near-field-pass','overtake','distant-cross','fragment-swarm'];
const COMET_PALETTES={DESPRENDIMIENTO:['#eef7ff','#8ec9ff','#d9e9f5'],TUNEL:['#ffffff','#79a9ff','#b9d5f4'],LUZ:['#fffbe9','#9ccaff','#ead8ba'],MEMORIA:['#f7f4eb','#adc7db','#d9c7ae'],FRONTERA:['#f4f8ff','#7da5e8','#c8d8ee'],RETORNO:['#fffaf0','#9ec3e5','#ead9bd']};

const planetVertex=`varying vec3 vP;varying vec3 vN;void main(){vP=normalize(position);vN=normalize(normalMatrix*normal);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`;
const planetSurfaceFragment=`
precision mediump float;varying vec3 vP;varying vec3 vN;uniform float uTime,uKind,uBandStrength,uEmissionStrength,uOpacity;uniform vec3 uPrimary,uSecondary,uEmission;
float h(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453);}float n3(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);float n000=h(i),n100=h(i+vec3(1,0,0)),n010=h(i+vec3(0,1,0)),n110=h(i+vec3(1,1,0)),n001=h(i+vec3(0,0,1)),n101=h(i+vec3(1,0,1)),n011=h(i+vec3(0,1,1)),n111=h(i+vec3(1,1,1));return mix(mix(mix(n000,n100,f.x),mix(n010,n110,f.x),f.y),mix(mix(n001,n101,f.x),mix(n011,n111,f.x),f.y),f.z);}float fbm(vec3 p){float v=0.0,a=.5;for(int i=0;i<4;i++){v+=n3(p)*a;p=p*2.03+vec3(7.1,-3.7,5.2);a*=.5;}return v;}
void main(){vec3 p=vP;float macro=fbm(p*3.2),fine=fbm(p*9.0+vec3(2.1,-4.3,1.7));float band=.5+.5*sin((p.y*20.0+macro*3.8)*3.14159);band=smoothstep(.26,.78,band);float ice=smoothstep(.48,.78,macro*.70+fine*.30);float rock=smoothstep(.34,.76,macro*.55+fine*.45);float fiss=pow(max(0.0,1.0-abs(sin((p.x*21.0+p.y*17.0+p.z*13.0+fine*4.0)*2.2))),14.0);float exotic=.5+.5*sin((p.y*11.0+p.x*5.0+macro*2.4)*3.14159);float pattern=band;if(uKind>0.5&&uKind<1.5)pattern=ice;if(uKind>1.5&&uKind<2.5)pattern=rock;if(uKind>2.5&&uKind<3.5)pattern=macro*.48+fine*.52;if(uKind>3.5)pattern=exotic*.62+macro*.38;vec3 c=mix(uSecondary,uPrimary,clamp(pattern,0.0,1.0));float a=uOpacity*(.13+uBandStrength*(.16+.22*pattern));if(uKind>1.5&&uKind<2.5)a*=.72;if(uKind>2.5&&uKind<3.5){float hot=smoothstep(.64,.96,fiss+fine*.26)*uEmissionStrength;c=mix(c,uEmission,clamp(hot*1.25,0.0,1.0));a=max(a,hot*.82);}if(uKind>3.5)c=mix(c,vec3(.34,.62,.50),smoothstep(.62,.90,macro)*.34);float rim=pow(1.0-max(vN.z,0.0),2.0);c+=uEmission*(uEmissionStrength*.035+rim*uEmissionStrength*.018);if(a<.008)discard;gl_FragColor=vec4(c,a);}`;
const planetCloudFragment=`
precision mediump float;varying vec3 vP;uniform float uTime,uCloudStrength,uOpacity;uniform vec3 uCloudColor;float h(vec3 p){return fract(sin(dot(p,vec3(91.7,157.3,273.1)))*43758.5453);}float n3(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);float a=h(i),b=h(i+vec3(1,0,0)),c=h(i+vec3(0,1,0)),d=h(i+vec3(1,1,0)),e=h(i+vec3(0,0,1)),f1=h(i+vec3(1,0,1)),g=h(i+vec3(0,1,1)),j=h(i+vec3(1,1,1));return mix(mix(mix(a,b,f.x),mix(c,d,f.x),f.y),mix(mix(e,f1,f.x),mix(g,j,f.x),f.y),f.z);}float fbm(vec3 p){float v=0.0,a=.5;for(int i=0;i<4;i++){v+=n3(p)*a;p=p*2.07+vec3(3.2,-6.1,2.7);a*=.5;}return v;}void main(){float drift=uTime*.012;vec3 p=vP;float cs=cos(drift),sn=sin(drift);p.xz=mat2(cs,-sn,sn,cs)*p.xz;float macro=fbm(p*3.8),fine=fbm(p*10.5+vec3(4,-2,7));float mask=smoothstep(.56,.80,macro*.70+fine*.30);float belts=.58+.42*sin((p.y*13.0+macro*2.0)*3.14159);mask*=mix(.62,1.0,belts);float a=mask*uCloudStrength*uOpacity;if(a<.006)discard;gl_FragColor=vec4(uCloudColor,a);}`;
function surfaceMaterial(v){return new THREE.ShaderMaterial({vertexShader:planetVertex,fragmentShader:planetSurfaceFragment,uniforms:{uTime:{value:0},uKind:{value:v.kind},uBandStrength:{value:v.bands},uEmissionStrength:{value:v.emission},uOpacity:{value:1},uPrimary:{value:new THREE.Color(v.tint)},uSecondary:{value:new THREE.Color(v.secondary)},uEmission:{value:new THREE.Color(v.emissive)}},transparent:true,depthWrite:false,depthTest:true,toneMapped:false,blending:THREE.NormalBlending});}
function cloudMaterial(v){return new THREE.ShaderMaterial({vertexShader:planetVertex,fragmentShader:planetCloudFragment,uniforms:{uTime:{value:0},uCloudStrength:{value:v.clouds},uOpacity:{value:1},uCloudColor:{value:new THREE.Color(v.cloud)}},transparent:true,depthWrite:false,depthTest:true,toneMapped:false,blending:THREE.NormalBlending});}

const tailVertex=`attribute float aSize;attribute float aSeed;attribute vec3 color;uniform float uTime;uniform float uOpacity;varying vec3 vColor;varying float vAlpha;varying float vSeed;void main(){vec3 p=position;float trail=max(0.0,-p.z);p.x+=sin(uTime*.7+aSeed*19.0+trail*.08)*(.025+trail*.003);p.y+=cos(uTime*.55+aSeed*13.0+trail*.06)*(.018+trail*.002);vec4 mv=modelViewMatrix*vec4(p,1.0);float perspective=230.0/max(1.0,-mv.z);gl_PointSize=clamp(aSize*perspective,1.0,72.0);gl_Position=projectionMatrix*mv;vColor=color;vAlpha=uOpacity*(1.0-smoothstep(26.0,39.0,trail));vSeed=aSeed;}`;
const tailFragment=`precision mediump float;varying vec3 vColor;varying float vAlpha;varying float vSeed;void main(){vec2 p=gl_PointCoord-.5;float r=length(p);float rag=.035*sin(atan(p.y,p.x)*5.0+vSeed*17.0);float a=(1.0-smoothstep(.18,.52,r+rag))*vAlpha;if(a<.008)discard;gl_FragColor=vec4(vColor,a);}`;
function tailMaterial(opacity){return new THREE.ShaderMaterial({vertexShader:tailVertex,fragmentShader:tailFragment,uniforms:{uTime:{value:0},uOpacity:{value:opacity}},transparent:true,depthWrite:false,depthTest:false,toneMapped:false,blending:THREE.AdditiveBlending});}
function buildTailGeometry(count,dust=false){const positions=new Float32Array(count*3),sizes=new Float32Array(count),seeds=new Float32Array(count),colors=new Float32Array(count*3);const c0=new THREE.Color(dust?0xffe2b8:0xf7fbff),c1=new THREE.Color(dust?0xd4a878:0x78a8ff);for(let i=0;i<count;i++){const t=i/(count-1),s=i*3.17+17.1,spread=(dust?.12:.07)+t*(dust?2.9:1.6),curve=dust?Math.pow(t,1.35)*2.8:0;positions[i*3]=(hash(s)-.5)*spread+curve;positions[i*3+1]=(hash(s+7.3)-.5)*spread*.62;positions[i*3+2]=-1.2-t*(dust?30:38);sizes[i]=(dust?5.0:4.2)+hash(s+11.2)*(dust?12:8)+t*(dust?5:3);seeds[i]=hash(s+19.4);const c=c0.clone().lerp(c1,t);colors[i*3]=c.r;colors[i*3+1]=c.g;colors[i*3+2]=c.b;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(positions,3));g.setAttribute('aSize',new THREE.BufferAttribute(sizes,1));g.setAttribute('aSeed',new THREE.BufferAttribute(seeds,1));g.setAttribute('color',new THREE.BufferAttribute(colors,3));g.computeBoundingSphere();return g;}

export class CinematicEncounterSystem extends Base{
 constructor(scene,renderer=null){super(scene,renderer);this.planetVariantCursor=0;this.proceduralCycle=0;this.cometRouteCursor=0;this.ionTailGeometry=buildTailGeometry(180,false);this.dustTailGeometry=buildTailGeometry(150,true);this.stats.planetVariants={last:null,shown:0,families:PLANET_VARIANTS.map(v=>v.id),surfaceSignatures:true,bands:true,clouds:true,conditionalEmission:true};this.stats.cometRoute={guaranteedProcedural:true,longIonTail:true,longDustTail:true,crossingPaths:true,fragmentSwarm:true,routeModes:[...COMET_ROUTE_MODES],lastMode:null,passes:0};}
 createPlanet(p){const root=super.createPlanet(p),variant=PLANET_VARIANTS[this.planetVariantCursor++%PLANET_VARIANTS.length],mesh=root.userData.surfaceMesh||root.userData.body?.children?.[0],body=root.userData.body||root;if(mesh?.material){mesh.material.color.set(variant.tint);mesh.material.emissive?.set?.(variant.emissive);mesh.material.emissiveIntensity=variant.emission;mesh.material.roughness=variant.roughness;mesh.material.metalness=.002;}const surface=new THREE.Mesh(this.geometries.planet,surfaceMaterial(variant));surface.scale.setScalar(1.006);surface.renderOrder=13;body.add(surface);const clouds=new THREE.Mesh(this.geometries.planet,cloudMaterial(variant));clouds.scale.setScalar(1.022);clouds.renderOrder=14;root.add(clouds);const atmosphere=root.userData.atmosphere;if(atmosphere?.material?.uniforms?.uColor)atmosphere.material.uniforms.uColor.value.set(variant.atmosphere);const halo=root.children.find(o=>o.isSprite);if(halo?.material?.color)halo.material.color.set(variant.atmosphere);root.userData.planetVariant=variant;root.userData.surfaceLayer=surface;root.userData.cloudLayer=clouds;root.userData.enhancements?.push(`familia planetaria ${variant.id}`,'firma superficial procedural','bandas y relieve cromático diferenciados',variant.clouds>.12?'capa de nubes independiente':'atmósfera seca',variant.emission>.12?'emisión nocturna/volcánica':'emisión mínima');this.stats.planetVariants.last=variant.id;this.stats.planetVariants.shown++;return root;}
 createComet(){const root=super.createComet(),oldFx=root.userData.routeFx;if(oldFx){root.remove(oldFx);oldFx.traverse?.(o=>o.material?.dispose?.());}const ionMat=tailMaterial(.92),dustMat=tailMaterial(.64),ion=new THREE.Points(this.ionTailGeometry,ionMat),dust=new THREE.Points(this.dustTailGeometry,dustMat);ion.frustumCulled=false;dust.frustumCulled=false;ion.renderOrder=22;dust.renderOrder=21;const tails=new THREE.Group();tails.add(dust,ion);root.add(tails);root.userData.routeFx=tails;root.userData.ionTail=ion;root.userData.dustTail=dust;root.userData.enhancements?.push('cola iónica larga de partículas 3D','cola de polvo curvada de partículas 3D','cabeza luminosa con núcleo 67P');return root;}
 attachFragmentSwarm(root,side){if(root.userData.fragmentSwarm)return;const swarm=new THREE.Group();for(let i=0;i<6;i++){const mat=new THREE.MeshStandardMaterial({color:new THREE.Color().setHSL(.09+hash(i*2.3)*.04,.10,.24+hash(i*5.1)*.16),roughness:1,metalness:0,emissive:0x050607,emissiveIntensity:.04}),m=new THREE.Mesh(this.geometries.debris,mat),s=.55+hash(i*7.2)*1.15;m.scale.set(s,s*(.55+hash(i*3.1)*.55),s*(.64+hash(i*4.9)*.46));m.position.set(side*(.9+i*.48)+(hash(i*9.3)-.5)*.8,(hash(i*6.7)-.5)*2.3,-1.4-i*1.1);m.rotation.set(hash(i*2.1)*2,hash(i*4.2)*2,hash(i*5.8)*2);swarm.add(m);}root.add(swarm);root.userData.fragmentSwarm=swarm;root.userData.enhancements?.push('enjambre de seis fragmentos rocosos acompañantes');}
 applyCometRoute(a){const mode=COMET_ROUTE_MODES[this.cometRouteCursor++%COMET_ROUTE_MODES.length],side=this.cometRouteCursor%2===0?-1:1;a.routeMode=mode;a.root.userData.routeMode=mode;a.passSide=side;if(mode==='diagonal-cross'){a.root.position.x=-side*9.4;a.root.position.y=side*3.0;a.passHeight=-side*1.7;a.speed*=1.02;}else if(mode==='near-field-pass'){a.root.position.x=-side*5.0;a.root.position.y=-side*.9;a.passHeight=side*.35;a.root.scale.multiplyScalar(1.18);a.speed*=.96;}else if(mode==='overtake'){a.root.position.x=side*2.6;a.root.position.y=(hash(this.cometRouteCursor*3.2)-.5)*2.2;a.passHeight=a.root.position.y*.72;a.speed*=.80;}else if(mode==='distant-cross'){a.root.position.x=-side*15.5;a.root.position.y=side*5.2;a.passHeight=-side*3.9;a.root.scale.multiplyScalar(.76);a.speed*=1.08;}else{a.root.position.x=-side*8.2;a.root.position.y=side*1.9;a.passHeight=-side*.95;a.speed*=.90;this.attachFragmentSwarm(a.root,side);}a.root.userData.enhancements?.push(`trayectoria ${mode}`);this.stats.cometRoute.lastMode=mode;}
 spawnProcedural(){this.proceduralCycle++;if(this.proceduralCycle%2===1){const side=this.proceduralCycle%4===1?-1:1,p=COMET_PALETTES[this.stage]||COMET_PALETTES.DESPRENDIMIENTO;this.spawnEncounter({id:`real-route-comet-${this.proceduralCycle}`,narrativeStage:this.stage,objectType:'comet',spawnPosition:{x:side*.72,y:(hash(this.proceduralCycle*2.7)-.5)*.46},focalApproach:true,trajectoryVector:{x:-side*.055,y:0,z:1},scale:1.18,speed:.92,palette:p,luminosity:.70,durationSeconds:18},{source:'procedural'});return;}super.spawnProcedural();}
 spawnEncounter(e,meta={source:'llm'}){const ok=super.spawnEncounter(e,meta);if(!ok)return false;const a=this.active[this.active.length-1];if(a?.type==='comet'){this.applyCometRoute(a);a.root.userData.ionTail?.material?.uniforms&&(a.root.userData.ionTail.material.uniforms.uOpacity.value=.92);a.root.userData.dustTail?.material?.uniforms&&(a.root.userData.dustTail.material.uniforms.uOpacity.value=.64);this.stats.cometRoute.passes++;}return true;}
 update(dt){super.update(dt);for(const a of this.active){if(a.type==='planet'){const v=a.root.userData.planetVariant,m=a.root.userData.surfaceMesh?.material,surface=a.root.userData.surfaceLayer,clouds=a.root.userData.cloudLayer;if(v&&m){m.color.set(v.tint);m.emissive?.set?.(v.emissive);m.emissiveIntensity=v.emission;m.roughness=v.roughness;}if(surface?.material?.uniforms)surface.material.uniforms.uTime.value=this.clock;if(clouds?.material?.uniforms){clouds.material.uniforms.uTime.value=this.clock;clouds.rotation.y+=dt*(v?.cloudDrift||.004);}continue;}if(a.type!=='comet')continue;const t=clamp01(a.age/a.duration),near=Math.exp(-Math.pow((a.root.position.z+5)/28,2)),ion=a.root.userData.ionTail,dust=a.root.userData.dustTail,tails=a.root.userData.routeFx,side=a.passSide||1;if(ion?.material?.uniforms){ion.material.uniforms.uTime.value=this.clock;ion.material.uniforms.uOpacity.value=.66+near*.34;ion.scale.z=1.0+near*.82;}if(dust?.material?.uniforms){dust.material.uniforms.uTime.value=this.clock*.82;dust.material.uniforms.uOpacity.value=.38+near*.38;dust.scale.z=.95+near*.70;dust.rotation.z=.06+smooth01(t)*.10;}if(tails){const crossing=['diagonal-cross','near-field-pass','fragment-swarm'].includes(a.routeMode),yaw=crossing?-side*.22:(a.routeMode==='distant-cross'?-side*.12:0);tails.rotation.y+=(yaw-tails.rotation.y)*(1-Math.exp(-2.4*dt));}const swarm=a.root.userData.fragmentSwarm;if(swarm){swarm.rotation.z+=dt*.10;swarm.rotation.y+=dt*.06;}const coma=a.root.userData.coma;if(coma?.material){coma.material.color.set(0xf4fbff);coma.material.opacity=.12+near*.24;coma.scale.setScalar(4.4+near*3.0);}const halo=a.root.userData.comaHalo;if(halo?.material){halo.material.color.set(0xa8c8ed);halo.material.opacity=.025+near*.085;halo.scale.setScalar(7.5+near*5.0);}}}
 dispose(){this.ionTailGeometry.dispose();this.dustTailGeometry.dispose();super.dispose();}
}
