import * as THREE from 'three';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const clamp01=v=>Math.max(0,Math.min(1,v));
const STAGE_PALETTES={DESPRENDIMIENTO:['#07152d','#17265e','#8fb7ff'],TUNEL:['#050817','#17265e','#7b8fff'],LUZ:['#39235f','#8b6acb','#fff4dc'],MEMORIA:['#251b46','#725283','#e6a56f'],FRONTERA:['#0b1730','#344c78','#d5b482'],RETORNO:['#122c4c','#58718e','#f1e4c8']};
const STAGE_TYPES={DESPRENDIMIENTO:['comet','debris','light_filament'],TUNEL:['comet','planet','light_filament'],LUZ:['planet','comet','light_filament'],MEMORIA:['planet','comet','debris'],FRONTERA:['comet','light_filament','planet'],RETORNO:['planet','comet','debris']};
function glowTexture(){const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d'),g=x.createRadialGradient(32,32,0,32,32,32);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.18,'rgba(255,255,255,.34)');g.addColorStop(.58,'rgba(255,255,255,.06)');g.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=g;x.fillRect(0,0,64,64);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.generateMipmaps=false;return t;}
function atmosphereMaterial(color){return new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uColor:{value:new THREE.Color(color)},uOpacity:{value:.30}},vertexShader:`varying vec3 vN;varying vec3 vV;void main(){vec4 mv=modelViewMatrix*vec4(position,1.0);vN=normalize(normalMatrix*normal);vV=normalize(-mv.xyz);gl_Position=projectionMatrix*mv;}`,fragmentShader:`uniform vec3 uColor;uniform float uOpacity;varying vec3 vN;varying vec3 vV;void main(){float rim=pow(1.0-max(dot(vN,vV),0.0),2.15);float a=rim*uOpacity;gl_FragColor=vec4(uColor*a,a);}`});}

export class CinematicEncounterSystem{
 constructor(scene){this.scene=scene;this.group=new THREE.Group();scene.add(this.group);this.active=[];this.clock=0;this.nextAt=5.5;this.seq=0;this.stage='DESPRENDIMIENTO';this.maxActive=1;this.glow=glowTexture();this.geometries={planet:new THREE.SphereGeometry(2.35,24,16),atmosphere:new THREE.SphereGeometry(2.49,20,14),comet:new THREE.IcosahedronGeometry(.56,1),debris:new THREE.IcosahedronGeometry(.18,0)};this.keyLight=new THREE.DirectionalLight(0xffffff,.78);this.keyLight.position.set(4,3,2);scene.add(this.keyLight);this.fillLight=new THREE.AmbientLight(0x466080,.13);scene.add(this.fillLight);this.stats={active:0,spawned:0,llmSpawned:0,proceduralSpawned:0,visualEnhanced:0,lastType:null,lastSource:null,lastId:null,lastEnhancements:[],particleFX:{ready:false,mobileDisabled:true},textures:{disabled:true,reason:'mobile-low-allocation'}};}
 setStage(stage){if(stage&&stage!==this.stage){this.stage=stage;this.nextAt=Math.min(this.nextAt,this.clock+2.5);}}
 createPlanet(p){const root=new THREE.Group(),body=new THREE.Group(),mesh=new THREE.Mesh(this.geometries.planet,new THREE.MeshStandardMaterial({color:new THREE.Color(p[0]||'#1c3154'),roughness:.84,metalness:.01,emissive:new THREE.Color(p[1]||p[0]||'#233c67'),emissiveIntensity:.04}));body.add(mesh);root.add(body);const atmosphere=new THREE.Mesh(this.geometries.atmosphere,atmosphereMaterial(p[2]||'#bcd8ff'));root.add(atmosphere);const halo=new THREE.Sprite(new THREE.SpriteMaterial({map:this.glow,color:new THREE.Color(p[2]||'#dbe8ff'),transparent:true,opacity:.045,depthWrite:false,blending:THREE.AdditiveBlending}));halo.scale.set(5.9,5.9,1);root.add(halo);root.userData.body=body;root.userData.atmosphere=atmosphere;root.userData.enhancements=['superficie GPU compacta','atmósfera Fresnel','halo atmosférico','orientación dinámica de ruta'];return root;}
 createComet(p){const root=new THREE.Group(),body=new THREE.Group(),nucleus=new THREE.Mesh(this.geometries.comet,new THREE.MeshStandardMaterial({color:0x1c1e24,roughness:.96,metalness:.01,emissive:new THREE.Color(p[2]||'#dceaff'),emissiveIntensity:.045}));nucleus.scale.set(1,.8,.93);body.add(nucleus);root.add(body);const coma=new THREE.Sprite(new THREE.SpriteMaterial({map:this.glow,color:0xedf5ff,transparent:true,opacity:.18,depthWrite:false,blending:THREE.AdditiveBlending}));coma.scale.set(2.5,2.5,1);root.add(coma);const tail=new THREE.Sprite(new THREE.SpriteMaterial({map:this.glow,color:new THREE.Color(p[1]||'#7894c8'),transparent:true,opacity:.075,depthWrite:false,blending:THREE.AdditiveBlending}));tail.position.set(0,0,-3.4);tail.scale.set(2.0,7.0,1);tail.rotation.z=Math.PI*.5;root.add(tail);root.userData.body=body;root.userData.routeFx=tail;root.userData.enhancements=['núcleo facetado compacto','coma dinámica','cola GPU alineada a trayectoria'];return root;}
 createFilament(p){const root=new THREE.Group();for(let i=0;i<2;i++){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:this.glow,color:new THREE.Color(p[(i+1)%p.length]||p[0]),transparent:true,opacity:.040,depthWrite:false,blending:THREE.AdditiveBlending}));s.position.set((i-.5)*1.3,(i?-.35:.35),(i-.5)*2.0);s.scale.set(1.8,7.0,1);root.add(s);}root.userData.enhancements=['filamento GPU compacto'];return root;}
 createDebris(){const root=new THREE.Group(),body=new THREE.Group();for(let i=0;i<3;i++){const mesh=new THREE.Mesh(this.geometries.debris,new THREE.MeshStandardMaterial({color:0x464b54,roughness:1,metalness:.02}));mesh.position.set((i-1)*.85,Math.sin(i*1.7)*.5,(i-1)*1.1);mesh.scale.setScalar(.8+i*.18);body.add(mesh);}root.add(body);root.userData.body=body;root.userData.enhancements=['fragmentos compactos','rotación local'];return root;}
 create(type,p){if(type==='planet')return this.createPlanet(p);if(type==='comet')return this.createComet(p);if(type==='light_filament')return this.createFilament(p);return this.createDebris();}
 applyRoute(root,type,palette,velocity,opts){root.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),velocity.clone().normalize());const enhancements=root.userData.enhancements||(root.userData.enhancements=[]);if(type==='planet'){const wake=new THREE.Sprite(new THREE.SpriteMaterial({map:this.glow,color:new THREE.Color(palette[1]||palette[0]),transparent:true,opacity:.032,depthWrite:false,blending:THREE.AdditiveBlending}));wake.position.set(0,0,-4.0);wake.scale.set(2.2,6.4,1);wake.rotation.z=Math.PI*.5;root.add(wake);root.userData.routeFx=wake;enhancements.push('estela compacta alineada a ruta');}else if(type==='comet')enhancements.push('cola orientada por vector de trayectoria');if(opts.focalApproach)enhancements.push('aproximación corregida al punto focal');}
 spawnEncounter(e,meta={source:'llm'}){if(!e||this.active.length>=this.maxActive)return false;const palette=Array.isArray(e.palette)&&e.palette.length?e.palette:(STAGE_PALETTES[e.narrativeStage]||STAGE_PALETTES[this.stage]);const type=e.objectType||'comet',root=this.create(type,palette);this.seq++;const id=e.id||`encounter-${this.seq}`,sx=clamp(Number(e.spawnPosition?.x)||0,-1.5,1.5),sy=clamp(Number(e.spawnPosition?.y)||0,-1.5,1.5);root.position.set(sx*9.2,sy*5.6,-112);const raw=new THREE.Vector3(Number(e.trajectoryVector?.x)||0,Number(e.trajectoryVector?.y)||0,Math.abs(Number(e.trajectoryVector?.z)||1));if(e.focalApproach){raw.x-=sx*.12;raw.y-=sy*.08;}const velocity=raw.normalize(),speed=clamp(Number(e.speed)||.8,.25,4)*15,duration=clamp(Number(e.durationSeconds)||12,8,24),luminosityFactor=clamp(.62+(Number(e.luminosity)||.6)*.34,.5,1.25),baseScale=type==='planet'?1.35:type==='comet'?1.15:1;root.scale.setScalar(clamp((Number(e.scale)||1)*baseScale,.5,3.6));this.applyRoute(root,type,palette,velocity,{focalApproach:Boolean(e.focalApproach)});this.group.add(root);this.active.push({id,root,age:0,duration,velocity,speed,spinY:.007,spinZ:.003,luminosityFactor,type,source:meta.source||'external'});this.nextAt=this.clock+Math.max(6,Math.min(9,duration*.45));this.stats.spawned++;if(meta.source==='llm'){this.stats.llmSpawned++;this.stats.visualEnhanced++;}else this.stats.proceduralSpawned++;this.stats.lastType=type;this.stats.lastSource=meta.source||'external';this.stats.lastId=id;this.stats.lastEnhancements=[...(root.userData.enhancements||[])];return true;}
 spawnProcedural(){const types=STAGE_TYPES[this.stage]||STAGE_TYPES.DESPRENDIMIENTO,palette=STAGE_PALETTES[this.stage]||STAGE_PALETTES.DESPRENDIMIENTO,phase=(this.seq+1)*1.618,type=types[this.seq%types.length],x=Math.sin(phase*1.71)*.62,y=Math.cos(phase*1.13)*.40;this.spawnEncounter({id:`mobile-cosmic-${this.seq+1}`,narrativeStage:this.stage,objectType:type,spawnPosition:{x,y},focalApproach:true,trajectoryVector:{x:-x*.035,y:-y*.026,z:1},scale:type==='planet'?1.15:1,speed:.76,palette,luminosity:.52,durationSeconds:12},{source:'procedural'});}
 setOpacity(root,k){root.traverse(o=>{const m=o.material;if(!m)return;for(const x of(Array.isArray(m)?m:[m])){if(x.uniforms?.uOpacity){if(x.userData.baseUOpacity===undefined)x.userData.baseUOpacity=x.uniforms.uOpacity.value;x.uniforms.uOpacity.value=x.userData.baseUOpacity*k;}else if(x.transparent){if(x.userData.baseOpacity===undefined)x.userData.baseOpacity=x.opacity??1;x.opacity=x.userData.baseOpacity*k;}}});}
 update(dt){this.clock+=dt;for(let i=this.active.length-1;i>=0;i--){const a=this.active[i];a.age+=dt;const t=clamp01(a.age/a.duration),ease=t*t*(3-2*t);a.root.position.addScaledVector(a.velocity,a.speed*(.72+ease*.95)*dt);const body=a.root.userData.body||a.root;body.rotation.y+=dt*a.spinY;body.rotation.z+=dt*a.spinZ;const atmosphere=a.root.userData.atmosphere;if(atmosphere?.material?.uniforms?.uOpacity)atmosphere.material.uniforms.uOpacity.value=.28+.08*a.luminosityFactor+.04*ease;const fx=a.root.userData.routeFx;if(fx?.material){const base=fx.material.userData.baseOpacity??fx.material.opacity;fx.material.userData.baseOpacity=base;fx.material.opacity=base*(.78+.22*Math.sin(this.clock*1.3));}const opacity=clamp01(t/.12)*(1-clamp01((t-.82)/.18));this.setOpacity(a.root,opacity*a.luminosityFactor);if(t>=1||a.root.position.z>15){this.group.remove(a.root);this.disposeRoot(a.root);this.active.splice(i,1);}}if(this.clock>=this.nextAt&&this.active.length<this.maxActive)this.spawnProcedural();this.stats.active=this.active.length;}
 disposeRoot(root){root.traverse(o=>{const m=o.material;if(Array.isArray(m))m.forEach(x=>x.dispose?.());else m?.dispose?.();});}
 dispose(){for(const a of this.active)this.disposeRoot(a.root);this.active=[];for(const g of Object.values(this.geometries))g.dispose();this.glow.dispose();this.scene.remove(this.group);this.scene.remove(this.keyLight);this.scene.remove(this.fillLight);}
}
