import * as THREE from 'three';
import { CinematicEncounterSystem as Base } from './MobileCinematicEncounterSystem.js?v=20260813-49';
import { MobileAstronomicalTexturePool } from '../assets/MobileAstronomicalTexturePool.js?v=20260813-50';

function hotRockMaterial(){return new THREE.ShaderMaterial({transparent:true,uniforms:{uTime:{value:0},uHeat:{value:.35},uOpacity:{value:1}},vertexShader:`varying vec3 p,n;void main(){p=position;n=normalize(normalMatrix*normal);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec3 p,n;uniform float uTime,uHeat,uOpacity;float h(vec3 q){return fract(sin(dot(q,vec3(17.1,43.3,91.7)))*43758.5);}void main(){float g=h(floor(p*18.)),lead=smoothstep(-.28,.48,p.z),cr=pow(abs(sin(p.x*24.+p.y*17.)*sin(p.y*29.-p.z*19.)),18.);float l=.25+.75*max(dot(normalize(n),normalize(vec3(-.4,.55,.7))),0.);vec3 base=mix(vec3(.014,.011,.009),vec3(.105,.072,.045),g*.6)*l;float hot=clamp((lead*.72+cr)*uHeat,0.,1.5);vec3 e=mix(vec3(1.,.045,.002),vec3(1.,.88,.3),clamp(hot*.75,0.,1.));gl_FragColor=vec4(base+e*hot*.82,uOpacity);}`});}

export class CinematicEncounterSystem extends Base{
  constructor(scene,renderer=null){super(scene,renderer);this.texturePool=new MobileAstronomicalTexturePool(renderer);this.hotShellGeo=new THREE.IcosahedronGeometry(.64,2);this.stats.textures={...this.texturePool.stats};}
  createPlanet(p){const root=super.createPlanet(p);const mesh=root.userData.body?.children?.[0];if(mesh){root.userData.surfaceMesh=mesh;mesh.material.roughness=.72;mesh.material.metalness=.002;}root.userData.enhancements.push('textura astronómica real bajo demanda');return root;}
  createComet(p){
    const root=new THREE.Group(),body=new THREE.Group(),rock=hotRockMaterial(),nucleus=new THREE.Mesh(this.geometries.comet,rock);nucleus.scale.set(1,.78,.92);body.add(nucleus);root.add(body);
    const shellMat=new THREE.MeshBasicMaterial({color:0xff6a18,transparent:true,opacity:.05,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.BackSide}),shell=new THREE.Mesh(this.hotShellGeo,shellMat);shell.scale.set(1.05,.82,.96);root.add(shell);
    const coma=new THREE.Sprite(new THREE.SpriteMaterial({map:this.glow,color:0xffd0a0,transparent:true,opacity:.14,depthWrite:false,blending:THREE.AdditiveBlending}));coma.scale.set(2.5,2.5,1);root.add(coma);
    const tails=new THREE.Group();for(let i=0;i<5;i++){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:this.glow,color:new THREE.Color(i<3?'#ff8b36':'#7ba8ff'),transparent:true,opacity:.07*(1-i*.12),depthWrite:false,blending:THREE.AdditiveBlending}));s.position.set((i%2?-.06:.04)*i,.02*i,-1.5-i*1.35);s.scale.set(1.1+i*.45,.45+i*.13,1);tails.add(s);}root.add(tails);
    root.userData.body=body;root.userData.routeFx=tails;root.userData.hotRock=rock;root.userData.hotShell=shell;root.userData.coma=coma;root.userData.enhancements=['núcleo rocoso facetado','fisuras incandescentes','ablación térmica frontal','plasma','cola de polvo','adelantamiento relativo'];return root;
  }
  spawnEncounter(e,meta={source:'llm'}){const ok=super.spawnEncounter(e,meta);if(!ok)return false;const a=this.active[this.active.length-1];if(!a)return true;if(a.type==='comet'){a.speed*=.62;a.duration=Math.max(15,a.duration);a.root.userData.enhancements?.push('velocidad relativa menor al túnel: la cámara lo adelanta');}if(a.type==='planet')void this.texturePool.enhancePlanet(a.root,{...e,narrativeStage:e.narrativeStage||this.stage}).then(done=>{if(done){this.stats.visualEnhanced++;this.stats.lastEnhancements=[...(a.root.userData.enhancements||[])];}});return true;}
  update(dt){super.update(dt);for(const a of this.active){if(a.type!=='comet')continue;const z=a.root.position.z,near=Math.exp(-Math.pow((z+2)/27,2)),heat=.42+near*1.45,rock=a.root.userData.hotRock,shell=a.root.userData.hotShell,coma=a.root.userData.coma;if(rock?.uniforms){rock.uniforms.uTime.value=this.clock;rock.uniforms.uHeat.value=heat;}if(shell){shell.material.opacity=.035+.22*near;shell.scale.set(1.05+near*.08,.82+near*.06,.96+near*.10);}if(coma){coma.material.opacity=.10+.22*near;coma.scale.setScalar(2.2+near*1.7);}const fx=a.root.userData.routeFx;if(fx)fx.scale.z=1+near*1.7;}this.stats.textures={...this.texturePool.stats};}
  dispose(){this.texturePool.dispose();this.hotShellGeo.dispose();super.dispose();}
}
