import * as THREE from 'three';

const clamp01=v=>Math.max(0,Math.min(1,v));
const hex=v=>typeof v==='string'&&/^#[0-9a-fA-F]{6}$/.test(v);

export class NebulaDirectiveBridge{
 constructor(){this.current=null;this.target=null;this.mix=0;this.transitionSeconds=10;this.stats={active:false,darkZoneFraction:null,filamentDensity:null,luminousCore:null,chromaticRange:[]};}
 setDirective(update){if(!update||!Number.isFinite(update.darkZoneFraction)||!Number.isFinite(update.filamentDensity)||!update.luminousCore||!Array.isArray(update.chromaticRange))return false;const colors=update.chromaticRange.filter(hex).slice(0,3);if(!colors.length)return false;this.current=this.sample();this.target={darkZoneFraction:Math.max(.3,Math.min(1,update.darkZoneFraction)),filamentDensity:clamp01(update.filamentDensity),luminousCore:{x:Math.max(-1,Math.min(1,Number(update.luminousCore.x)||0)),y:Math.max(-1,Math.min(1,Number(update.luminousCore.y)||0))},chromaticRange:colors};this.mix=0;this.stats.active=true;return true;}
 sample(){return this.target||{darkZoneFraction:.6,filamentDensity:.3,luminousCore:{x:0,y:0},chromaticRange:['#0d1b4b','#6a0572','#ffffff']};}
 update(dt,warpField){if(!this.target||!warpField)return;this.mix=Math.min(1,this.mix+dt/this.transitionSeconds);const t=this.mix*this.mix*(3-2*this.mix),from=this.current||this.target,to=this.target,dark=THREE.MathUtils.lerp(from.darkZoneFraction,to.darkZoneFraction,t),filaments=THREE.MathUtils.lerp(from.filamentDensity,to.filamentDensity,t),cx=THREE.MathUtils.lerp(from.luminousCore.x,to.luminousCore.x,t),cy=THREE.MathUtils.lerp(from.luminousCore.y,to.luminousCore.y,t),colors=[0,1,2].map(i=>new THREE.Color(from.chromaticRange[i]||from.chromaticRange[from.chromaticRange.length-1]||'#ffffff').lerp(new THREE.Color(to.chromaticRange[i]||to.chromaticRange[to.chromaticRange.length-1]||'#ffffff'),t));const u=warpField.nebula?.material?.uniforms;if(u){u.uNarrativeBlend.value=1;u.uNarrativeDarkZone.value=dark;u.uNarrativeFilaments.value=filaments;u.uNarrativeCore.value.set(cx,cy);u.uNarrativeColor0.value.copy(colors[0]);u.uNarrativeColor1.value.copy(colors[1]);u.uNarrativeColor2.value.copy(colors[2]);}
 const deep=warpField.deepSpace;if(deep){deep.spectralColors=colors.map(c=>[c.r,c.g,c.b]);for(const sector of deep.sectors||[]){sector.group.position.x+=cx*.015;sector.group.position.y+=cy*.015;for(const layer of sector.layers||[]){if(layer.dust)layer.material.opacity=Math.min(.24,layer.material.opacity*(.82+dark*.42));else layer.material.opacity=Math.min(.13,layer.material.opacity*(.78+filaments*.48));}}}
 this.stats={active:true,darkZoneFraction:dark,filamentDensity:filaments,luminousCore:{x:cx,y:cy},chromaticRange:colors.map(c=>`#${c.getHexString()}`)};}
 clear(warpField){this.target=null;this.current=null;this.mix=0;const u=warpField?.nebula?.material?.uniforms;if(u)u.uNarrativeBlend.value=0;this.stats={active:false,darkZoneFraction:null,filamentDensity:null,luminousCore:null,chromaticRange:[]};}
}
