import * as THREE from 'three';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const clamp01=v=>clamp(v,0,1);
const lerp=(a,b,t)=>a+(b-a)*t;
const smooth01=v=>{const t=clamp01(v);return t*t*(3-2*t);};
const BASE_AXIS=new THREE.Vector3(0,0,1);
const RAD2DEG=180/Math.PI;

const PLANET_FAMILIES=[
 {id:'ocean-terra',kind:6,base:0x123f68,secondary:0x5f8451,accent:0xa48d62,cloud:0xf4f7f8,atmosphere:0x67b8e8,emissive:0x000000,roughness:.78,scale:3.35,cloudOpacity:.26},
 {id:'amber-gas-giant',kind:0,base:0x7d4d2b,secondary:0xc98f57,accent:0xe5c49a,cloud:0xf0d4ae,atmosphere:0xd49a68,emissive:0x000000,roughness:.72,scale:4.2,cloudOpacity:.14},
 {id:'cyan-gas-giant',kind:1,base:0x18556e,secondary:0x4fa8c0,accent:0xa8deea,cloud:0xd8f3f7,atmosphere:0x59c8df,emissive:0x000000,roughness:.68,scale:4.0,cloudOpacity:.15},
 {id:'ice-world',kind:2,base:0x789fb6,secondary:0xdcecf3,accent:0xffffff,cloud:0xffffff,atmosphere:0x9ed8f0,emissive:0x07131b,roughness:.84,scale:3.1,cloudOpacity:.10},
 {id:'red-rocky',kind:3,base:0x6b2a22,secondary:0xb85e46,accent:0xd69b75,cloud:0xc6a28e,atmosphere:0xc46b55,emissive:0x080100,roughness:.94,scale:2.8,cloudOpacity:.06},
 {id:'volcanic-world',kind:4,base:0x171312,secondary:0x5a281c,accent:0x9b4b27,cloud:0x6d554d,atmosphere:0xa23b22,emissive:0xff5a16,roughness:.90,scale:2.7,cloudOpacity:.05},
 {id:'violet-green-exotic',kind:5,base:0x382953,secondary:0x688f78,accent:0xa59ab6,cloud:0xc2cad5,atmosphere:0x8b74c6,emissive:0x2c1a42,roughness:.76,scale:3.2,cloudOpacity:.12}
];

function shuffle(a){const out=[...a];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
function route(mode,side=1){
 if(mode==='overtake')return{x0:side*1.25,x1:side*2.15,y0:-1.35,y1:-2.15,arc:.10*side,z0:-108,z1:9,travelMs:9200,close:true};
 if(mode==='near-field-pass')return{x0:-side*4.8,x1:side*5.0,y0:side*1.4,y1:-side*.9,arc:-side*.35,z0:-94,z1:7,travelMs:8600,close:true};
 if(mode==='diagonal-cross')return{x0:-side*7.2,x1:side*7.4,y0:side*2.5,y1:-side*2.0,arc:side*.50,z0:-104,z1:8,travelMs:9000,close:true};
 return{x0:-side*12.5,x1:side*11.8,y0:side*4.1,y1:-side*3.3,arc:side*1.0,z0:-135,z1:-22,travelMs:10800,close:false};
}
function routePosition(r,p,out=new THREE.Vector3()){return out.set(lerp(r.x0,r.x1,p),lerp(r.y0,r.y1,p)+Math.sin(p*Math.PI)*r.arc,lerp(r.z0,r.z1,p));}
function focalConeDeg(x,y,z){return Math.atan2(Math.hypot(x,y),Math.max(1,Math.abs(z)))*RAD2DEG;}

function softPointsMaterial(color,opacity,blend=THREE.AdditiveBlending){
 return new THREE.ShaderMaterial({transparent:true,depthWrite:false,depthTest:true,blending:blend,uniforms:{uColor:{value:new THREE.Color(color)},uOpacity:{value:opacity}},vertexShader:`attribute float aSize;varying float vAlpha;void main(){vec4 mv=modelViewMatrix*vec4(position,1.0);gl_Position=projectionMatrix*mv;gl_PointSize=clamp(aSize*(105.0/max(1.0,-mv.z)),1.0,20.0);vAlpha=1.0;}`,fragmentShader:`uniform vec3 uColor;uniform float uOpacity;varying float vAlpha;void main(){vec2 q=gl_PointCoord-.5;float r=length(q)*2.0;if(r>1.0)discard;float a=pow(1.0-r,1.8)*uOpacity*vAlpha;gl_FragColor=vec4(uColor,a);}`});
}
function makePoints(count,builder,color,opacity,blend){const pos=new Float32Array(count*3),sizes=new Float32Array(count);for(let i=0;i<count;i++){const p=builder(i,count);pos[i*3]=p.x;pos[i*3+1]=p.y;pos[i*3+2]=p.z;sizes[i]=p.size;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setAttribute('aSize',new THREE.BufferAttribute(sizes,1));const m=softPointsMaterial(color,opacity,blend);return new THREE.Points(g,m);}
function nucleusMaterial(){return new THREE.ShaderMaterial({uniforms:{uBase:{value:new THREE.Color(0x34383a)}},vertexShader:`varying vec3 vN;varying vec3 vP;void main(){vN=normalize(normalMatrix*normal);vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`uniform vec3 uBase;varying vec3 vN;varying vec3 vP;float h(vec3 p){return fract(sin(dot(p,vec3(17.17,41.73,93.11)))*43758.5453);}void main(){vec3 n=normalize(vN);float lit=.20+.64*max(dot(n,normalize(vec3(-.35,.48,.80))),0.0);float grain=.82+.20*h(floor(vP*5.0));float rim=pow(1.0-max(n.z,0.0),3.0)*.08;gl_FragColor=vec4(uBase*(lit*grain+rim),1.0);}`});}

const noiseGLSL=`
float hash31(vec3 p){p=fract(p*.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}
float noise3(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);float n000=hash31(i+vec3(0,0,0)),n100=hash31(i+vec3(1,0,0)),n010=hash31(i+vec3(0,1,0)),n110=hash31(i+vec3(1,1,0)),n001=hash31(i+vec3(0,0,1)),n101=hash31(i+vec3(1,0,1)),n011=hash31(i+vec3(0,1,1)),n111=hash31(i+vec3(1,1,1));float nx00=mix(n000,n100,f.x),nx10=mix(n010,n110,f.x),nx01=mix(n001,n101,f.x),nx11=mix(n011,n111,f.x);return mix(mix(nx00,nx10,f.y),mix(nx01,nx11,f.y),f.z);}
float fbm(vec3 p){float v=0.0,a=.54;for(int i=0;i<4;i++){v+=a*noise3(p);p=p*2.03+vec3(13.1,7.7,19.3);a*=.49;}return v;}`;

function planetSurfaceMaterial(f){return new THREE.ShaderMaterial({uniforms:{uBase:{value:new THREE.Color(f.base)},uSecond:{value:new THREE.Color(f.secondary)},uAccent:{value:new THREE.Color(f.accent)},uEmissive:{value:new THREE.Color(f.emissive)},uKind:{value:f.kind},uTime:{value:0}},vertexShader:`varying vec3 vN;varying vec3 vP;void main(){vN=normalize(normalMatrix*normal);vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`uniform vec3 uBase,uSecond,uAccent,uEmissive;uniform float uKind,uTime;varying vec3 vN;varying vec3 vP;${noiseGLSL}void main(){vec3 p=normalize(vP);float macro=fbm(p*2.35+vec3(1.7,4.3,7.1));float detail=fbm(p*7.2+vec3(8.4,2.1,5.6));float bandNoise=fbm(vec3(p.x*2.2,p.y*5.8,p.z*2.2)+vec3(0.0,uTime*.012,0.0));float bands=.5+.5*sin(p.y*19.0+bandNoise*4.2+uTime*.018);vec3 col=uBase;if(uKind<1.5){float storm=clamp(bands*.78+detail*.22,0.0,1.0);col=mix(uBase,uSecond,storm);col=mix(col,uAccent,smoothstep(.78,.97,storm)*.34);}else if(uKind<2.5){float ice=smoothstep(.36,.72,macro+.18*detail);col=mix(uBase,uSecond,ice);col=mix(col,uAccent,smoothstep(.72,.92,detail)*.24);}else if(uKind<3.5){float rock=smoothstep(.38,.70,macro+.16*detail);col=mix(uBase,uSecond,rock);col=mix(col,uAccent,smoothstep(.66,.88,detail)*.25);}else if(uKind<4.5){float crust=smoothstep(.34,.72,macro+.12*detail),lava=smoothstep(.78,.93,detail+.10*sin(p.y*17.0));col=mix(uBase,uSecond,crust);col=mix(col,uAccent,lava*.34);col+=uEmissive*lava*.50;}else if(uKind<5.5){float exotic=clamp(.52*macro+.48*bands,0.0,1.0);col=mix(uBase,uSecond,exotic);col=mix(col,uAccent,smoothstep(.72,.92,detail)*.18);}else{float landMask=smoothstep(.53,.62,macro+.07*(detail-.5));float landTone=clamp(.58*detail+.42*macro,0.0,1.0);vec3 land=mix(uSecond,uAccent,landTone*.58);col=mix(uBase,land,landMask);float polar=smoothstep(.74,.94,abs(p.y));col=mix(col,vec3(.88,.94,.98),polar*.72);float shelf=1.0-smoothstep(.0,.055,abs((macro+.07*(detail-.5))-.575));col=mix(col,vec3(.34,.58,.62),shelf*.10);}vec3 nn=normalize(vN);float direct=max(dot(nn,normalize(vec3(-.42,.54,.72))),0.0);float light=.12+.84*direct;float rim=pow(1.0-max(nn.z,0.0),2.7)*.055;gl_FragColor=vec4(col*light+uEmissive*.025+col*rim,1.0);}`});}
function planetCloudMaterial(f){return new THREE.ShaderMaterial({transparent:true,depthWrite:false,depthTest:true,blending:THREE.NormalBlending,uniforms:{uColor:{value:new THREE.Color(f.cloud)},uOpacity:{value:f.cloudOpacity},uTime:{value:0},uKind:{value:f.kind}},vertexShader:`varying vec3 vP;void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`uniform vec3 uColor;uniform float uOpacity,uTime,uKind;varying vec3 vP;${noiseGLSL}void main(){vec3 p=normalize(vP);vec3 drift=vec3(uTime*.012,uTime*.004,-uTime*.009);float n=fbm(p*5.2+drift),fine=fbm(p*11.0-drift*.45),bands=.5+.5*sin(p.y*21.0+fbm(p*3.2)*3.5+uTime*.014);float mask=uKind<1.5?smoothstep(.48,.75,.64*bands+.36*n):smoothstep(.57,.76,.72*n+.28*fine);if(uKind>2.5&&uKind<4.5)mask*=.34;float a=mask*uOpacity;gl_FragColor=vec4(uColor,a);}`});}
function atmosphereMaterial(f){return new THREE.ShaderMaterial({transparent:true,depthWrite:false,depthTest:true,side:THREE.BackSide,blending:THREE.AdditiveBlending,uniforms:{uColor:{value:new THREE.Color(f.atmosphere)},uOpacity:{value:f.kind===6?.22:.12}},vertexShader:`varying vec3 vN;varying vec3 vV;void main(){vec4 mv=modelViewMatrix*vec4(position,1.0);vN=normalize(normalMatrix*normal);vV=mv.xyz;gl_Position=projectionMatrix*mv;}`,fragmentShader:`uniform vec3 uColor;uniform float uOpacity;varying vec3 vN;varying vec3 vV;void main(){float rim=pow(1.0-max(dot(normalize(vN),normalize(-vV)),0.0),2.25);gl_FragColor=vec4(uColor,rim*uOpacity);}`});}

export class PhysicalEncounterRuntimeV66{
 constructor(scene,renderer=null){this.scene=scene;this.renderer=renderer;this.mobile=/iPad|iPhone|iPod|Android/i.test(navigator.userAgent||'')||innerWidth<800;this.group=new THREE.Group();this.group.name='URUXPhysicalEncounterRuntimeV66';scene.add(this.group);this.active=[];this.planetBag=shuffle(PLANET_FAMILIES.filter(f=>f.id!=='ocean-terra'));this.lastPlanetFamily=null;this.firstPlanetPending=true;this.nextPlanetAt=performance.now()+8200;this.nextAmbientCometAt=performance.now()+28000;this.stage='DESPRENDIMIENTO';this.stats={revision:'v66.2-focal-organic-relative-motion',visualRuntimeIndependentOfAI:true,legacyCinematicGraphActive:false,planetVariants:{families:PLANET_FAMILIES.map(x=>x.id),selectionMode:'seeded-shuffle-bag-v66.2',noImmediateRepeat:true,surfaceSignatures:true,organicFbmSurface:true,atmosphereShell:true,focalSpawn:true,focalConeMaxDeg:.15,motionModel:'shared-forward-speed-v66.2',firstFamilyPolicy:'ocean-terra-focal-intro',planetAppearanceRevision:'v66.3-focal-point-growth',spawnMode:'focal-point-growth-v66.3',spawnAtFocalOrigin:true,initialScaleRatio:.06,growthByDepth:true,lateralDriftAfterProgress:.16,clouds:true,lastSpawnPose:null,lastPose:null,speedRatio:null},cometRoute:{kinematics:'relative-velocity-aligned-v66',wallClockKinematics:true,tailFollowsRelativeVelocity:true,tailBehindMotion:true,tailAlignmentCosine:null,guaranteedRouteMode:'overtake',guaranteedCloseRoute:true,guaranteeSpawned:false,guaranteedActualCameraCrossing:false,actualCameraCrossings:0,actualCrossingPose:null,whiteoutProtected:true,physicalCorePriority:true,musicGated:true,visualRuntimeIndependentOfAI:true,cometBrightnessCap:.48,activeComets:0,passes:0,ambientPasses:0},musicDirection:{section:'INTRO',eventReadiness:0}};if(scene?.userData)scene.userData.uruxPhysicalEncounters=this;}
 setStage(stage){this.stage=stage||this.stage;}
 nextPlanet(){if(this.firstPlanetPending){this.firstPlanetPending=false;this.lastPlanetFamily='ocean-terra';return PLANET_FAMILIES[0];}if(!this.planetBag.length)this.planetBag=shuffle(PLANET_FAMILIES.filter(f=>f.id!=='ocean-terra'));let f=this.planetBag.shift();if(f.id===this.lastPlanetFamily&&this.planetBag.length){this.planetBag.push(f);f=this.planetBag.shift();}this.lastPlanetFamily=f.id;return f;}
 createCometRoot(){const root=new THREE.Group(),mat=nucleusMaterial();const a=new THREE.Mesh(new THREE.IcosahedronGeometry(.82,2),mat),b=new THREE.Mesh(new THREE.IcosahedronGeometry(.57,2),mat.clone());a.scale.set(1.15,.78,.83);b.position.set(.70,.08,-.05);b.scale.set(.86,.72,.78);root.add(a,b);const ionCount=this.mobile?150:260,dustCount=this.mobile?120:210,comaCount=this.mobile?76:120;const ion=makePoints(ionCount,(i,n)=>{const p=i/(n-1),s=.05+p*.30;return{x:(Math.random()-.5)*s,y:(Math.random()-.5)*s,z:-.9-p*23,size:1.45+(1-p)*1.35};},0x73cfff,.15,THREE.AdditiveBlending);const dust=makePoints(dustCount,(i,n)=>{const p=i/(n-1),s=.10+p*.82;return{x:-.35*p*p+(Math.random()-.5)*s,y:-.28*p*p+(Math.random()-.5)*s,z:-.75-p*16,size:1.25+(1-p)*1.45};},0xd8c2a4,.09,THREE.NormalBlending);const coma=makePoints(comaCount,()=>{const r=Math.pow(Math.random(),1.7)*1.9,th=Math.random()*Math.PI*2,cz=Math.random()*2-1,sr=Math.sqrt(1-cz*cz);return{x:Math.cos(th)*sr*r,y:Math.sin(th)*sr*r,z:cz*r,size:1.8+Math.random()*1.8};},0xaedcff,.07,THREE.AdditiveBlending);ion.name='ionTail';dust.name='dustTail';coma.name='coma';root.add(ion,dust,coma);root.userData={ion,dust,coma,surfaceMeshes:[a,b]};return root;}
 spawnComet(mode='overtake',guaranteed=false){if(this.active.some(x=>x.type==='comet'))return false;const side=Math.random()<.5?-1:1,r=route(mode,side),root=this.createCometRoot();root.position.set(r.x0,r.y0,r.z0);this.group.add(root);const a={type:'comet',root,route:{...r,mode,side,guaranteed,wallStart:performance.now(),crossed:false,lastVelocity:new THREE.Vector3(0,0,1)},born:performance.now()};this.active.push(a);this.stats.cometRoute.activeComets++;this.stats.cometRoute.passes++;if(guaranteed)this.stats.cometRoute.guaranteeSpawned=true;else this.stats.cometRoute.ambientPasses++;return true;}
 createPlanetRoot(f){const root=new THREE.Group(),geo=new THREE.SphereGeometry(1,this.mobile?36:48,this.mobile?24:32),surface=planetSurfaceMaterial(f),cloud=planetCloudMaterial(f),atmosphere=atmosphereMaterial(f),planet=new THREE.Mesh(geo,surface),cloudMesh=new THREE.Mesh(geo.clone(),cloud),atmoMesh=new THREE.Mesh(geo.clone(),atmosphere);cloudMesh.scale.setScalar(1.018);atmoMesh.scale.setScalar(1.045);root.add(planet,cloudMesh,atmoMesh);root.scale.setScalar(f.scale);root.userData={family:f,surface,cloud,atmosphere,planet,cloudMesh,atmoMesh};return root;}
 spawnPlanet(meta={}){if(this.active.some(x=>x.type==='planet'))return false;const f=this.nextPlanet(),root=this.createPlanetRoot(f),side=Math.random()<.5?-1:1,z0=-205,x0=0,y0=0,speedFactor=.97+Math.random()*.06,targetX=side*(7.2+Math.random()*2.2),targetY=(Math.random()-.5)*2.4,initialScaleRatio=.06;root.position.set(x0,y0,z0);root.scale.setScalar(f.scale*initialScaleRatio);this.group.add(root);this.active.push({type:'planet',root,f,speedFactor,side,z0,targetX,targetY,initialScaleRatio,age:0,born:performance.now()});const cone=focalConeDeg(x0,y0,z0);this.stats.planetVariants.lastFamily=f.id;this.stats.planetVariants.spawned=(this.stats.planetVariants.spawned||0)+1;this.stats.planetVariants.lastSpawnPose={x:0,y:0,z:z0,focalConeDeg:+cone.toFixed(3),family:f.id,initialScaleRatio};this.stats.planetVariants.speedRatio=+speedFactor.toFixed(3);return true;}
 spawnEncounter(e={},meta={source:'llm'}){const ctx=this.scene?.userData?.uruxMusicDirection||{};if(e.objectType==='comet'){if(!ctx.allowCloseComet)return false;return this.spawnComet(ctx.section==='CLIMAX'?'near-field-pass':'distant-cross',false);}if(e.objectType==='planet')return this.spawnPlanet(e);return false;}
 disposeObject(a){this.group.remove(a.root);a.root.traverse(o=>{o.geometry?.dispose?.();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose?.());else o.material?.dispose?.();});}
 update(dt,direction={}){const now=performance.now(),forward=Math.max(0,Number(direction.effectiveForwardSpeed??direction.speedTarget??0));this.stats.musicDirection.section=direction.section||'INTRO';this.stats.musicDirection.eventReadiness=+Number(direction.eventReadiness||0).toFixed(3);if(!this.stats.cometRoute.guaranteeSpawned&&direction.progress>.15&&direction.allowCloseComet)this.spawnComet('overtake',true);if(now>this.nextPlanetAt&&!this.active.some(x=>x.type==='planet')&&direction.progress>.045){this.spawnPlanet();this.nextPlanetAt=now+24000+Math.random()*12000;}if(this.stats.cometRoute.guaranteeSpawned&&now>this.nextAmbientCometAt&&!this.active.some(x=>x.type==='comet')&&(direction.visualEnergy||0)>.73){this.spawnComet('distant-cross',false);this.nextAmbientCometAt=now+30000+Math.random()*18000;}
  let maxNear=0;for(let i=this.active.length-1;i>=0;i--){const a=this.active[i];if(a.type==='planet'){a.age+=dt;a.root.position.z+=forward*a.speedFactor*dt;const travelP=clamp01((a.root.position.z-a.z0)/Math.max(.001,-3.2-a.z0)),growthP=Math.pow(smooth01(travelP),1.18),visualScaleRatio=lerp(a.initialScaleRatio,1,growthP),driftP=Math.pow(smooth01(clamp01((travelP-.16)/.74)),1.28);a.root.scale.setScalar(a.f.scale*visualScaleRatio);a.root.position.x=a.targetX*driftP;a.root.position.y=a.targetY*driftP*.72;a.root.rotation.y+=dt*(.025+.012*clamp01(forward/28));a.root.rotation.x+=dt*.0045;a.root.userData.surface.uniforms.uTime.value+=dt;a.root.userData.cloud.uniforms.uTime.value+=dt;const cone=focalConeDeg(a.root.position.x,a.root.position.y,a.root.position.z);this.stats.planetVariants.lastPose={x:+a.root.position.x.toFixed(2),y:+a.root.position.y.toFixed(2),z:+a.root.position.z.toFixed(2),focalConeDeg:+cone.toFixed(2),family:a.f.id,effectiveForwardSpeed:+forward.toFixed(2),speedRatio:+a.speedFactor.toFixed(3),travelProgress:+travelP.toFixed(3),visualScaleRatio:+visualScaleRatio.toFixed(3),focalPointGrowth:true};if(a.root.position.z>-3.2){this.disposeObject(a);this.active.splice(i,1);}continue;}const r=a.route,p=smooth01(clamp01((now-r.wallStart)/r.travelMs)),pos=routePosition(r,p),next=routePosition(r,Math.min(1,p+.006)),vel=next.clone().sub(pos);if(vel.lengthSq()<1e-7)vel.copy(r.lastVelocity);else r.lastVelocity.copy(vel);const dir=vel.normalize();a.root.position.copy(pos);const q=new THREE.Quaternion().setFromUnitVectors(BASE_AXIS,dir);a.root.quaternion.slerp(q,1-Math.exp(-10*Math.max(.001,dt)));const back=new THREE.Vector3(0,0,-1).applyQuaternion(a.root.quaternion).normalize(),align=back.dot(dir.clone().multiplyScalar(-1));this.stats.cometRoute.tailAlignmentCosine=+align.toFixed(3);const near=Math.exp(-Math.pow((pos.z+12)/24,2)),intensity=clamp(direction.cometIntensity??.34,.26,.48);maxNear=Math.max(maxNear,near*intensity);a.root.userData.ion.material.uniforms.uOpacity.value=(.09+near*.07)*intensity/.48;a.root.userData.dust.material.uniforms.uOpacity.value=(.045+near*.035)*intensity/.48;a.root.userData.coma.material.uniforms.uOpacity.value=(.035+near*.035)*intensity/.48;const pose={mode:r.mode,p:+p.toFixed(3),x:+pos.x.toFixed(2),y:+pos.y.toFixed(2),z:+pos.z.toFixed(2),tailAlignment:+align.toFixed(3)};if(r.close&&pos.z>-56&&pos.z<9&&Math.abs(pos.x)<5.5&&Math.abs(pos.y)<3.6&&!r.crossed){r.crossed=true;this.stats.cometRoute.actualCameraCrossings++;this.stats.cometRoute.actualCrossingPose=pose;if(r.guaranteed)this.stats.cometRoute.guaranteedActualCameraCrossing=true;}if(r.guaranteed)this.stats.cometRoute.lastGuaranteedPose=pose;if((now-r.wallStart)/r.travelMs>=1){this.disposeObject(a);this.active.splice(i,1);this.stats.cometRoute.activeComets=Math.max(0,this.stats.cometRoute.activeComets-1);}}
  if(this.scene?.userData)this.scene.userData.uruxEncounterBudget={closeComet:clamp(maxNear,0,.48),whiteoutProtection:true,updatedAt:now};}
 dispose(){for(const a of [...this.active])this.disposeObject(a);this.active.length=0;this.scene.remove(this.group);if(this.scene?.userData?.uruxPhysicalEncounters===this)this.scene.userData.uruxPhysicalEncounters=null;}
}
