import * as THREE from 'three';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const clamp01=v=>clamp(v,0,1);
const lerp=(a,b,t)=>a+(b-a)*t;
const smooth01=v=>{const t=clamp01(v);return t*t*(3-2*t);};
const BASE_AXIS=new THREE.Vector3(0,0,1);

const PLANET_FAMILIES=[
 {id:'amber-gas-giant',kind:0,base:0x9a6338,secondary:0xd9a266,cloud:0xf1d3a7,emissive:0x000000,roughness:.72,scale:4.2},
 {id:'cyan-gas-giant',kind:1,base:0x246e8e,secondary:0x73c7dc,cloud:0xd5f5ff,emissive:0x000000,roughness:.68,scale:4.0},
 {id:'ice-world',kind:2,base:0x9ebfd1,secondary:0xe7f6ff,cloud:0xffffff,emissive:0x07131b,roughness:.84,scale:3.1},
 {id:'red-rocky',kind:3,base:0x7c3025,secondary:0xc46a4f,cloud:0xb88a75,emissive:0x080100,roughness:.94,scale:2.8},
 {id:'volcanic-world',kind:4,base:0x231b19,secondary:0x6a2d19,cloud:0x6d554d,emissive:0xff5a16,roughness:.90,scale:2.7},
 {id:'violet-green-exotic',kind:5,base:0x473464,secondary:0x739b86,cloud:0xb6bfd1,emissive:0x34204c,roughness:.76,scale:3.2}
];

function shuffle(a){const out=[...a];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
function route(mode,side=1){
 if(mode==='overtake')return{x0:side*1.25,x1:side*2.15,y0:-1.35,y1:-2.15,arc:.10*side,z0:-108,z1:9,travelMs:9200,close:true};
 if(mode==='near-field-pass')return{x0:-side*4.8,x1:side*5.0,y0:side*1.4,y1:-side*.9,arc:-side*.35,z0:-94,z1:7,travelMs:8600,close:true};
 if(mode==='diagonal-cross')return{x0:-side*7.2,x1:side*7.4,y0:side*2.5,y1:-side*2.0,arc:side*.50,z0:-104,z1:8,travelMs:9000,close:true};
 return{x0:-side*12.5,x1:side*11.8,y0:side*4.1,y1:-side*3.3,arc:side*1.0,z0:-135,z1:-22,travelMs:10800,close:false};
}
function routePosition(r,p,out=new THREE.Vector3()){return out.set(lerp(r.x0,r.x1,p),lerp(r.y0,r.y1,p)+Math.sin(p*Math.PI)*r.arc,lerp(r.z0,r.z1,p));}

function softPointsMaterial(color,opacity,blend=THREE.AdditiveBlending){
 return new THREE.ShaderMaterial({transparent:true,depthWrite:false,depthTest:true,blending:blend,uniforms:{uColor:{value:new THREE.Color(color)},uOpacity:{value:opacity}},vertexShader:`attribute float aSize;varying float vAlpha;void main(){vec4 mv=modelViewMatrix*vec4(position,1.0);gl_Position=projectionMatrix*mv;gl_PointSize=clamp(aSize*(105.0/max(1.0,-mv.z)),1.0,20.0);vAlpha=1.0;}`,fragmentShader:`uniform vec3 uColor;uniform float uOpacity;varying float vAlpha;void main(){vec2 q=gl_PointCoord-.5;float r=length(q)*2.0;if(r>1.0)discard;float a=pow(1.0-r,1.8)*uOpacity*vAlpha;gl_FragColor=vec4(uColor,a);}`});
}
function makePoints(count,builder,color,opacity,blend){const pos=new Float32Array(count*3),sizes=new Float32Array(count);for(let i=0;i<count;i++){const p=builder(i,count);pos[i*3]=p.x;pos[i*3+1]=p.y;pos[i*3+2]=p.z;sizes[i]=p.size;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setAttribute('aSize',new THREE.BufferAttribute(sizes,1));const m=softPointsMaterial(color,opacity,blend);return new THREE.Points(g,m);}
function nucleusMaterial(){return new THREE.ShaderMaterial({uniforms:{uBase:{value:new THREE.Color(0x34383a)}},vertexShader:`varying vec3 vN;varying vec3 vP;void main(){vN=normalize(normalMatrix*normal);vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`uniform vec3 uBase;varying vec3 vN;varying vec3 vP;float h(vec3 p){return fract(sin(dot(p,vec3(17.17,41.73,93.11)))*43758.5453);}void main(){vec3 n=normalize(vN);float lit=.20+.64*max(dot(n,normalize(vec3(-.35,.48,.80))),0.0);float grain=.82+.20*h(floor(vP*5.0));float rim=pow(1.0-max(n.z,0.0),3.0)*.08;gl_FragColor=vec4(uBase*(lit*grain+rim),1.0);}`});}
function planetSurfaceMaterial(f){return new THREE.ShaderMaterial({uniforms:{uBase:{value:new THREE.Color(f.base)},uSecond:{value:new THREE.Color(f.secondary)},uEmissive:{value:new THREE.Color(f.emissive)},uKind:{value:f.kind},uTime:{value:0}},vertexShader:`varying vec3 vN;varying vec3 vP;void main(){vN=normalize(normalMatrix*normal);vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`uniform vec3 uBase,uSecond,uEmissive;uniform float uKind,uTime;varying vec3 vN;varying vec3 vP;float h(vec3 p){return fract(sin(dot(p,vec3(12.9898,78.233,39.425)))*43758.5453);}void main(){vec3 p=normalize(vP);float n=h(floor((p+1.0)*18.0));float bands=.5+.5*sin(p.y*28.0+n*2.2+uTime*.05);float rock=smoothstep(.25,.8,n);float ice=smoothstep(.35,.78,n+.22*abs(p.y));float lava=smoothstep(.73,.94,n+.12*sin(p.y*31.0));float gas=step(uKind,1.5);float tex=mix(rock,bands,gas);if(uKind>1.5&&uKind<2.5)tex=ice;if(uKind>4.5)tex=.5*bands+.5*rock;vec3 col=mix(uBase,uSecond,tex*.72);if(uKind>3.5&&uKind<4.5)col+=uEmissive*lava*.68;vec3 nn=normalize(vN);float light=.19+.75*max(dot(nn,normalize(vec3(-.42,.54,.72))),0.0);float rim=pow(1.0-max(nn.z,0.0),2.5)*.10;gl_FragColor=vec4(col*light+uEmissive*.035+col*rim,1.0);}`});}
function planetCloudMaterial(f){return new THREE.ShaderMaterial({transparent:true,depthWrite:false,depthTest:true,blending:THREE.NormalBlending,uniforms:{uColor:{value:new THREE.Color(f.cloud)},uTime:{value:0},uKind:{value:f.kind}},vertexShader:`varying vec3 vP;void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`uniform vec3 uColor;uniform float uTime,uKind;varying vec3 vP;float h(vec3 p){return fract(sin(dot(p,vec3(23.14,51.71,91.37)))*18347.17);}void main(){vec3 p=normalize(vP);float n=h(floor((p+1.0)*15.0+uTime*.03));float band=.5+.5*sin(p.y*32.0+uTime*.09+n*2.0);float a=smoothstep(.58,.86,mix(n,band,step(uKind,1.5)))*.18;if(uKind>2.5&&uKind<4.5)a*=.28;gl_FragColor=vec4(uColor,a);}`});}

export class PhysicalEncounterRuntimeV66{
 constructor(scene,renderer=null){this.scene=scene;this.renderer=renderer;this.mobile=/iPad|iPhone|iPod|Android/i.test(navigator.userAgent||'')||innerWidth<800;this.group=new THREE.Group();this.group.name='URUXPhysicalEncounterRuntimeV66';scene.add(this.group);this.active=[];this.planetBag=shuffle(PLANET_FAMILIES);this.lastPlanetFamily=null;this.nextPlanetAt=performance.now()+7500;this.nextAmbientCometAt=performance.now()+28000;this.stage='DESPRENDIMIENTO';this.stats={revision:'v66-lightweight-physical-encounters',visualRuntimeIndependentOfAI:true,legacyCinematicGraphActive:false,planetVariants:{families:PLANET_FAMILIES.map(x=>x.id),selectionMode:'seeded-shuffle-bag-v66',noImmediateRepeat:true,surfaceSignatures:true,clouds:true},cometRoute:{kinematics:'relative-velocity-aligned-v66',wallClockKinematics:true,tailFollowsRelativeVelocity:true,tailBehindMotion:true,tailAlignmentCosine:null,guaranteedRouteMode:'overtake',guaranteedCloseRoute:true,guaranteeSpawned:false,guaranteedActualCameraCrossing:false,actualCameraCrossings:0,actualCrossingPose:null,whiteoutProtected:true,physicalCorePriority:true,musicGated:true,visualRuntimeIndependentOfAI:true,cometBrightnessCap:.48,activeComets:0,passes:0,ambientPasses:0},musicDirection:{section:'INTRO',eventReadiness:0}};if(scene?.userData)scene.userData.uruxPhysicalEncounters=this;}
 setStage(stage){this.stage=stage||this.stage;}
 nextPlanet(){if(!this.planetBag.length)this.planetBag=shuffle(PLANET_FAMILIES);let f=this.planetBag.shift();if(f.id===this.lastPlanetFamily&&this.planetBag.length){this.planetBag.push(f);f=this.planetBag.shift();}this.lastPlanetFamily=f.id;return f;}
 createCometRoot(){const root=new THREE.Group(),mat=nucleusMaterial();const a=new THREE.Mesh(new THREE.IcosahedronGeometry(.82,2),mat),b=new THREE.Mesh(new THREE.IcosahedronGeometry(.57,2),mat.clone());a.scale.set(1.15,.78,.83);b.position.set(.70,.08,-.05);b.scale.set(.86,.72,.78);root.add(a,b);const ionCount=this.mobile?150:260,dustCount=this.mobile?120:210,comaCount=this.mobile?76:120;const ion=makePoints(ionCount,(i,n)=>{const p=i/(n-1),s=.05+p*.30;return{x:(Math.random()-.5)*s,y:(Math.random()-.5)*s,z:-.9-p*23,size:1.45+(1-p)*1.35};},0x73cfff,.15,THREE.AdditiveBlending);const dust=makePoints(dustCount,(i,n)=>{const p=i/(n-1),s=.10+p*.82;return{x:-.35*p*p+(Math.random()-.5)*s,y:-.28*p*p+(Math.random()-.5)*s,z:-.75-p*16,size:1.25+(1-p)*1.45};},0xd8c2a4,.09,THREE.NormalBlending);const coma=makePoints(comaCount,()=>{const r=Math.pow(Math.random(),1.7)*1.9,th=Math.random()*Math.PI*2,cz=Math.random()*2-1,sr=Math.sqrt(1-cz*cz);return{x:Math.cos(th)*sr*r,y:Math.sin(th)*sr*r,z:cz*r,size:1.8+Math.random()*1.8};},0xaedcff,.07,THREE.AdditiveBlending);ion.name='ionTail';dust.name='dustTail';coma.name='coma';root.add(ion,dust,coma);root.userData={ion,dust,coma,surfaceMeshes:[a,b]};return root;}
 spawnComet(mode='overtake',guaranteed=false){if(this.active.some(x=>x.type==='comet'))return false;const side=Math.random()<.5?-1:1,r=route(mode,side),root=this.createCometRoot();root.position.set(r.x0,r.y0,r.z0);this.group.add(root);const a={type:'comet',root,route:{...r,mode,side,guaranteed,wallStart:performance.now(),crossed:false,lastVelocity:new THREE.Vector3(0,0,1)},born:performance.now()};this.active.push(a);this.stats.cometRoute.activeComets++;this.stats.cometRoute.passes++;if(guaranteed)this.stats.cometRoute.guaranteeSpawned=true;else this.stats.cometRoute.ambientPasses++;return true;}
 createPlanetRoot(f){const root=new THREE.Group(),geo=new THREE.SphereGeometry(1,this.mobile?28:40,this.mobile?18:28),surface=planetSurfaceMaterial(f),cloud=planetCloudMaterial(f),planet=new THREE.Mesh(geo,surface),cloudMesh=new THREE.Mesh(geo.clone(),cloud);cloudMesh.scale.setScalar(1.018);root.add(planet,cloudMesh);root.scale.setScalar(f.scale);root.userData={family:f,surface,cloud,planet,cloudMesh};return root;}
 spawnPlanet(meta={}){if(this.active.some(x=>x.type==='planet'))return false;const f=this.nextPlanet(),root=this.createPlanetRoot(f),side=Math.random()<.5?-1:1;root.position.set(side*(9+Math.random()*5),(Math.random()-.5)*5,-150);this.group.add(root);this.active.push({type:'planet',root,f,z0:-150,z1:18,x0:root.position.x,x1:side*(7+Math.random()*5),y0:root.position.y,y1:root.position.y+(Math.random()-.5)*2,wallStart:performance.now(),travelMs:22000+Math.random()*6000});this.stats.planetVariants.lastFamily=f.id;this.stats.planetVariants.spawned=(this.stats.planetVariants.spawned||0)+1;return true;}
 spawnEncounter(e={},meta={source:'llm'}){const ctx=this.scene?.userData?.uruxMusicDirection||{};if(e.objectType==='comet'){if(!ctx.allowCloseComet)return false;return this.spawnComet(ctx.section==='CLIMAX'?'near-field-pass':'distant-cross',false);}if(e.objectType==='planet'){if(ctx.section==='INTRO'&&e.focalApproach)return false;return this.spawnPlanet(e);}return false;}
 disposeObject(a){this.group.remove(a.root);a.root.traverse(o=>{o.geometry?.dispose?.();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose?.());else o.material?.dispose?.();});}
 update(dt,direction={}){const now=performance.now();this.stats.musicDirection.section=direction.section||'INTRO';this.stats.musicDirection.eventReadiness=+Number(direction.eventReadiness||0).toFixed(3);if(!this.stats.cometRoute.guaranteeSpawned&&direction.progress>.15&&direction.allowCloseComet)this.spawnComet('overtake',true);if(now>this.nextPlanetAt&&!this.active.some(x=>x.type==='planet')&&direction.progress>.065){this.spawnPlanet();this.nextPlanetAt=now+22000+Math.random()*10000;}if(this.stats.cometRoute.guaranteeSpawned&&now>this.nextAmbientCometAt&&!this.active.some(x=>x.type==='comet')&&(direction.visualEnergy||0)>.73){this.spawnComet('distant-cross',false);this.nextAmbientCometAt=now+30000+Math.random()*18000;}
  let maxNear=0;for(let i=this.active.length-1;i>=0;i--){const a=this.active[i];if(a.type==='planet'){const p=clamp01((now-a.wallStart)/a.travelMs),s=smooth01(p);a.root.position.set(lerp(a.x0,a.x1,s),lerp(a.y0,a.y1,s),lerp(a.z0,a.z1,s));a.root.rotation.y+=dt*.055;a.root.rotation.x+=dt*.008;a.root.userData.surface.uniforms.uTime.value+=dt;a.root.userData.cloud.uniforms.uTime.value+=dt;if(p>=1){this.disposeObject(a);this.active.splice(i,1);}continue;}const r=a.route,p=smooth01(clamp01((now-r.wallStart)/r.travelMs)),pos=routePosition(r,p),next=routePosition(r,Math.min(1,p+.006)),vel=next.clone().sub(pos);if(vel.lengthSq()<1e-7)vel.copy(r.lastVelocity);else r.lastVelocity.copy(vel);const dir=vel.normalize();a.root.position.copy(pos);const q=new THREE.Quaternion().setFromUnitVectors(BASE_AXIS,dir);a.root.quaternion.slerp(q,1-Math.exp(-10*Math.max(.001,dt)));const back=new THREE.Vector3(0,0,-1).applyQuaternion(a.root.quaternion).normalize(),align=back.dot(dir.clone().multiplyScalar(-1));this.stats.cometRoute.tailAlignmentCosine=+align.toFixed(3);const near=Math.exp(-Math.pow((pos.z+12)/24,2)),intensity=clamp(direction.cometIntensity??.34,.26,.48);maxNear=Math.max(maxNear,near*intensity);a.root.userData.ion.material.uniforms.uOpacity.value=(.09+near*.07)*intensity/.48;a.root.userData.dust.material.uniforms.uOpacity.value=(.045+near*.035)*intensity/.48;a.root.userData.coma.material.uniforms.uOpacity.value=(.035+near*.035)*intensity/.48;const pose={mode:r.mode,p:+p.toFixed(3),x:+pos.x.toFixed(2),y:+pos.y.toFixed(2),z:+pos.z.toFixed(2),tailAlignment:+align.toFixed(3)};if(r.close&&pos.z>-56&&pos.z<9&&Math.abs(pos.x)<5.5&&Math.abs(pos.y)<3.6&&!r.crossed){r.crossed=true;this.stats.cometRoute.actualCameraCrossings++;this.stats.cometRoute.actualCrossingPose=pose;if(r.guaranteed)this.stats.cometRoute.guaranteedActualCameraCrossing=true;}if(r.guaranteed)this.stats.cometRoute.lastGuaranteedPose=pose;if((now-r.wallStart)/r.travelMs>=1){this.disposeObject(a);this.active.splice(i,1);this.stats.cometRoute.activeComets=Math.max(0,this.stats.cometRoute.activeComets-1);}}
  if(this.scene?.userData)this.scene.userData.uruxEncounterBudget={closeComet:clamp(maxNear,0,.48),whiteoutProtection:true,updatedAt:now};}
 dispose(){for(const a of [...this.active])this.disposeObject(a);this.active.length=0;this.scene.remove(this.group);if(this.scene?.userData?.uruxPhysicalEncounters===this)this.scene.userData.uruxPhysicalEncounters=null;}
}
