import * as THREE from 'three';

const STAGES=[
{id:'DESPRENDIMIENTO',label:'Desprendimiento',durationRange:[42,68],paletteHint:['#02030a','#07152d','#17265e'],encounterTypes:['debris','void_pulse','light_filament'],nebulaProfile:{density:.22,filamentDensity:.24,darkZoneFraction:.72}},
{id:'TUNEL',label:'Túnel',durationRange:[55,82],paletteHint:['#02020a','#0d1b4b','#4b0082'],encounterTypes:['debris','comet','light_filament','void_pulse'],nebulaProfile:{density:.42,filamentDensity:.58,darkZoneFraction:.58}},
{id:'LUZ',label:'Luz',durationRange:[45,70],paletteHint:['#13051e','#6a0572','#d946a8','#ffffff'],encounterTypes:['light_filament','planet','comet'],nebulaProfile:{density:.54,filamentDensity:.67,darkZoneFraction:.38}},
{id:'MEMORIA',label:'Memoria',durationRange:[58,92],paletteHint:['#08061c','#37206f','#a23885','#ffb25c'],encounterTypes:['planet','vessel','light_filament','debris'],nebulaProfile:{density:.48,filamentDensity:.50,darkZoneFraction:.44}},
{id:'FRONTERA',label:'Frontera',durationRange:[46,74],paletteHint:['#02030b','#18244b','#6d3b7e','#ffd08a'],encounterTypes:['void_pulse','vessel','light_filament'],nebulaProfile:{density:.36,filamentDensity:.34,darkZoneFraction:.62}},
{id:'RETORNO',label:'Retorno',durationRange:[52,84],paletteHint:['#050916','#183d6d','#8c5f9e','#fff4d6'],encounterTypes:['comet','debris','light_filament','planet'],nebulaProfile:{density:.31,filamentDensity:.45,darkZoneFraction:.50}}
];

class OpenRouterModelResolver{
 constructor(version='1.0.0'){this.version=version;this.storageKey='urux_model_id';}
 async resolve(){const models=await this.fetchEligibleModels();if(!models.length)return null;const saved=localStorage.getItem(this.storageKey);if(saved&&models.some(m=>m.id===saved))return saved;const payload=new TextEncoder().encode(`URUX${this.version}${JSON.stringify(models)}`),digest=await crypto.subtle.digest('SHA-256',payload),hex=[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join(''),index=parseInt(hex.slice(-8),16)%models.length,id=models[index].id;localStorage.setItem(this.storageKey,id);return id;}
 async fetchEligibleModels(){const response=await fetch('https://openrouter.ai/api/v1/models',{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`OpenRouter models request failed: ${response.status}`);const body=await response.json();return(body.data||[]).filter(m=>m.id?.endsWith(':free')).filter(m=>{const p=m.supported_parameters||[];return p.includes('structured_outputs')&&p.includes('response_format');}).sort((a,b)=>a.id.localeCompare(b.id));}
}

class NarrativeStateMachine{
 constructor(){this.index=0;this.elapsed=0;this.transitionAge=0;this.transitionDuration=10;this.transitioning=false;this.listeners=new Set();this.targetDuration=this.pickDuration(this.current);}
 get current(){return STAGES[this.index];}
 onTransition(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn);}
 update(dt){this.elapsed+=dt;if(!this.transitioning&&this.elapsed>=this.targetDuration)this.advance();if(this.transitioning){this.transitionAge+=dt;if(this.transitionAge>=this.transitionDuration)this.transitioning=false;}return{stage:this.current,elapsed:this.elapsed,targetDuration:this.targetDuration,transitioning:this.transitioning,transitionProgress:this.transitioning?Math.min(1,this.transitionAge/this.transitionDuration):1};}
 advance(){this.index=(this.index+1)%STAGES.length;this.elapsed=0;this.targetDuration=this.pickDuration(this.current);this.transitionDuration=8+Math.random()*4;this.transitionAge=0;this.transitioning=true;this.listeners.forEach(fn=>fn(this.current));}
 pickDuration(stage){const[min,max]=stage.durationRange;return min+Math.random()*(max-min);}
}

const SCHEMA={name:'urux_encounter_batch',strict:true,schema:{type:'object',additionalProperties:false,required:['encounters','nebulaUpdate'],properties:{encounters:{type:'array',minItems:3,maxItems:6,items:{type:'object',additionalProperties:false,required:['id','narrativeStage','objectType','spawnDepth','spawnPosition','focalApproach','trajectoryVector','scale','speed','palette','luminosity','durationSeconds'],properties:{id:{type:'string'},narrativeStage:{type:'string'},objectType:{enum:['planet','comet','debris','light_filament','vessel','void_pulse']},spawnDepth:{type:'number'},spawnPosition:{type:'object',additionalProperties:false,required:['x','y'],properties:{x:{type:'number'},y:{type:'number'}}},focalApproach:{type:'boolean'},trajectoryVector:{type:'object',additionalProperties:false,required:['x','y','z'],properties:{x:{type:'number'},y:{type:'number'},z:{type:'number'}}},scale:{type:'number'},speed:{type:'number'},palette:{type:'array',minItems:1,maxItems:6,items:{type:'string'}},luminosity:{type:'number'},durationSeconds:{type:'number'}}}},nebulaUpdate:{type:'object',additionalProperties:false,required:['darkZoneFraction','filamentDensity','luminousCore','chromaticRange'],properties:{darkZoneFraction:{type:'number',minimum:.3,maximum:1},filamentDensity:{type:'number',minimum:0,maximum:1},luminousCore:{type:'object',additionalProperties:false,required:['x','y'],properties:{x:{type:'number'},y:{type:'number'}}},chromaticRange:{type:'array',minItems:1,maxItems:8,items:{type:'string'}}}}}}};
const finite=v=>typeof v==='number'&&Number.isFinite(v),hex=v=>typeof v==='string'&&/^#[0-9a-fA-F]{6}$/.test(v);

class EncounterPlanner{
 constructor(resolver){this.resolver=resolver;this.buffer=[];this.lastRequestAt=-Infinity;this.inFlight=false;this.nebulaUpdate=null;this.retryNotBefore=0;this.budgetKey='urux_openrouter_daily_budget';}
 get pending(){return this.buffer.length;}
 consume(){return this.buffer.shift()||null;}
 budget(){const day=new Date().toISOString().slice(0,10);try{const b=JSON.parse(localStorage.getItem(this.budgetKey)||'null');if(b?.day===day&&Number.isInteger(b.requests)&&b.requests>=0)return b;}catch{}return{day,requests:0};}
 incrementBudget(){const b=this.budget();localStorage.setItem(this.budgetKey,JSON.stringify({day:b.day,requests:b.requests+1}));}
 async refill(stage,force=false){const now=performance.now();if(this.inFlight||(!force&&this.buffer.length>=1)||now-this.lastRequestAt<20000||Date.now()<this.retryNotBefore||this.budget().requests>=50)return false;const apiKey=localStorage.getItem('urux_openrouter_api_key');if(!apiKey)return false;this.inFlight=true;this.lastRequestAt=now;try{const model=await this.resolver.resolve();if(!model)return false;this.incrementBudget();const response=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json','HTTP-Referer':location.origin,'X-Title':'URUX Journey Director'},body:JSON.stringify({model,temperature:.72,provider:{require_parameters:true},response_format:{type:'json_schema',json_schema:SCHEMA},messages:[{role:'system',content:this.prompt(stage)},{role:'user',content:`Generate 3 to 6 future encounters for ${stage.id}.`}]})});if(response.status===429||response.status===503){const retryAfter=Number(response.headers.get('Retry-After'));if(Number.isFinite(retryAfter)&&retryAfter>0)this.retryNotBefore=Date.now()+retryAfter*1000;}if(!response.ok)throw new Error(`OpenRouter completion failed: ${response.status}`);const body=await response.json(),content=body.choices?.[0]?.message?.content;if(!content)return false;const parsed=JSON.parse(content);if(!this.validate(parsed,stage))return false;parsed.nebulaUpdate.darkZoneFraction=Math.max(.3,parsed.nebulaUpdate.darkZoneFraction);this.buffer.push(...parsed.encounters.map(e=>({...e,narrativeStage:stage.id,spawnDepth:0})));this.nebulaUpdate=parsed.nebulaUpdate;return true;}catch(error){console.warn('[URUX] Narrative batch rejected; procedural mode remains active.',error);return false;}finally{this.inFlight=false;}}
 validate(batch,stage){if(!batch||!Array.isArray(batch.encounters)||batch.encounters.length<3||batch.encounters.length>6)return false;const n=batch.nebulaUpdate;if(!n||!finite(n.darkZoneFraction)||n.darkZoneFraction<.3||n.darkZoneFraction>1||!finite(n.filamentDensity)||n.filamentDensity<0||n.filamentDensity>1||!n.luminousCore||!finite(n.luminousCore.x)||!finite(n.luminousCore.y)||!Array.isArray(n.chromaticRange)||!n.chromaticRange.length||!n.chromaticRange.every(hex))return false;const ids=new Set();for(const e of batch.encounters){if(!e||typeof e.id!=='string'||!e.id.trim()||ids.has(e.id)||e.narrativeStage!==stage.id||!stage.encounterTypes.includes(e.objectType)||e.spawnDepth!==0||!e.spawnPosition||!finite(e.spawnPosition.x)||!finite(e.spawnPosition.y)||Math.abs(e.spawnPosition.x)>1.5||Math.abs(e.spawnPosition.y)>1.5||!e.trajectoryVector||!finite(e.trajectoryVector.x)||!finite(e.trajectoryVector.y)||!finite(e.trajectoryVector.z)||Math.abs(e.trajectoryVector.x)+Math.abs(e.trajectoryVector.y)+Math.abs(e.trajectoryVector.z)<.001||!finite(e.scale)||e.scale<=0||e.scale>8||!finite(e.speed)||e.speed<=0||e.speed>4||!finite(e.luminosity)||e.luminosity<0||e.luminosity>3||!finite(e.durationSeconds)||e.durationSeconds<3||e.durationSeconds>45||!Array.isArray(e.palette)||!e.palette.length||!e.palette.every(hex))return false;ids.add(e.id);}return true;}
 prompt(stage){return`Eres el director narrativo del tránsito cósmico de URUX. Generas instrucciones para el motor Three.js que renderiza el viaje de un alma a través del cosmos. Responde ÚNICAMENTE con JSON válido, sin texto adicional, sin markdown, sin backticks. El JSON debe seguir exactamente el schema de encounters + nebulaUpdate. Cada encuentro debe tener una razón narrativa coherente con el estado: ${stage.id}. Usa únicamente estos objectType para este estado: ${stage.encounterTypes.join(', ')}. Los objetos nacen desde la profundidad (spawnDepth: 0) y avanzan hacia el observador. Mantén zonas oscuras (darkZoneFraction >= 0.3). La paleta cromática del estado actual es: ${stage.paletteHint.join(', ')}.`;}
}

class FocalTrajectoryEngine{
 constructor(){this.group=new THREE.Group();this.active=[];this.clock=0;this.nextAutonomousAt=2.5;this.sequence=0;}
 spawn(e){const object=this.createObject(e);object.position.set(e.spawnPosition.x*10,e.spawnPosition.y*7,-110);object.scale.setScalar(Math.max(.15,e.scale));this.group.add(object);const velocity=new THREE.Vector3(e.trajectoryVector.x,e.trajectoryVector.y,Math.abs(e.trajectoryVector.z||1)).normalize();this.active.push({encounter:e,object,age:0,velocity});}
 update(dt){for(let i=this.active.length-1;i>=0;i--){const item=this.active[i];item.age+=dt;item.object.position.addScaledVector(item.velocity,Math.max(.08,item.encounter.speed)*18*dt);if(!item.encounter.focalApproach)item.object.position.x+=Math.sin(item.age*.45+i)*.015;item.object.rotation.y+=dt*.08;item.object.rotation.z+=dt*.025;if(item.age>item.encounter.durationSeconds||item.object.position.z>12){this.group.remove(item.object);this.disposeObject(item.object);this.active.splice(i,1);}}}
 procedural(dt,stage){this.clock+=dt;this.group.rotation.z=Math.sin(this.clock*.05)*.008;this.group.position.x=Math.sin(this.clock*.09)*.06;if(this.clock<this.nextAutonomousAt||this.active.length>=2)return;this.sequence++;const phase=this.sequence*1.61803398875,type=stage.encounterTypes[this.sequence%stage.encounterTypes.length]||'light_filament',lateral=Math.sin(phase*.91)*.15;this.spawn({id:`procedural-${stage.id.toLowerCase()}-${this.sequence}`,narrativeStage:stage.id,objectType:type,spawnDepth:0,spawnPosition:{x:Math.sin(phase*2.1)*.72,y:Math.cos(phase*1.37)*.52},focalApproach:this.sequence%3!==0,trajectoryVector:{x:lateral,y:-lateral*.35,z:1},scale:.55+Math.abs(Math.sin(phase))*.9,speed:.42+Math.abs(Math.cos(phase*.7))*.42,palette:stage.paletteHint,luminosity:.28+Math.abs(Math.sin(phase*.44))*.42,durationSeconds:10+Math.abs(Math.cos(phase))*8});this.nextAutonomousAt=this.clock+5.5+Math.abs(Math.sin(phase))*4.5;}
 createObject(e){const color=new THREE.Color(e.palette[0]||'#ffffff'),emissive=new THREE.Color(e.palette[1]||e.palette[0]||'#ffffff'),material=new THREE.MeshStandardMaterial({color,emissive,emissiveIntensity:Math.max(0,e.luminosity),roughness:.7,metalness:.08,transparent:true,opacity:.82});let geometry;if(e.objectType==='planet')geometry=new THREE.IcosahedronGeometry(1.5,3);else if(e.objectType==='comet')geometry=new THREE.ConeGeometry(.35,3.8,12);else if(e.objectType==='vessel')geometry=new THREE.OctahedronGeometry(1.1,0);else if(e.objectType==='void_pulse')geometry=new THREE.TorusGeometry(1.8,.10,10,48);else if(e.objectType==='light_filament')geometry=new THREE.CylinderGeometry(.035,.16,5.5,8);else geometry=new THREE.DodecahedronGeometry(.75,0);const mesh=new THREE.Mesh(geometry,material);if(e.objectType==='comet'||e.objectType==='light_filament')mesh.rotation.x=Math.PI/2;return mesh;}
 disposeObject(object){object.traverse(child=>{child.geometry?.dispose?.();const m=child.material;if(Array.isArray(m))m.forEach(x=>x.dispose());else m?.dispose?.();});}
 dispose(){this.active.forEach(x=>this.disposeObject(x.object));this.active=[];this.group.clear();}
}

class CosmicPaletteDirector{
 constructor(scene){this.scene=scene;this.current=new THREE.Color('#02030a');this.target=this.current.clone();this.age=10;this.duration=10;this.darkZone=.6;this.filaments=.3;this.fog=new THREE.FogExp2('#010205',.0015);scene.fog=this.fog;this.light=new THREE.AmbientLight('#304060',.14);scene.add(this.light);}
 begin(stage,duration=10){this.current.copy(this.target);this.target.set(stage.paletteHint[1]||stage.paletteHint[0]||'#02030a');this.age=0;this.duration=Math.max(8,Math.min(12,duration));this.darkZone=Math.max(.3,stage.nebulaProfile.darkZoneFraction);this.filaments=stage.nebulaProfile.filamentDensity;}
 apply(update){if(!update)return;this.darkZone=Math.max(.3,update.darkZoneFraction);this.filaments=Math.max(0,Math.min(1,update.filamentDensity));if(update.chromaticRange?.[0])this.target.set(update.chromaticRange[0]);}
 update(dt){this.age=Math.min(this.duration,this.age+dt);const x=this.duration?this.age/this.duration:1,t=x*x*(3-2*x),color=this.current.clone().lerp(this.target,t),dim=THREE.MathUtils.lerp(.08,.28,1-this.darkZone);color.multiplyScalar(dim);this.fog.color.copy(color);this.fog.density=THREE.MathUtils.lerp(.0007,.0026,this.filaments);this.light.color.copy(color.clone().multiplyScalar(2.8));this.light.intensity=THREE.MathUtils.lerp(.06,.2,1-this.darkZone);}
 dispose(){this.scene.remove(this.light);if(this.scene.fog===this.fog)this.scene.fog=null;}
}

export class URUXJourneyAgent{
 constructor(scene){this.scene=scene;this.machine=new NarrativeStateMachine();this.resolver=new OpenRouterModelResolver('1.1.0');this.planner=new EncounterPlanner(this.resolver);this.trajectory=new FocalTrajectoryEngine();this.palette=new CosmicPaletteDirector(scene);this.encounterClock=0;this.started=false;scene.add(this.trajectory.group);this.palette.begin(this.machine.current,10);this.unsubscribe=this.machine.onTransition(stage=>{this.palette.begin(stage,10);void this.planner.refill(stage,true);});}
 start(){if(this.started)return;this.started=true;void this.planner.refill(this.machine.current,true);}
 update(dt){const snapshot=this.machine.update(dt);this.encounterClock+=dt;if(this.planner.pending<1)void this.planner.refill(snapshot.stage);if(this.encounterClock>=8){const encounter=this.planner.consume();if(encounter){this.trajectory.spawn(encounter);this.encounterClock=0;}}if(this.planner.pending<1)this.trajectory.procedural(dt,snapshot.stage);this.palette.apply(this.planner.nebulaUpdate);this.palette.update(dt);this.trajectory.update(dt);return snapshot;}
 dispose(){this.unsubscribe?.();this.scene.remove(this.trajectory.group);this.trajectory.dispose();this.palette.dispose();}
 get diagnostics(){const b=this.planner.budget();return{stage:this.machine.current.id,pending:this.planner.pending,model:localStorage.getItem('urux_model_id'),requestsToday:b.requests,requestsRemaining:Math.max(0,50-b.requests),llmConfigured:Boolean(localStorage.getItem('urux_openrouter_api_key'))};}
}

export function configureURUXOpenRouterKey(apiKey){if(typeof apiKey!=='string'||!apiKey.trim())throw new Error('A non-empty OpenRouter API key is required.');localStorage.setItem('urux_openrouter_api_key',apiKey.trim());return true;}
export function clearURUXOpenRouterKey(){localStorage.removeItem('urux_openrouter_api_key');}
