const STORAGE_KEY='urux_backend_url';
const DEFAULT_BACKEND_URL='https://music-pulse.habidomix.workers.dev';
const DEFAULT_TIMEOUT_MS=3000;
function normalize(url){if(typeof url!=='string')return null;const value=url.trim().replace(/\/$/,'');if(!/^https:\/\//i.test(value))return null;return value;}
export function configureURUXBackendURL(url){const normalized=normalize(url);if(!normalized)throw new Error('URUX backend URL must be a valid https URL.');localStorage.setItem(STORAGE_KEY,normalized);return normalized;}
export function clearURUXBackendURL(){localStorage.removeItem(STORAGE_KEY);}
export function getURUXBackendURL(){return normalize(localStorage.getItem(STORAGE_KEY)||DEFAULT_BACKEND_URL);}
export class URUXBackendClient{
 constructor(){this.lastStatus=null;this.lastError=null;this.lastModel=null;this.lastModelMode=null;this.lastWorkerVersion=null;this.openrouterUsage=null;this.openrouterKeyOk=null;this.requestAttempts=0;this.requestState='idle';}
 get configured(){return Boolean(getURUXBackendURL());}
 async health(){const base=getURUXBackendURL();if(!base)return{ok:false,configured:false};const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),3000);try{const r=await fetch(`${base}/health`,{signal:controller.signal,headers:{Accept:'application/json'},cache:'no-store'});const body=await r.json().catch(()=>({}));this.lastStatus=r.status;this.lastWorkerVersion=body.version||null;this.lastError=r.ok?null:`backend:${r.status}`;return{...body,httpStatus:r.status,configured:true};}catch(error){this.lastError=String(error);return{ok:false,configured:true,error:this.lastError};}finally{clearTimeout(timer);}}
 async openrouterStatus(){const base=getURUXBackend_URL;}
 async encounters(stage){const base=getURUXBackendURL();if(!base)return null;this.requestAttempts++;this.requestState='requesting';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),DEFAULT_TIMEOUT_MS);try{const r=await fetch(`${base}/v1/encounters`,{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({stage})});this.lastStatus=r.status;const body=await r.json().catch(()=>({}));if(r.status===429){const retryAfter=Number(r.headers.get('Retry-After'))||20;const error=new Error(`rate_limited:${retryAfter}`);error.retryAfter=retryAfter;this.requestState='rate_limited';throw error;}if(!r.ok){const detail=[body.error,body.detail].filter(Boolean).join(':');this.requestState='error';throw new Error(`backend:${r.status}${detail?`:${detail}`:''}`);}this.lastModel=body.model||null;this.lastModelMode=body.modelMode||null;this.lastError=null;this.requestState='success';void this.openrouterStatus();return body;}catch(error){this.lastError=String(error);if(this.requestState==='requesting')this.requestState=error?.name==='AbortError'?'timeout':'error';throw error;}finally{clearTimeout(timer);}}
}
